n2p2 - A neural network potential package: nnp Namespace Reference
nnp Namespace Reference
Classes
struct Atom
Storage for a single atom.
class CutoffFunction
class Dataset
Collect and process large data sets.
class Element
Contains element-specific data.
class ElementMap
Contains element map.
class GradientDescent
Weight updates based on simple gradient descent methods.
class InterfaceLammps
class KalmanFilter
Implementation of the Kalman filter method.
class Log
Logging class for library output.
class Mode
Base class for all NNP applications.
class NeuralNetwork
This class implements a feed-forward neural network.
class Prediction
class Settings
Reads and analyzes settings file and stores parameters.
class SetupAnalysis
class Stopwatch
Implements a simple stopwatch on different platforms.
struct Structure
Storage for one atomic configuration.
class SymmetryFunction
Symmetry function base class.
class SymmetryFunctionAngularNarrow
Angular symmetry function (type 3)
class SymmetryFunctionAngularWide
Angular symmetry function (type 9)
class SymmetryFunctionGroup
class SymmetryFunctionGroupAngularNarrow
Angular symmetry function group (type 3)
class SymmetryFunctionGroupAngularWide
Angular symmetry function group (type 3)
class SymmetryFunctionGroupRadial
Radial symmetry function group (type 2)
class SymmetryFunctionGroupWeightedAngular
Weighted angular symmetry function group (type 13)
class SymmetryFunctionGroupWeightedRadial
Weighted radial symmetry function group (type 12)
class SymmetryFunctionRadial
Radial symmetry function (type 2)
class SymmetryFunctionStatistics
class SymmetryFunctionWeightedAngular
Weighted angular symmetry function (type 13)
class SymmetryFunctionWeightedRadial
Weighted radial symmetry function (type 12)
class Training
Training methods.
class Updater
Base class for different weight update methods.
struct Vec3D
Vector in 3 dimensional real space.
Functions
vector< string > split (std::string const &input, char delimiter=' ')
Split string at each delimiter.
string trim (std::string const &line, std::string const &whitespace=" \")
Remove leading and trailing whitespaces from string.
string reduce (std::string const &line, std::string const &whitespace=" \", std::string const &fill=" ")
Replace multiple whitespaces with fill.
string pad (string const &input, size_t num, char fill, bool right)
string strpr (const char *format,...)
String version of printf function.
vector< string > createFileHeader (vector< string > const &title, vector< size_t > const &colSize, vector< string > const &colName, vector< string > const &colInfo, char const &commentChar)
void appendLinesToFile (std::ofstream &file, std::vector< std::string > const lines)
Append multiple lines of strings to open file stream.
void appendLinesToFile (FILE *const &file, std::vector< std::string > const lines)
Append multiple lines of strings to open file pointer.
double pow_int (double x, int n)
Integer version of power function, "fast exponentiation algorithm".
std::string pad (std::string const &input, std::size_t num, char fill=' ', bool right=true)
Pad string to given length with fill character.
std::vector< std::string > createFileHeader (std::vector< std::string > const &title, std::vector< std::size_t > const &colLength, std::vector< std::string > const &colName, std::vector< std::string > const &colInfo, char const &commentChar='#')
Generate output file header with info section and column labels.
template<typename K , typename V >
V const & safeFind (std::map< K, V > const &stdMap, typename std::map< K, V >::key_type const &key)
Safely access map entry.
template<typename T >
bool comparePointerTargets (T *lhs, T *rhs)
Compare pointer targets.
Vec3D operator+ (Vec3D lhs, Vec3D const &rhs)
Overload + operator to implement vector addition.
Vec3D operator- (Vec3D lhs, Vec3D const &rhs)
Overload - operator to implement vector subtraction.
Vec3D operator- (Vec3D v)
Overload - operator to implement vector sign change.
Vec3D operator* (Vec3D v, double const a)
Overload * operator to implement multiplication with scalar.
Vec3D operator/ (Vec3D v, double const a)
Overload / operator to implement division by scalar.
Vec3D operator* (double const a, Vec3D v)
Overload * operator to implement multiplication with scalar (scalar first).
Function Documentation
split()
std::vector< std::string > nnp::split (std::string const & input, char delimiter = ' ')
Split string at each delimiter.
Parameters
[in] input Input string.
[in] delimiter Delimiter character (default ' ').
Returns
Vector containing the string parts.
Definition at line 32 of file utility.cpp.
Referenced by nnp::Element::addSymmetryFunction(), nnp::Dataset::getNumStructures(), nnp::InterfaceLammps::initialize(), main(), nnp::Structure::readFromFile(), nnp::Structure::readFromLines(), nnp::ElementMap::registerElements(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionAngularNarrow::setParameters(), nnp::SymmetryFunction::setScalingType(), nnp::Mode::setupCutoff(), nnp::Mode::setupElements(), nnp::Mode::setupNeuralNetwork(), nnp::Mode::setupNeuralNetworkWeights(), nnp::Mode::setupSymmetryFunctions(), nnp::Training::setupTraining(), and nnp::Structure::writeToFilePoscar().
 {
     vector<string> parts;
     stringstream ss;
     ss.str(input);
     string item;
     while (getline(ss, item, delimiter)) {
         parts.push_back(item);
     }
     return parts;
 }
trim()
std::string nnp::trim (std::string const & line)
Remove leading and trailing whitespaces from string.
Parameters
[in] line Input string.
[in] whitespace All characters identified as whitespace (default: " \t").
Returns
String without leading and trailing whitespaces.
Definition at line 46 of file utility.cpp.
Referenced by nnp::InterfaceLammps::initialize(), and reduce().
 {
     size_t const begin = line.find_first_not_of(whitespace);
     if (begin == string::npos)
     {
         return "";
     }
     size_t const end = line.find_last_not_of(whitespace);
     size_t const range = end - begin + 1;
     return line.substr(begin, range);
 }
reduce()
std::string nnp::reduce (std::string const & line)
Replace multiple whitespaces with fill.
Parameters
[in] line Input string.
[in] whitespace All characters identified as whitespace (default: " \t").
[in] fill Replacement character (default: " ").
Returns
String with fill replacements.
Calls trim() at the beginning.
Definition at line 59 of file utility.cpp.
References trim().
Referenced by nnp::Element::addSymmetryFunction(), nnp::Dataset::getNumStructures(), nnp::InterfaceLammps::initialize(), main(), nnp::Settings::parseLines(), nnp::Structure::readFromFile(), nnp::Structure::readFromLines(), nnp::ElementMap::registerElements(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionAngularNarrow::setParameters(), nnp::SymmetryFunction::setScalingType(), nnp::Mode::setupElements(), nnp::Mode::setupNeuralNetwork(), nnp::Mode::setupNeuralNetworkWeights(), nnp::Mode::setupSymmetryFunctions(), and nnp::Training::setupTraining().
 {
     string result = trim(line, whitespace);
     size_t begin = result.find_first_of(whitespace);
     while (begin != string::npos)
     {
         size_t const end = result.find_first_not_of(whitespace, begin);
         size_t const range = end - begin;
         result.replace(begin, range, fill);
         size_t const newBegin = begin + fill.length();
         begin = result.find_first_of(whitespace, newBegin);
     }
     return result;
 }
pad() [1/2]
string nnp::pad (string const & input, size_t num, char fill, bool right)
Definition at line 78 of file utility.cpp.
Referenced by nnp::SymmetryFunctionRadial::parameterInfo(), nnp::SymmetryFunctionWeightedRadial::parameterInfo(), nnp::SymmetryFunctionWeightedAngular::parameterInfo(), nnp::SymmetryFunctionAngularWide::parameterInfo(), nnp::SymmetryFunctionAngularNarrow::parameterInfo(), and nnp::SymmetryFunction::parameterInfo().
 {
     string result = input;
     if (input.size() >= num) return result;
     string pad(num - input.size(), fill);
     if (right) return result + pad;
     else return pad + result;
 }
strpr()
std::string nnp::strpr (const char * format, ...)
String version of printf function.
Definition at line 89 of file utility.cpp.
References STRPR_MAXBUF.
Referenced by nnp::Training::addTrainingLogEntry(), nnp::Training::calculateError(), nnp::Training::calculateErrorEpoch(), nnp::Training::calculateNeighborLists(), nnp::Mode::calculateSymmetryFunctionGroups(), nnp::Mode::calculateSymmetryFunctions(), nnp::Training::checkSelectionMode(), nnp::Dataset::collectSymmetryFunctionStatistics(), nnp::Dataset::combineFiles(), nnp::Dataset::distributeStructures(), nnp::ElementMap::getElementsString(), nnp::Structure::getEnergyLine(), nnp::SymmetryFunctionStatistics::getExtrapolationWarningLines(), nnp::Atom::getForcesLines(), nnp::SymmetryFunctionRadial::getSettingsLine(), nnp::SymmetryFunctionWeightedRadial::getSettingsLine(), nnp::SymmetryFunctionAngularWide::getSettingsLine(), nnp::SymmetryFunctionWeightedAngular::getSettingsLine(), nnp::SymmetryFunctionAngularNarrow::getSettingsLine(), nnp::Atom::Neighbor::info(), nnp::ElementMap::info(), nnp::GradientDescent::info(), nnp::KalmanFilter::info(), nnp::Atom::info(), nnp::Structure::info(), nnp::NeuralNetwork::info(), nnp::InterfaceLammps::initialize(), nnp::Mode::initialize(), nnp::Training::initializeWeights(), nnp::Training::initializeWeightsMemory(), nnp::Training::loop(), main(), nnp::SymmetryFunctionRadial::parameterInfo(), nnp::SymmetryFunctionWeightedRadial::parameterInfo(), nnp::SymmetryFunctionAngularWide::parameterInfo(), nnp::SymmetryFunctionWeightedAngular::parameterInfo(), nnp::SymmetryFunctionAngularNarrow::parameterInfo(), nnp::SymmetryFunction::parameterInfo(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), nnp::SymmetryFunctionGroupWeightedRadial::parameterLines(), nnp::SymmetryFunctionGroupRadial::parameterLines(), nnp::SymmetryFunctionGroupAngularWide::parameterLines(), nnp::SymmetryFunctionGroupWeightedAngular::parameterLines(), nnp::SymmetryFunctionGroupAngularNarrow::parameterLines(), nnp::Settings::parseLines(), nnp::Settings::readFile(), runTest(), nnp::Settings::sanityCheck(), nnp::SymmetryFunction::scalingLine(), nnp::Training::selectSets(), nnp::Element::setScalingNone(), nnp::Mode::setupCutoff(), nnp::Mode::setupElementMap(), nnp::Mode::setupElements(), nnp::Dataset::setupMPI(), nnp::Mode::setupNeuralNetwork(), nnp::Mode::setupNeuralNetworkWeights(), nnp::Mode::setupNormalization(), nnp::Dataset::setupRandomNumberGenerator(), nnp::Mode::setupSymmetryFunctionGroups(), nnp::Mode::setupSymmetryFunctionMemory(), nnp::Mode::setupSymmetryFunctions(), nnp::Mode::setupSymmetryFunctionScaling(), nnp::Mode::setupSymmetryFunctionStatistics(), nnp::Training::setupTraining(), nnp::GradientDescent::status(), nnp::KalmanFilter::status(), nnp::ElementMap::symbolFromAtomicNumber(), nnp::Element::updateSymmetryFunctionStatistics(), nnp::Dataset::writeAtomicEnvironmentFile(), nnp::NeuralNetwork::writeConnections(), nnp::Training::writeLearningCurve(), nnp::Dataset::writeNeighborHistogram(), nnp::Dataset::writeNeighborLists(), nnp::Training::writeNeuronStatistics(), nnp::Training::writeNeuronStatisticsEpoch(), nnp::Training::writeSetsToFiles(), nnp::Dataset::writeSymmetryFunctionFile(), nnp::Dataset::writeSymmetryFunctionHistograms(), nnp::Dataset::writeSymmetryFunctionScaling(), nnp::SetupAnalysis::writeSymmetryFunctionShape(), nnp::Structure::writeToFile(), nnp::Structure::writeToFilePoscar(), nnp::Structure::writeToFileXyz(), nnp::Training::writeUpdaterStatus(), nnp::Training::writeWeights(), and nnp::Training::writeWeightsEpoch().
 {
     char buffer[STRPR_MAXBUF];
     va_list args;
     va_start(args, format);
     vsprintf(buffer, format, args);
     va_end(args);
     string s(buffer);
     return s;
 }
createFileHeader() [1/2]
vector<string> nnp::createFileHeader (vector< string > const & title, vector< size_t > const & colSize, vector< string > const & colName, vector< string > const & colInfo, char const & commentChar)
Definition at line 103 of file utility.cpp.
Referenced by nnp::Training::calculateError(), main(), nnp::Training::setupTraining(), nnp::GradientDescent::statusHeader(), nnp::KalmanFilter::statusHeader(), nnp::NeuralNetwork::writeConnections(), nnp::Training::writeLearningCurve(), nnp::Dataset::writeNeighborHistogram(), nnp::Training::writeNeuronStatistics(), nnp::Dataset::writeSymmetryFunctionHistograms(), nnp::Dataset::writeSymmetryFunctionScaling(), and nnp::SetupAnalysis::writeSymmetryFunctionShape().
 {
     size_t const stdWidth = 80;
     vector<string> h;
     if (!(colSize.size() == colName.size() &&
           colName.size() == colInfo.size()))
     {
         throw runtime_error("ERROR: Could not create file header, column sizes"
                             " are not equal.\n");
     }
     size_t numCols = colSize.size();
     // Separator line definition.
     string sepLine(stdWidth, commentChar);
     sepLine += '\n';
     // Start string.
     string startStr(1, commentChar);
     // Add title lines.
     h.push_back(sepLine);
     for (vector<string>::const_iterator it = title.begin();
          it != title.end(); ++it)
     {
         h.push_back(startStr + ' ' + (*it) + '\n');
     }
     h.push_back(sepLine);
     // Determine maximum width of names.
     size_t widthNames = 0;
     for (vector<string>::const_iterator it = colName.begin();
          it != colName.end(); ++it)
     {
         widthNames = max(widthNames, it->size());
     }
     // Column description section.
     stringstream s;
     s << startStr << ' '
       << left << setw(4) << "Col" << ' '
       << left << setw(widthNames) << "Name" << ' '
       << left << "Description\n";
     h.push_back(s.str());
     h.push_back(sepLine);
     for (size_t i = 0; i < numCols; ++i)
     {
         s.clear();
         s.str(string());
         s << startStr << ' '
           << left << setw(4) << i + 1 << ' '
           << left << setw(widthNames) << colName.at(i) << ' '
           << colInfo.at(i) << '\n';
         h.push_back(s.str());
     }
     // Determine total data width.
     size_t widthData = 0;
     for (vector<size_t>::const_iterator it = colSize.begin();
          it != colSize.end(); ++it)
     {
         widthData += (*it) + 1;
     }
     widthData -= 1;
     if (widthData > stdWidth)
     {
         // Long separator line.
         h.push_back(string(widthData, commentChar) + "\n");
     }
     else
     {
         h.push_back(sepLine);
     }
     // Write column number.
     s.clear();
     s.str(string());
     s << startStr;
     for (size_t i = 0; i < numCols; ++i)
     {
         size_t n = colSize.at(i);
         if (i == 0) n -= 2;
         s << ' ' << right << setw(n) << i + 1;
     }
     s << '\n';
     h.push_back(s.str());
     // Write column name.
     s.clear();
     s.str(string());
     s << startStr;
     for (size_t i = 0; i < numCols; ++i)
     {
         size_t n = colSize.at(i);
         if (i == 0) n -= 2;
         string name = colName.at(i);
         if (name.size() > n)
         {
             name.erase(n, string::npos);
         }
         s << ' ' << right << setw(n) << name;
     }
     s << '\n';
     h.push_back(s.str());
     // Long separator line.
     h.push_back(string(widthData, commentChar) + "\n");
     return h;
 }
appendLinesToFile() [1/2]
void nnp::appendLinesToFile (std::ofstream & file, std::vector< std::string > const lines)
Append multiple lines of strings to open file stream.
Parameters
[in,out] file File stream to append lines to.
[in] lines Vector of strings with line content.
Definition at line 217 of file utility.cpp.
Referenced by nnp::Training::calculateError(), main(), nnp::Training::setupTraining(), nnp::NeuralNetwork::writeConnections(), nnp::Training::writeLearningCurve(), nnp::Dataset::writeNeighborHistogram(), nnp::Training::writeNeuronStatistics(), nnp::Dataset::writeSymmetryFunctionHistograms(), nnp::Dataset::writeSymmetryFunctionScaling(), nnp::SetupAnalysis::writeSymmetryFunctionShape(), and nnp::Training::writeUpdaterStatus().
 {
     for (vector<string>::const_iterator it = lines.begin();
          it != lines.end(); ++it)
     {
         file << (*it);
     }
     return;
 }
appendLinesToFile() [2/2]
void nnp::appendLinesToFile (FILE *const & file, std::vector< std::string > const lines)
Append multiple lines of strings to open file pointer.
Parameters
[in,out] file File pointer.
[in] lines Vector of strings with line content.
Definition at line 228 of file utility.cpp.
 {
     for (vector<string>::const_iterator it = lines.begin();
          it != lines.end(); ++it)
     {
         fprintf(file, "%s", it->c_str());
     }
     return;
 }
pow_int()
double nnp::pow_int (double x, int n)
Integer version of power function, "fast exponentiation algorithm".
Parameters
[in] x Base number.
[in] n Integer exponent.
Returns
x^n
Definition at line 239 of file utility.cpp.
Referenced by nnp::SymmetryFunctionGroupAngularWide::calculate(), nnp::SymmetryFunctionGroupWeightedAngular::calculate(), nnp::SymmetryFunctionGroupAngularNarrow::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), and comparePointerTargets().
 {
     // Need an unsigned integer for bit-shift divison.
     unsigned int m;
     // If negative exponent, take the inverse of x and change sign of n.
     if (n < 0)
     {
         x = 1.0 / x;
         m = -n;
     }
     else m = n;
     // Exponentiation by squaring, "fast exponentiation algorithm"
     double result = 1.0;
     do
     {
         if (m & 1) result *= x;
         // Division by 2.
         m >>= 1;
         x *= x;
     }
     while (m);
     return result;
 }
pad() [2/2]
std::string nnp::pad (std::string const & input, std::size_t num, char fill = ' ', bool right = true)
Pad string to given length with fill character.
Parameters
[in] input Input string.
[in] num Desired width of padded string.
[in] fill Padding character.
[in] right If true, pad right. Pad left otherwise.
Returns
String padded to desired length or original string if length of old string is not shorter than desired length.
createFileHeader() [2/2]
std::vector<std::string> nnp::createFileHeader (std::vector< std::string > const & title, std::vector< std::size_t > const & colLength, std::vector< std::string > const & colName, std::vector< std::string > const & colInfo, char const & commentChar = '#')
Generate output file header with info section and column labels.
Parameters
[in] title Multiple lines of title text.
[in] colLength Length of the individual columns.
[in] colName Names of the individual columns.
[in] colInfo Description of the individual columns.
[in] commentChar Character used for starting each line and to create separator lines.
Returns
Vector of strings, one entry per line.
safeFind()
template<typename K , typename V > V const& nnp::safeFind (std::map< K, V > const & stdMap, typename std::map< K, V >::key_type const & key)
Safely access map entry.
Parameters
[in] stdMap Map to search in.
[in] key Key requested.
The .at() member function of maps is available only for C++11.
Definition at line 121 of file utility.h.
Referenced by nnp::SymmetryFunction::getPrintFormat(), nnp::SymmetryFunctionGroup::getPrintFormatCommon(), nnp::SymmetryFunctionGroup::getPrintFormatMember(), nnp::ElementMap::index(), nnp::ElementMap::symbol(), and nnp::Dataset::writeSymmetryFunctionHistograms().
 {
     if (stdMap.find(key) == stdMap.end())
     {
         std::stringstream message;
         message << "ERROR: No map entry found for key \"";
         message << key;
         message << "\".\n";
         throw std::range_error(message.str());
     }
     return stdMap.find(key)->second;
 }
comparePointerTargets()
template<typename T > bool nnp::comparePointerTargets (T * lhs, T * rhs)
Compare pointer targets.
Parameters
[in] lhs Pointer to left side of comparison.
[in] rhs Pointer to right side of comparison.
Returns
True if dereferenced lhs < dereferenced rhs, False otherwise.
Definition at line 144 of file utility.h.
References pow_int().
 {
     return ((*lhs) < (*rhs));
 }
operator+()
Vec3D nnp::operator+ (Vec3D lhs, Vec3D const & rhs) inline
Overload + operator to implement vector addition.
Returns
Sum of two vectors.
Definition at line 292 of file Vec3D.h.
 {
     return lhs += rhs;
 }
operator-() [1/2]
Vec3D nnp::operator- (Vec3D lhs, Vec3D const & rhs) inline
Overload - operator to implement vector subtraction.
Returns
Difference between two vectors.
Definition at line 297 of file Vec3D.h.
 {
     return lhs -= rhs;
 }
operator-() [2/2]
Vec3D nnp::operator- (Vec3D v) inline
Overload - operator to implement vector sign change.
Returns
Negative vector.
Definition at line 302 of file Vec3D.h.
 {
     v *= -1.0;
     return v;
 }
operator*() [1/2]
Vec3D nnp::operator* (Vec3D v, double const a) inline
Overload * operator to implement multiplication with scalar.
Returns
Vector multiplied with scalar.
Definition at line 308 of file Vec3D.h.
 {
     return v *= a;
 }
operator/()
Vec3D nnp::operator/ (Vec3D v, double const a) inline
Overload / operator to implement division by scalar.
Returns
Vector divided by scalar.
Definition at line 313 of file Vec3D.h.
 {
     return v /= a;
 }
operator*() [2/2]
Vec3D nnp::operator* (double const a, Vec3D v) inline
Overload * operator to implement multiplication with scalar (scalar first).
Returns
Vector multiplied with scalar.
Definition at line 318 of file Vec3D.h.
 {
     return v *= a;
 }