n2p2 - A neural network potential package: nnp::CutoffFunction Class Reference
nnp::CutoffFunction Class Reference
#include <CutoffFunction.h>
Public Types
enum CutoffType {
CT_HARD, CT_COS, CT_TANHU, CT_TANH,
CT_EXP, CT_POLY1, CT_POLY2, CT_POLY3,
CT_POLY4
}
List of available cutoff function types.
Public Member Functions
CutoffFunction ()
Constructor, initializes to ´CT_HARD´.
void setCutoffType (CutoffType const cutoffType)
Set cutoff type.
CutoffType getCutoffType () const
Getter for cutoffType.
void setCutoffRadius (double const cutoffRadius)
Set cutoff radius.
double getCutoffRadius () const
Getter for rc.
void setCutoffParameter (double const alpha)
Set parameter for polynomial cutoff function (CT_POLY).
double getCutoffParameter () const
Getter for alpha.
double f (double r) const
Cutoff function .
double df (double r) const
Derivative of cutoff function .
void fdf (double r, double &fc, double &dfc) const
Calculate cutoff function and derivative .
Private Member Functions
double fHARD (double r) const
double dfHARD (double r) const
void fdfHARD (double r, double &fc, double &dfc) const
double fCOS (double r) const
double dfCOS (double r) const
void fdfCOS (double r, double &fc, double &dfc) const
double fTANHU (double r) const
double dfTANHU (double r) const
void fdfTANHU (double r, double &fc, double &dfc) const
double fTANH (double r) const
double dfTANH (double r) const
void fdfTANH (double r, double &fc, double &dfc) const
double fPOLY1 (double r) const
double dfPOLY1 (double r) const
void fdfPOLY1 (double r, double &fc, double &dfc) const
double fPOLY2 (double r) const
double dfPOLY2 (double r) const
void fdfPOLY2 (double r, double &fc, double &dfc) const
double fPOLY3 (double r) const
double dfPOLY3 (double r) const
void fdfPOLY3 (double r, double &fc, double &dfc) const
double fPOLY4 (double r) const
double dfPOLY4 (double r) const
void fdfPOLY4 (double r, double &fc, double &dfc) const
double fEXP (double r) const
double dfEXP (double r) const
void fdfEXP (double r, double &fc, double &dfc) const
Private Attributes
CutoffType cutoffType
Cutoff function type.
double rc
Outer cutoff radius .
double rcinv
Inverse cutoff radius .
double rci
Inner cutoff for cutoff function types which allow shifting.
double alpha
Cutoff function parameter for CT_POLYn and CT_EXP .
double iw
Inverse width of cutoff function .
double(CutoffFunction::* fPtr)(double r) const
Function pointer to f.
double(CutoffFunction::* dfPtr)(double r) const
Function pointer to df.
void(CutoffFunction::* fdfPtr)(double r, double &fc, double &dfc) const
Function pointer to fdf.
Static Private Attributes
static double const PI = 4.0 * atan(1.0)
static double const PI_2 = 2.0 * atan(1.0)
static double const E = exp(1.0)
static double const TANH_PRE = pow((E + 1 / E) / (E - 1 / E), 3)
Detailed Description
Definition at line 23 of file CutoffFunction.h.
Member Enumeration Documentation
CutoffType
enum nnp::CutoffFunction::CutoffType
List of available cutoff function types.
Most cutoff types allow the definition of an inner cutoff . Then the cutoff is equal to up to the inner cutoff:
Enumerator
CT_HARD
CT_COS
CT_TANHU
CT_TANH
CT_EXP
CT_POLY1
CT_POLY2
CT_POLY3
CT_POLY4
Definition at line 40 of file CutoffFunction.h.
     {
         CT_HARD,
         CT_COS,
         CT_TANHU,
         CT_TANH,
         CT_EXP,
         CT_POLY1,
         CT_POLY2,
         CT_POLY3,
         CT_POLY4
     };
Constructor & Destructor Documentation
CutoffFunction()
CutoffFunction::CutoffFunction ()
Constructor, initializes to ´CT_HARD´.
Definition at line 30 of file CutoffFunction.cpp.
                                : cutoffType(CT_HARD                 ),
                                    rc        (0.0                     ),
                                    rcinv     (0.0                     ),
                                    rci       (0.0                     ),
                                    alpha     (0.0                     ),
                                    iw        (0.0                     ),
                                    fPtr      (&CutoffFunction::  fHARD),
                                    dfPtr     (&CutoffFunction:: dfHARD),
                                    fdfPtr    (&CutoffFunction::fdfHARD)
 {
 }
Member Function Documentation
setCutoffType()
void CutoffFunction::setCutoffType (CutoffType const cutoffType)
Set cutoff type.
Parameters
[in] cutoffType Type of cutoff used.
Definition at line 42 of file CutoffFunction.cpp.
References CT_COS, CT_EXP, CT_HARD, CT_POLY1, CT_POLY2, CT_POLY3, CT_POLY4, CT_TANH, CT_TANHU, cutoffType, dfCOS(), dfEXP(), dfHARD(), dfPOLY1(), dfPOLY2(), dfPOLY3(), dfPOLY4(), dfPtr, dfTANH(), dfTANHU(), fCOS(), fdfCOS(), fdfEXP(), fdfHARD(), fdfPOLY1(), fdfPOLY2(), fdfPOLY3(), fdfPOLY4(), fdfPtr, fdfTANH(), fdfTANHU(), fEXP(), fHARD(), fPOLY1(), fPOLY2(), fPOLY3(), fPOLY4(), fPtr, fTANH(), and fTANHU().
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), runTest(), and nnp::SymmetryFunction::setCutoffFunction().
 {
     this->cutoffType = cutoffType;
     if (cutoffType == CT_HARD)
     {
           fPtr = &CutoffFunction::  fHARD;
          dfPtr = &CutoffFunction:: dfHARD;
         fdfPtr = &CutoffFunction::fdfHARD;
     }
     else if (cutoffType == CT_COS)
     {
           fPtr = &CutoffFunction::  fCOS;
          dfPtr = &CutoffFunction:: dfCOS;
         fdfPtr = &CutoffFunction::fdfCOS;
     }
     else if (cutoffType == CT_TANHU)
     {
           fPtr = &CutoffFunction::  fTANHU;
          dfPtr = &CutoffFunction:: dfTANHU;
         fdfPtr = &CutoffFunction::fdfTANHU;
     }
     else if (cutoffType == CT_TANH)
     {
           fPtr = &CutoffFunction::  fTANH;
          dfPtr = &CutoffFunction:: dfTANH;
         fdfPtr = &CutoffFunction::fdfTANH;
     }
     else if (cutoffType == CT_EXP)
     {
           fPtr = &CutoffFunction::  fEXP;
          dfPtr = &CutoffFunction:: dfEXP;
         fdfPtr = &CutoffFunction::fdfEXP;
     }
     else if (cutoffType == CT_POLY1)
     {
           fPtr = &CutoffFunction::  fPOLY1;
          dfPtr = &CutoffFunction:: dfPOLY1;
         fdfPtr = &CutoffFunction::fdfPOLY1;
     }
     else if (cutoffType == CT_POLY2)
     {
           fPtr = &CutoffFunction::  fPOLY2;
          dfPtr = &CutoffFunction:: dfPOLY2;
         fdfPtr = &CutoffFunction::fdfPOLY2;
     }
     else if (cutoffType == CT_POLY3)
     {
           fPtr = &CutoffFunction::  fPOLY3;
          dfPtr = &CutoffFunction:: dfPOLY3;
         fdfPtr = &CutoffFunction::fdfPOLY3;
     }
     else if (cutoffType == CT_POLY4)
     {
           fPtr = &CutoffFunction::  fPOLY4;
          dfPtr = &CutoffFunction:: dfPOLY4;
         fdfPtr = &CutoffFunction::fdfPOLY4;
     }
     else
     {
         throw invalid_argument("ERROR: Unknown cutoff type.\n");
     }
     return;
 }
getCutoffType()
CutoffFunction::CutoffType nnp::CutoffFunction::getCutoffType () const inline
Getter for cutoffType.
Returns
CutoffType used.
Definition at line 195 of file CutoffFunction.h.
References cutoffType.
 {
     return cutoffType;
 }
setCutoffRadius()
void CutoffFunction::setCutoffRadius (double const cutoffRadius)
Set cutoff radius.
Parameters
[in] cutoffRadius Cutoff radius .
Definition at line 108 of file CutoffFunction.cpp.
References rc, and rcinv.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), nnp::SymmetryFunctionWeightedRadial::changeLengthUnit(), nnp::SymmetryFunctionRadial::changeLengthUnit(), nnp::SymmetryFunctionWeightedAngular::changeLengthUnit(), nnp::SymmetryFunctionAngularWide::changeLengthUnit(), nnp::SymmetryFunctionAngularNarrow::changeLengthUnit(), main(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), and nnp::SymmetryFunctionAngularNarrow::setParameters().
 {
     rc = cutoffRadius;
     rcinv = 1.0 / cutoffRadius;
     return;
 }
getCutoffRadius()
double nnp::CutoffFunction::getCutoffRadius () const inline
Getter for rc.
Returns
Cutoff radius used.
Definition at line 200 of file CutoffFunction.h.
References rc.
 {
     return rc;
 }
setCutoffParameter()
void CutoffFunction::setCutoffParameter (double const alpha)
Set parameter for polynomial cutoff function (CT_POLY).
Parameters
[in] alpha Width parameter .
Definition at line 115 of file CutoffFunction.cpp.
References alpha, iw, rc, and rci.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), nnp::SymmetryFunctionWeightedRadial::changeLengthUnit(), nnp::SymmetryFunctionRadial::changeLengthUnit(), nnp::SymmetryFunctionAngularWide::changeLengthUnit(), nnp::SymmetryFunctionWeightedAngular::changeLengthUnit(), nnp::SymmetryFunctionAngularNarrow::changeLengthUnit(), main(), nnp::SymmetryFunction::setCutoffFunction(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), and nnp::SymmetryFunctionAngularNarrow::setParameters().
 {
     if (alpha < 0.0 || alpha >= 1.0)
     {
         throw invalid_argument("ERROR: 0 <= alpha < 1.0 is required.\n");
     }
     this->alpha = alpha;
     rci = rc * alpha;
     iw = 1.0 / (rc - rci);
     return;
 }
getCutoffParameter()
double nnp::CutoffFunction::getCutoffParameter () const inline
Getter for alpha.
Returns
Cutoff parameter used.
Definition at line 205 of file CutoffFunction.h.
References alpha.
 {
     return alpha;
 }
f()
double nnp::CutoffFunction::f (double r) const inline
Cutoff function .
Parameters
[in] r Distance.
Returns
Cutoff function value.
Definition at line 210 of file CutoffFunction.h.
References fPtr, and rc.
Referenced by nnp::SymmetryFunctionWeightedRadial::calculateRadialPart(), nnp::SymmetryFunctionRadial::calculateRadialPart(), nnp::SymmetryFunctionWeightedAngular::calculateRadialPart(), nnp::SymmetryFunctionAngularWide::calculateRadialPart(), nnp::SymmetryFunctionAngularNarrow::calculateRadialPart(), and runTest().
 {
     if (r >= rc) return 0.0;
     return (this->*fPtr)(r);
 }
df()
double nnp::CutoffFunction::df (double r) const inline
Derivative of cutoff function .
Parameters
[in] r Distance.
Returns
Value of cutoff function derivative.
Definition at line 216 of file CutoffFunction.h.
References dfPtr, and rc.
Referenced by runTest().
 {
     if (r >= rc) return 0.0;
     return (this->*dfPtr)(r);
 }
fdf()
void nnp::CutoffFunction::fdf (double r, double & fc, double & dfc) const inline
Calculate cutoff function and derivative .
Parameters
[in] r Distance.
[out] fc Cutoff function value.
[out] dfc Value of cutoff function derivative.
Definition at line 222 of file CutoffFunction.h.
References fdfPtr, and rc.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::calculate(), nnp::SymmetryFunctionGroupRadial::calculate(), nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionGroupAngularWide::calculate(), nnp::SymmetryFunctionGroupWeightedAngular::calculate(), nnp::SymmetryFunctionGroupAngularNarrow::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), and runTest().
 {
     if (r >= rc)
     {
         fc = 0.0;
         dfc = 0.0;
         return;
     }
     (this->*fdfPtr)(r, fc, dfc);
     return;
 }
fHARD()
double nnp::CutoffFunction::fHARD (double r) const inline private
Definition at line 234 of file CutoffFunction.h.
Referenced by setCutoffType().
 {
     return 1.0;
 }
dfHARD()
double nnp::CutoffFunction::dfHARD (double r) const inline private
Definition at line 239 of file CutoffFunction.h.
Referenced by setCutoffType().
 {
     return 0.0;
 }
fdfHARD()
void nnp::CutoffFunction::fdfHARD (double r, double & fc, double & dfc) const inline private
Definition at line 244 of file CutoffFunction.h.
Referenced by setCutoffType().
 {
     fc = 1.0;
     dfc = 0.0;
     return;
 }
fCOS()
double CutoffFunction::fCOS (double r) const private
Definition at line 127 of file CutoffFunction.cpp.
References iw, PI, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 1.0;
     double const x = (r - rci) * iw;
     return 0.5 * (cos(PI * x) + 1.0);
 }
dfCOS()
double CutoffFunction::dfCOS (double r) const private
Definition at line 134 of file CutoffFunction.cpp.
References iw, PI, PI_2, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 0.0;
     double const x = (r - rci) * iw;
     return -PI_2 * iw * sin(PI * x);
 }
fdfCOS()
void CutoffFunction::fdfCOS (double r, double & fc, double & dfc) const private
Definition at line 141 of file CutoffFunction.cpp.
References iw, PI, and rci.
Referenced by setCutoffType().
 {
     if (r < rci)
     {
         fc = 1.0;
         dfc = 0.0;
         return;
     }
     double const x = (r - rci) * iw;
     double const temp = cos(PI * x);
     fc = 0.5 * (temp + 1.0);
     dfc = -0.5 * iw * PI * sqrt(1.0 - temp * temp);
     return;
 }
fTANHU()
double CutoffFunction::fTANHU (double r) const private
Definition at line 156 of file CutoffFunction.cpp.
References rcinv.
Referenced by setCutoffType().
 {
     double const temp = tanh(1.0 - r * rcinv);
     return temp * temp * temp;
 }
dfTANHU()
double CutoffFunction::dfTANHU (double r) const private
Definition at line 162 of file CutoffFunction.cpp.
References rcinv.
Referenced by setCutoffType().
 {
     double temp = tanh(1.0 - r * rcinv);
     temp *= temp;
     return 3.0 * temp * (temp - 1.0) * rcinv;
 }
fdfTANHU()
void CutoffFunction::fdfTANHU (double r, double & fc, double & dfc) const private
Definition at line 169 of file CutoffFunction.cpp.
References rcinv.
Referenced by setCutoffType().
 {
     double const temp = tanh(1.0 - r * rcinv);
     double const temp2 = temp * temp;
     fc = temp * temp2;
     dfc = 3.0 * temp2 * (temp2 - 1.0) * rcinv;
     return;
 }
fTANH()
double CutoffFunction::fTANH (double r) const private
Definition at line 178 of file CutoffFunction.cpp.
References rcinv, and TANH_PRE.
Referenced by setCutoffType().
 {
     double const temp = tanh(1.0 - r * rcinv);
     return TANH_PRE * temp * temp * temp;
 }
dfTANH()
double CutoffFunction::dfTANH (double r) const private
Definition at line 184 of file CutoffFunction.cpp.
References rcinv, and TANH_PRE.
Referenced by setCutoffType().
 {
     double temp = tanh(1.0 - r * rcinv);
     temp *= temp;
     return 3.0 * TANH_PRE * temp * (temp - 1.0) * rcinv;
 }
fdfTANH()
void CutoffFunction::fdfTANH (double r, double & fc, double & dfc) const private
Definition at line 191 of file CutoffFunction.cpp.
References rcinv, and TANH_PRE.
Referenced by setCutoffType().
 {
     double const temp = tanh(1.0 - r * rcinv);
     double const temp2 = temp * temp;
     fc = TANH_PRE * temp * temp2;
     dfc = 3.0 * TANH_PRE * temp2 * (temp2 - 1.0) * rcinv;
     return;
 }
fPOLY1()
double CutoffFunction::fPOLY1 (double r) const private
Definition at line 231 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 1.0;
     double const x = (r - rci) * iw;
     return (2.0 * x - 3.0) * x * x + 1.0;
 }
dfPOLY1()
double CutoffFunction::dfPOLY1 (double r) const private
Definition at line 238 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 0.0;
     double const x = (r - rci) * iw;
     return iw * x * (6.0 * x - 6.0);
 }
fdfPOLY1()
void CutoffFunction::fdfPOLY1 (double r, double & fc, double & dfc) const private
Definition at line 245 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci)
     {
         fc = 1.0;
         dfc = 0.0;
         return;
     }
     double const x = (r - rci) * iw;
     fc = (2.0 * x - 3.0) * x * x + 1.0;
     dfc = iw * x * (6.0 * x - 6.0);
     return;
 }
fPOLY2()
double CutoffFunction::fPOLY2 (double r) const private
Definition at line 259 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 1.0;
     double const x = (r - rci) * iw;
     return ((15.0 - 6.0 * x) * x - 10.0) * x * x * x + 1.0;
 }
dfPOLY2()
double CutoffFunction::dfPOLY2 (double r) const private
Definition at line 266 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 0.0;
     double const x = (r - rci) * iw;
     return iw * x * x * ((60.0 - 30.0 * x) * x - 30.0);
 }
fdfPOLY2()
void CutoffFunction::fdfPOLY2 (double r, double & fc, double & dfc) const private
Definition at line 273 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci)
     {
         fc = 1.0;
         dfc = 0.0;
         return;
     }
     double const x = (r - rci) * iw;
     double const x2 = x * x;
     fc = ((15.0 - 6.0 * x) * x - 10.0) * x * x2 + 1.0;
     dfc = iw * x2 * ((60.0 - 30.0 * x) * x - 30.0);
     return;
 }
fPOLY3()
double CutoffFunction::fPOLY3 (double r) const private
Definition at line 288 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 1.0;
     double const x = (r - rci) * iw;
     double const x2 = x * x;
     return (x * (x * (20.0 * x - 70.0) + 84.0) - 35.0) * x2 * x2 + 1.0;
 }
dfPOLY3()
double CutoffFunction::dfPOLY3 (double r) const private
Definition at line 296 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 0.0;
     double const x = (r - rci) * iw;
     return iw * x * x * x * (x * (x * (140.0 * x - 420.0) + 420.0) - 140.0);
 }
fdfPOLY3()
void CutoffFunction::fdfPOLY3 (double r, double & fc, double & dfc) const private
Definition at line 303 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci)
     {
         fc = 1.0;
         dfc = 0.0;
         return;
     }
     double const x = (r - rci) * iw;
     double const x2 = x * x;
     fc = (x * (x * (20.0 * x - 70.0) + 84.0) - 35.0) * x2 * x2 + 1.0;
     dfc = iw * x2 * x * (x * (x * (140.0 * x - 420.0) + 420.0) - 140.0);
     return;
 }
fPOLY4()
double CutoffFunction::fPOLY4 (double r) const private
Definition at line 318 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 1.0;
     double const x = (r - rci) * iw;
     double const x2 = x * x;
     return (x * (x * ((315.0 - 70.0 * x) * x - 540.0) + 420.0) - 126.0) *
            x2 * x2 * x + 1.0;
 }
dfPOLY4()
double CutoffFunction::dfPOLY4 (double r) const private
Definition at line 327 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 0.0;
     double const x = (r - rci) * iw;
     double const x2 = x * x;
     return iw * x2 * x2 *
            (x * (x * ((2520.0 - 630.0 * x) * x - 3780.0) + 2520.0) - 630.0);
 }
fdfPOLY4()
void CutoffFunction::fdfPOLY4 (double r, double & fc, double & dfc) const private
Definition at line 336 of file CutoffFunction.cpp.
References iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci)
     {
         fc = 1.0;
         dfc = 0.0;
         return;
     }
     double const x = (r - rci) * iw;
     double x4 = x * x;
     x4 *= x4;
     fc = (x * (x * ((315.0 - 70.0 * x) * x - 540.0) + 420.0) - 126.0) *
          x * x4 + 1.0;
     dfc = iw * x4 *
           (x * (x * ((2520.0 - 630.0 * x) * x - 3780.0) + 2520.0) - 630.0);
     return;
 }
fEXP()
double CutoffFunction::fEXP (double r) const private
Definition at line 200 of file CutoffFunction.cpp.
References E, iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 1.0;
     double const x = (r - rci) * iw;
     return E * exp(1.0 / (x * x - 1.0));
 }
dfEXP()
double CutoffFunction::dfEXP (double r) const private
Definition at line 207 of file CutoffFunction.cpp.
References E, iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci) return 0.0;
     double const x = (r - rci) * iw;
     double const temp = 1.0 / (x * x - 1.0);
     return -2.0 * iw * E * x * temp * temp * exp(temp);
 }
fdfEXP()
void CutoffFunction::fdfEXP (double r, double & fc, double & dfc) const private
Definition at line 215 of file CutoffFunction.cpp.
References E, iw, and rci.
Referenced by setCutoffType().
 {
     if (r < rci)
     {
         fc = 1.0;
         dfc = 0.0;
         return;
     }
     double const x = (r - rci) * iw;
     double const temp = 1.0 / (x * x - 1.0);
     double const temp2 = exp(temp);
     fc = E * temp2;
     dfc = -2.0 * iw * E * x * temp * temp * temp2;
     return;
 }
Member Data Documentation
PI
double const CutoffFunction::PI = 4.0 * atan(1.0) static private
Definition at line 127 of file CutoffFunction.h.
Referenced by dfCOS(), fCOS(), and fdfCOS().
PI_2
double const CutoffFunction::PI_2 = 2.0 * atan(1.0) static private
Definition at line 128 of file CutoffFunction.h.
Referenced by dfCOS().
E
double const CutoffFunction::E = exp(1.0) static private
Definition at line 129 of file CutoffFunction.h.
Referenced by dfEXP(), fdfEXP(), and fEXP().
TANH_PRE
double const CutoffFunction::TANH_PRE = pow((E + 1 / E) / (E - 1 / E), 3) static private
Definition at line 130 of file CutoffFunction.h.
Referenced by dfTANH(), fdfTANH(), and fTANH().
cutoffType
CutoffType nnp::CutoffFunction::cutoffType private
Cutoff function type.
Definition at line 133 of file CutoffFunction.h.
Referenced by getCutoffType(), and setCutoffType().
rc
double nnp::CutoffFunction::rc private
Outer cutoff radius .
Definition at line 135 of file CutoffFunction.h.
Referenced by df(), f(), fdf(), getCutoffRadius(), setCutoffParameter(), and setCutoffRadius().
rcinv
double nnp::CutoffFunction::rcinv private
Inverse cutoff radius .
Definition at line 137 of file CutoffFunction.h.
Referenced by dfTANH(), dfTANHU(), fdfTANH(), fdfTANHU(), fTANH(), fTANHU(), and setCutoffRadius().
rci
double nnp::CutoffFunction::rci private
Inner cutoff for cutoff function types which allow shifting.
Definition at line 139 of file CutoffFunction.h.
Referenced by dfCOS(), dfEXP(), dfPOLY1(), dfPOLY2(), dfPOLY3(), dfPOLY4(), fCOS(), fdfCOS(), fdfEXP(), fdfPOLY1(), fdfPOLY2(), fdfPOLY3(), fdfPOLY4(), fEXP(), fPOLY1(), fPOLY2(), fPOLY3(), fPOLY4(), and setCutoffParameter().
alpha
double nnp::CutoffFunction::alpha private
Cutoff function parameter for CT_POLYn and CT_EXP .
Definition at line 141 of file CutoffFunction.h.
Referenced by getCutoffParameter(), and setCutoffParameter().
iw
double nnp::CutoffFunction::iw private
Inverse width of cutoff function .
Definition at line 143 of file CutoffFunction.h.
Referenced by dfCOS(), dfEXP(), dfPOLY1(), dfPOLY2(), dfPOLY3(), dfPOLY4(), fCOS(), fdfCOS(), fdfEXP(), fdfPOLY1(), fdfPOLY2(), fdfPOLY3(), fdfPOLY4(), fEXP(), fPOLY1(), fPOLY2(), fPOLY3(), fPOLY4(), and setCutoffParameter().
fPtr
double(CutoffFunction::* nnp::CutoffFunction::fPtr) (double r) const private
Function pointer to f.
Definition at line 145 of file CutoffFunction.h.
Referenced by f(), and setCutoffType().
dfPtr
double(CutoffFunction::* nnp::CutoffFunction::dfPtr) (double r) const private
Function pointer to df.
Definition at line 147 of file CutoffFunction.h.
Referenced by df(), and setCutoffType().
fdfPtr
void(CutoffFunction::* nnp::CutoffFunction::fdfPtr) (double r, double &fc, double &dfc) const private
Function pointer to fdf.
Definition at line 149 of file CutoffFunction.h.
Referenced by fdf(), and setCutoffType().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/CutoffFunction.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/CutoffFunction.cpp