n2p2 - A neural network potential package: nnp::Element Class Reference
nnp::Element Class Reference
Contains element-specific data.
#include <Element.h>
Public Member Functions
Element (std::size_t const index, ElementMap const &elementMap)
Constructor using index.
~Element ()
Destructor.
void setAtomicEnergyOffset (double atomicEnergyOffset)
Set atomicEnergyOffset.
std::size_t getIndex () const
Get index.
std::size_t getAtomicNumber () const
Get atomicNumber.
double getAtomicEnergyOffset () const
Get atomicEnergyOffset.
std::string getSymbol () const
Get symbol.
void addSymmetryFunction (std::string const &parameters, std::size_t const &lineNumber)
Add one symmetry function.
void changeLengthUnitSymmetryFunctions (double convLength)
Change length unit for all symmetry functions.
void sortSymmetryFunctions ()
Sort all symmetry function.
std::vector< std::string > infoSymmetryFunctionParameters () const
Print symmetry function parameter value information.
std::vector< std::string > infoSymmetryFunction (std::size_t index) const
Print symmetry function parameter names and values.
std::vector< std::string > infoSymmetryFunctionScaling () const
Print symmetry function scaling information.
void setupSymmetryFunctionGroups ()
Set up symmetry function groups.
void setupSymmetryFunctionMemory ()
Extract relevant symmetry function combinations for derivative memory.
std::vector< std::string > infoSymmetryFunctionGroups () const
Print symmetry function group info.
void setCutoffFunction (CutoffFunction::CutoffType const cutoffType, double const cutoffAlpha)
Set cutoff function for all symmetry functions.
void setScalingNone () const
Set no scaling of symmetry function.
void setScaling (SymmetryFunction::ScalingType scalingType, std::vector< std::string > const &statisticsLine, double minS, double maxS) const
Set scaling of all symmetry functions.
std::size_t numSymmetryFunctions () const
Get number of symmetry functions.
std::size_t getMinNeighbors () const
Get maximum of required minimum number of neighbors for all symmetry functions for this element.
double getMinCutoffRadius () const
Get minimum cutoff radius of all symmetry functions.
double getMaxCutoffRadius () const
Get maximum cutoff radius of all symmetry functions.
std::vector< std::size_t > const & getSymmetryFunctionNumTable () const
Get number of relevant symmetry functions per element.
std::vector< std::vector< std::size_t > > const & getSymmetryFunctionTable () const
Get symmetry function element relevance table.
void calculateSymmetryFunctions (Atom &atom, bool const derivatives) const
Calculate symmetry functions.
void calculateSymmetryFunctionGroups (Atom &atom, bool const derivatives) const
Calculate symmetry functions via groups.
std::size_t updateSymmetryFunctionStatistics (Atom const &atom)
Update symmetry function statistics.
SymmetryFunction const & getSymmetryFunction (std::size_t index) const
Get symmetry function instance.
Public Attributes
NeuralNetwork * neuralNetwork
Neural network pointer for this element.
SymmetryFunctionStatistics statistics
Symmetry function statistics.
Private Attributes
ElementMap elementMap
Copy of element map.
std::size_t index
Global index of this element.
std::size_t atomicNumber
Atomic number of this element.
double atomicEnergyOffset
Offset energy for every atom of this element.
std::string symbol
Element symbol.
std::vector< std::size_t > symmetryFunctionNumTable
Number of relevant symmetry functions for each neighbor element.
std::vector< std::vector< std::size_t > > symmetryFunctionTable
List of symmetry function indices relevant for each neighbor element.
std::vector< SymmetryFunction * > symmetryFunctions
Vector of pointers to symmetry functions.
std::vector< SymmetryFunctionGroup * > symmetryFunctionGroups
Vector of pointers to symmetry function groups.
Detailed Description
Contains element-specific data.
Definition at line 36 of file Element.h.
Constructor & Destructor Documentation
Element()
Element::Element (std::size_t const index, ElementMap const & elementMap)
Constructor using index.
Definition at line 42 of file Element.cpp.
                                                                  :
     neuralNetwork     (NULL                          ),
     elementMap        (elementMap                    ),
     index             (index                         ),
     atomicNumber      (elementMap.atomicNumber(index)),
     atomicEnergyOffset(0.0                           ),
     symbol            (elementMap.symbol(index)      )
 {
 }
~Element()
Element::~Element ()
Destructor.
Necessary because of symmetryFunctions vector of pointers.
Definition at line 52 of file Element.cpp.
References neuralNetwork, symmetryFunctionGroups, and symmetryFunctions.
 {
     for (vector<SymmetryFunction*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         delete *it;
     }
     for (vector<SymmetryFunctionGroup*>::const_iterator
          it = symmetryFunctionGroups.begin();
          it != symmetryFunctionGroups.end(); ++it)
     {
         delete *it;
     }
     if (neuralNetwork != NULL)
     {
         delete neuralNetwork;
     }
 }
Member Function Documentation
setAtomicEnergyOffset()
void nnp::Element::setAtomicEnergyOffset (double atomicEnergyOffset) inline
Set atomicEnergyOffset.
Definition at line 223 of file Element.h.
References atomicEnergyOffset.
 {
     this->atomicEnergyOffset = atomicEnergyOffset;
     return;
 }
getIndex()
size_t nnp::Element::getIndex () const inline
Get index.
Definition at line 230 of file Element.h.
References index.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), and nnp::Mode::calculateSymmetryFunctions().
 {
     return index;
 }
getAtomicNumber()
size_t nnp::Element::getAtomicNumber () const inline
Get atomicNumber.
Definition at line 235 of file Element.h.
References atomicNumber.
Referenced by nnp::SetupAnalysis::writeSymmetryFunctionShape().
 {
     return atomicNumber;
 }
getAtomicEnergyOffset()
double nnp::Element::getAtomicEnergyOffset () const inline
Get atomicEnergyOffset.
Definition at line 240 of file Element.h.
References atomicEnergyOffset.
 {
     return atomicEnergyOffset;
 }
getSymbol()
std::string nnp::Element::getSymbol () const inline
Get symbol.
Definition at line 245 of file Element.h.
References symbol.
Referenced by nnp::Mode::setupNeuralNetwork().
 {
     return symbol;
 }
addSymmetryFunction()
void Element::addSymmetryFunction (std::string const & parameters, std::size_t const & lineNumber)
Add one symmetry function.
Parameters
[in] parameters String containing settings for symmetry function.
[in] lineNumber Line number of symmetry function in settings file.
Definition at line 73 of file Element.cpp.
References elementMap, nnp::reduce(), nnp::split(), and symmetryFunctions.
 {
     vector<string> args = split(reduce(parameters));
     size_t         type = (size_t)atoi(args.at(1).c_str());
     if (type == 2)
     {
         symmetryFunctions.push_back(
             new SymmetryFunctionRadial(elementMap));
     }
     else if (type == 3)
     {
         symmetryFunctions.push_back(
             new SymmetryFunctionAngularNarrow(elementMap));
     }
     else if (type == 9)
     {
         symmetryFunctions.push_back(
             new SymmetryFunctionAngularWide(elementMap));
     }
     else if (type == 12)
     {
         symmetryFunctions.push_back(
             new SymmetryFunctionWeightedRadial(elementMap));
     }
     else if (type == 13)
     {
         symmetryFunctions.push_back(
             new SymmetryFunctionWeightedAngular(elementMap));
     }
     else
     {
         throw runtime_error("ERROR: Unknown symmetry function type.\n");
     }
     symmetryFunctions.back()->setParameters(parameters);
     symmetryFunctions.back()->setLineNumber(lineNumber);
     return;
 }
changeLengthUnitSymmetryFunctions()
void Element::changeLengthUnitSymmetryFunctions (double convLength)
Change length unit for all symmetry functions.
Parameters
[in] convLength Length unit conversion factor.
Definition at line 115 of file Element.cpp.
References symmetryFunctions.
 {
     for (vector<SymmetryFunction*>::iterator it = symmetryFunctions.begin();
          it != symmetryFunctions.end(); ++it)
     {
         (*it)->changeLengthUnit(convLength);
     }
     return;
 }
sortSymmetryFunctions()
void Element::sortSymmetryFunctions ()
Sort all symmetry function.
Definition at line 126 of file Element.cpp.
References symmetryFunctions.
 {
     sort(symmetryFunctions.begin(),
          symmetryFunctions.end(),
          comparePointerTargets<SymmetryFunction>);
     for (size_t i = 0; i < symmetryFunctions.size(); ++i)
     {
         symmetryFunctions.at(i)->setIndex(i);
     }
     return;
 }
infoSymmetryFunctionParameters()
vector< string > Element::infoSymmetryFunctionParameters () const
Print symmetry function parameter value information.
Definition at line 140 of file Element.cpp.
References symmetryFunctions.
 {
     vector<string> v;
     for (vector<SymmetryFunction*>::const_iterator
          sf = symmetryFunctions.begin(); sf != symmetryFunctions.end(); ++sf)
     {
         v.push_back((*sf)->parameterLine());
     }
     return v;
 }
infoSymmetryFunction()
std::vector< std::string > nnp::Element::infoSymmetryFunction (std::size_t index) const inline
Print symmetry function parameter names and values.
Definition at line 263 of file Element.h.
References symmetryFunctions.
Referenced by nnp::SetupAnalysis::writeSymmetryFunctionShape().
 {
     return symmetryFunctions.at(index)->parameterInfo();
 }
infoSymmetryFunctionScaling()
vector< string > Element::infoSymmetryFunctionScaling () const
Print symmetry function scaling information.
Definition at line 153 of file Element.cpp.
References symmetryFunctions.
 {
     vector<string> v;
     for (vector<SymmetryFunction*>::const_iterator
          sf = symmetryFunctions.begin(); sf != symmetryFunctions.end(); ++sf)
     {
         v.push_back((*sf)->scalingLine());
     }
     return v;
 }
setupSymmetryFunctionGroups()
void Element::setupSymmetryFunctionGroups ()
Set up symmetry function groups.
Definition at line 166 of file Element.cpp.
References elementMap, symmetryFunctionGroups, and symmetryFunctions.
 {
     for (vector<SymmetryFunction*>::const_iterator
          sf = symmetryFunctions.begin(); sf != symmetryFunctions.end(); ++sf)
     {
         bool createNewGroup = true;
         for (vector<SymmetryFunctionGroup*>::const_iterator
              sfg = symmetryFunctionGroups.begin();
              sfg != symmetryFunctionGroups.end(); ++sfg)
         {
             if ((*sfg)->addMember((*sf)))
             {
                 createNewGroup = false;
                 break;
             }
         }
         if (createNewGroup)
         {
             if ((*sf)->getType() == 2)
             {
                 symmetryFunctionGroups.push_back((SymmetryFunctionGroup*)
                     new SymmetryFunctionGroupRadial(elementMap));
             }
             else if ((*sf)->getType() == 3)
             {
                 symmetryFunctionGroups.push_back((SymmetryFunctionGroup*)
                     new SymmetryFunctionGroupAngularNarrow(elementMap));
             }
             else if ((*sf)->getType() == 9)
             {
                 symmetryFunctionGroups.push_back((SymmetryFunctionGroup*)
                     new SymmetryFunctionGroupAngularWide(elementMap));
             }
             else if ((*sf)->getType() == 12)
             {
                 symmetryFunctionGroups.push_back((SymmetryFunctionGroup*)
                     new SymmetryFunctionGroupWeightedRadial(elementMap));
             }
             else if ((*sf)->getType() == 13)
             {
                 symmetryFunctionGroups.push_back((SymmetryFunctionGroup*)
                     new SymmetryFunctionGroupWeightedAngular(elementMap));
             }
             else
             {
                 throw runtime_error("ERROR: Unknown symmetry function group"
                                     " type.\n");
             }
             symmetryFunctionGroups.back()->addMember(*sf);
         }
     }
     sort(symmetryFunctionGroups.begin(),
          symmetryFunctionGroups.end(),
          comparePointerTargets<SymmetryFunctionGroup>);
     for (size_t i = 0; i < symmetryFunctionGroups.size(); ++i)
     {
         symmetryFunctionGroups.at(i)->sortMembers();
         symmetryFunctionGroups.at(i)->setIndex(i);
     }
     return;
 }
setupSymmetryFunctionMemory()
void Element::setupSymmetryFunctionMemory ()
Extract relevant symmetry function combinations for derivative memory.
Definition at line 231 of file Element.cpp.
References elementMap, nnp::ElementMap::size(), symmetryFunctionNumTable, symmetryFunctions, and symmetryFunctionTable.
 {
     symmetryFunctionTable.clear();
     symmetryFunctionTable.resize(elementMap.size());
     for (auto const& s : symmetryFunctions)
     {
         for (size_t i = 0; i < elementMap.size(); ++i)
         {
             if (s->checkRelevantElement(i))
             {
                 s->setIndexPerElement(i, symmetryFunctionTable.at(i).size());
                 symmetryFunctionTable.at(i).push_back(s->getIndex());
             }
         }
     }
     for (size_t i = 0; i < elementMap.size(); ++i)
     {
         symmetryFunctionNumTable.push_back(symmetryFunctionTable.at(i).size());
     }
     return;
 }
infoSymmetryFunctionGroups()
vector< string > Element::infoSymmetryFunctionGroups () const
Print symmetry function group info.
Definition at line 254 of file Element.cpp.
References symmetryFunctionGroups.
 {
     vector<string> v;
     for (vector<SymmetryFunctionGroup*>::const_iterator
          it = symmetryFunctionGroups.begin();
          it != symmetryFunctionGroups.end(); ++it)
     {
         vector<string> lines = (*it)->parameterLines();
         v.insert(v.end(), lines.begin(), lines.end());
     }
     return v;
 }
setCutoffFunction()
void Element::setCutoffFunction (CutoffFunction::CutoffType const cutoffType, double const cutoffAlpha)
Set cutoff function for all symmetry functions.
Parameters
[in] cutoffType Type of cutoff function.
[in] cutoffAlpha Cutoff parameter for all functions.
Definition at line 269 of file Element.cpp.
References symmetryFunctions.
 {
     for (vector<SymmetryFunction*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         (*it)->setCutoffFunction(cutoffType, cutoffAlpha);
     }
     return;
 }
setScalingNone()
void Element::setScalingNone () const
Set no scaling of symmetry function.
Still scaling factors need to be initialized.
Definition at line 281 of file Element.cpp.
References nnp::SymmetryFunction::ST_NONE, nnp::strpr(), symmetryFunctionGroups, and symmetryFunctions.
 {
     for (size_t i = 0; i < symmetryFunctions.size(); ++i)
     {
         string scalingLine = strpr("%d %d 0.0 0.0 0.0 0.0",
                                    symmetryFunctions.at(i)->getEc(),
                                    i + 1);
         symmetryFunctions.at(i)->setScalingType(SymmetryFunction::ST_NONE,
                                                 scalingLine,
                                                 0.0,
                                                 0.0);
     }
     for (size_t i = 0; i < symmetryFunctionGroups.size(); ++i)
     {
         symmetryFunctionGroups.at(i)->setScalingFactors();
     }
     return;
 }
setScaling()
void Element::setScaling (SymmetryFunction::ScalingType scalingType, std::vector< std::string > const & statisticsLine, double minS, double maxS) const
Set scaling of all symmetry functions.
Parameters
[in] scalingType Type of scaling, see SymmetryFunction::ScalingType.
[in] statisticsLine Vector of strings containing statistics for all symmetry functions.
[in] minS Minimum for scaling range.
[in] maxS Minimum for scaling range.
Definition at line 301 of file Element.cpp.
References symmetryFunctionGroups, and symmetryFunctions.
 {
     for (size_t i = 0; i < symmetryFunctions.size(); ++i)
     {
         symmetryFunctions.at(i)->setScalingType(scalingType,
                                                 statisticsLine.at(i),
                                                 Smin,
                                                 Smax);
     }
     for (size_t i = 0; i < symmetryFunctionGroups.size(); ++i)
     {
         symmetryFunctionGroups.at(i)->setScalingFactors();
     }
     return;
 }
numSymmetryFunctions()
size_t nnp::Element::numSymmetryFunctions () const inline
Get number of symmetry functions.
Returns
Number of symmetry functions.
Definition at line 268 of file Element.h.
References symmetryFunctions.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), nnp::Mode::calculateSymmetryFunctions(), nnp::Mode::setupNeuralNetwork(), and nnp::SetupAnalysis::writeSymmetryFunctionShape().
 {
     return symmetryFunctions.size();
 }
getMinNeighbors()
size_t Element::getMinNeighbors () const
Get maximum of required minimum number of neighbors for all symmetry functions for this element.
Returns
Minimum number of neighbors required.
Definition at line 321 of file Element.cpp.
References symmetryFunctions.
 {
     size_t minNeighbors = 0;
     for (vector<SymmetryFunction*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         minNeighbors = max((*it)->getMinNeighbors(), minNeighbors);
     }
     return minNeighbors;
 }
getMinCutoffRadius()
double Element::getMinCutoffRadius () const
Get minimum cutoff radius of all symmetry functions.
Returns
Minimum cutoff radius.
Definition at line 334 of file Element.cpp.
References symmetryFunctions.
 {
     double minCutoffRadius = numeric_limits<double>::max();
     for (vector<SymmetryFunction*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         minCutoffRadius = min((*it)->getRc(), minCutoffRadius);
     }
     return minCutoffRadius;
 }
getMaxCutoffRadius()
double Element::getMaxCutoffRadius () const
Get maximum cutoff radius of all symmetry functions.
Returns
Maximum cutoff radius.
Definition at line 347 of file Element.cpp.
References symmetryFunctions.
 {
     double maxCutoffRadius = 0.0;
     for (vector<SymmetryFunction*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         maxCutoffRadius = max((*it)->getRc(), maxCutoffRadius);
     }
     return maxCutoffRadius;
 }
getSymmetryFunctionNumTable()
std::vector< std::size_t > const & nnp::Element::getSymmetryFunctionNumTable () const inline
Get number of relevant symmetry functions per element.
Returns
symmetryFunctionNumTable
Definition at line 251 of file Element.h.
References symmetryFunctionNumTable.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), and nnp::Mode::calculateSymmetryFunctions().
 {
     return symmetryFunctionNumTable;
 }
getSymmetryFunctionTable()
std::vector< std::vector< std::size_t > > const & nnp::Element::getSymmetryFunctionTable () const inline
Get symmetry function element relevance table.
Returns
symmetryFunctionTable
Definition at line 257 of file Element.h.
References symmetryFunctionTable.
 {
     return symmetryFunctionTable;
 }
calculateSymmetryFunctions()
void Element::calculateSymmetryFunctions (Atom & atom, bool const derivatives) const
Calculate symmetry functions.
Parameters
[in] atom Atom whose symmetry functions are calculated.
[in] derivatives If symmetry function derivatives will be calculated.
Definition at line 360 of file Element.cpp.
References symmetryFunctions.
Referenced by nnp::Mode::calculateSymmetryFunctions().
 {
     for (vector<SymmetryFunction*>::const_iterator
          it = symmetryFunctions.begin();
          it != symmetryFunctions.end(); ++it)
     {
         (*it)->calculate(atom, derivatives);
     }
     return;
 }
calculateSymmetryFunctionGroups()
void Element::calculateSymmetryFunctionGroups (Atom & atom, bool const derivatives) const
Calculate symmetry functions via groups.
Parameters
[in] atom Atom whose symmetry functions are calculated.
[in] derivatives If symmetry function derivatives will be calculated.
Definition at line 373 of file Element.cpp.
References symmetryFunctionGroups.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups().
 {
     for (vector<SymmetryFunctionGroup*>::const_iterator
          it = symmetryFunctionGroups.begin();
          it != symmetryFunctionGroups.end(); ++it)
     {
         (*it)->calculate(atom, derivatives);
     }
     return;
 }
updateSymmetryFunctionStatistics()
size_t Element::updateSymmetryFunctionStatistics (Atom const & atom)
Update symmetry function statistics.
Parameters
[in] atom Atom with symmetry function values.
Returns
Number of extrapolation warnings encountered.
This function checks also for extrapolation warnings.
Definition at line 386 of file Element.cpp.
References nnp::SymmetryFunctionStatistics::addExtrapolationWarning(), nnp::SymmetryFunctionStatistics::addValue(), nnp::SymmetryFunctionStatistics::collectExtrapolationWarnings, nnp::SymmetryFunctionStatistics::collectStatistics, nnp::Atom::element, nnp::Atom::G, index, nnp::Atom::indexStructure, nnp::Atom::numSymmetryFunctions, statistics, nnp::SymmetryFunctionStatistics::stopOnExtrapolationWarnings, nnp::strpr(), symmetryFunctions, nnp::Atom::tag, and nnp::SymmetryFunctionStatistics::writeExtrapolationWarnings.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), and nnp::Mode::calculateSymmetryFunctions().
 {
     size_t countExtrapolationWarnings = 0;
     double epsilon = 10.0 * numeric_limits<double>::epsilon();
     if (atom.element != index)
     {
         throw runtime_error("ERROR: Atom has a different element index.\n");
     }
     if (atom.numSymmetryFunctions != symmetryFunctions.size())
     {
         throw runtime_error("ERROR: Number of symmetry functions"
                             " does not match.\n");
     }
     for (size_t i = 0; i < atom.G.size(); ++i)
     {
         double const Gmin = symmetryFunctions.at(i)->getGmin();
         double const Gmax = symmetryFunctions.at(i)->getGmax();
         double const value = symmetryFunctions.at(i)->unscale(atom.G.at(i));
         size_t const index = symmetryFunctions.at(i)->getIndex();
         if (statistics.collectStatistics)
         {
             statistics.addValue(index, atom.G.at(i));
         }
         // Avoid "fake" EWs at the boundaries.
         if (value + epsilon < Gmin || value - epsilon > Gmax)
         {
             countExtrapolationWarnings++;
             if (statistics.collectExtrapolationWarnings)
             {
                 statistics.addExtrapolationWarning(index,
                                                    value,
                                                    Gmin,
                                                    Gmax,
                                                    atom.indexStructure,
                                                    atom.tag);
             }
             if (statistics.writeExtrapolationWarnings)
             {
                 cerr << strpr("### NNP EXTRAPOLATION WARNING ### "
                               "STRUCTURE: %6zu ATOM: %6zu SYMFUNC: %4zu "
                               "VALUE: %10.3E MIN: %10.3E MAX: %10.3E\n",
                               atom.indexStructure,
                               atom.tag,
                               index,
                               value,
                               Gmin,
                               Gmax);
             }
             if (statistics.stopOnExtrapolationWarnings)
             {
                 throw out_of_range(
                         strpr("### NNP EXTRAPOLATION WARNING ### "
                               "STRUCTURE: %6zu ATOM: %6zu SYMFUNC: %4zu "
                               "VALUE: %10.3E MIN: %10.3E MAX: %10.3E\n"
                               "ERROR: Symmetry function value out of range.\n",
                               atom.indexStructure,
                               atom.tag,
                               index,
                               value,
                               Gmin,
                               Gmax));
             }
         }
     }
     return countExtrapolationWarnings;
 }
getSymmetryFunction()
SymmetryFunction const & nnp::Element::getSymmetryFunction (std::size_t index) const inline
Get symmetry function instance.
Parameters
[in] index Symmetry function index.
Returns
Symmetry function object.
Definition at line 273 of file Element.h.
References symmetryFunctions.
Referenced by nnp::SetupAnalysis::writeSymmetryFunctionShape().
 {
     return *(symmetryFunctions.at(index));
 }
Member Data Documentation
neuralNetwork
NeuralNetwork* nnp::Element::neuralNetwork
Neural network pointer for this element.
Definition at line 194 of file Element.h.
Referenced by nnp::Mode::calculateAtomicNeuralNetworks(), nnp::Mode::setupNeuralNetwork(), and ~Element().
statistics
SymmetryFunctionStatistics nnp::Element::statistics
Symmetry function statistics.
Definition at line 196 of file Element.h.
Referenced by updateSymmetryFunctionStatistics().
elementMap
ElementMap nnp::Element::elementMap private
Copy of element map.
Definition at line 200 of file Element.h.
Referenced by addSymmetryFunction(), setupSymmetryFunctionGroups(), and setupSymmetryFunctionMemory().
index
std::size_t nnp::Element::index private
Global index of this element.
Definition at line 202 of file Element.h.
Referenced by getIndex(), and updateSymmetryFunctionStatistics().
atomicNumber
std::size_t nnp::Element::atomicNumber private
Atomic number of this element.
Definition at line 204 of file Element.h.
Referenced by getAtomicNumber().
atomicEnergyOffset
double nnp::Element::atomicEnergyOffset private
Offset energy for every atom of this element.
Definition at line 206 of file Element.h.
Referenced by getAtomicEnergyOffset(), and setAtomicEnergyOffset().
symbol
std::string nnp::Element::symbol private
Element symbol.
Definition at line 208 of file Element.h.
Referenced by getSymbol().
symmetryFunctionNumTable
std::vector<std::size_t> nnp::Element::symmetryFunctionNumTable private
Number of relevant symmetry functions for each neighbor element.
Definition at line 210 of file Element.h.
Referenced by getSymmetryFunctionNumTable(), and setupSymmetryFunctionMemory().
symmetryFunctionTable
std::vector<std::vector<std::size_t> > nnp::Element::symmetryFunctionTable private
List of symmetry function indices relevant for each neighbor element.
Definition at line 212 of file Element.h.
Referenced by getSymmetryFunctionTable(), and setupSymmetryFunctionMemory().
symmetryFunctions
std::vector<SymmetryFunction*> nnp::Element::symmetryFunctions private
Vector of pointers to symmetry functions.
Definition at line 214 of file Element.h.
Referenced by addSymmetryFunction(), calculateSymmetryFunctions(), changeLengthUnitSymmetryFunctions(), getMaxCutoffRadius(), getMinCutoffRadius(), getMinNeighbors(), getSymmetryFunction(), infoSymmetryFunction(), infoSymmetryFunctionParameters(), infoSymmetryFunctionScaling(), numSymmetryFunctions(), setCutoffFunction(), setScaling(), setScalingNone(), setupSymmetryFunctionGroups(), setupSymmetryFunctionMemory(), sortSymmetryFunctions(), updateSymmetryFunctionStatistics(), and ~Element().
symmetryFunctionGroups
std::vector<SymmetryFunctionGroup*> nnp::Element::symmetryFunctionGroups private
Vector of pointers to symmetry function groups.
Definition at line 216 of file Element.h.
Referenced by calculateSymmetryFunctionGroups(), infoSymmetryFunctionGroups(), setScaling(), setScalingNone(), setupSymmetryFunctionGroups(), and ~Element().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/Element.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/Element.cpp