n2p2 - A neural network potential package: nnp::Mode Class Reference
nnp::Mode Class Reference
Base class for all NNP applications.
#include <Mode.h>
Public Member Functions
Mode ()
void initialize ()
Write welcome message with version information.
void loadSettingsFile (std::string const &fileName="input.nn")
Open settings file and load all keywords into memory.
void setupGeneric ()
Combine multiple setup routines and provide a basic NNP setup.
void setupNormalization ()
Set up normalization.
void setupElementMap ()
Set up the element map.
void setupElements ()
Set up all Element instances.
void setupCutoff ()
Set up cutoff function for all symmetry functions.
void setupSymmetryFunctions ()
Set up all symmetry functions.
void setupSymmetryFunctionScalingNone ()
Set up "empy" symmetry function scaling.
void setupSymmetryFunctionScaling (std::string const &fileName="scaling.data")
Set up symmetry function scaling from file.
void setupSymmetryFunctionGroups ()
Set up symmetry function groups.
void setupSymmetryFunctionMemory (bool verbose=false)
Extract required memory dimensions for symmetry function derivatives.
void setupSymmetryFunctionStatistics (bool collectStatistics, bool collectExtrapolationWarnings, bool writeExtrapolationWarnings, bool stopOnExtrapolationWarnings)
Set up symmetry function statistics collection.
void setupNeuralNetwork ()
Set up neural networks for all elements.
void setupNeuralNetworkWeights (std::string const &fileNameFormat="weights.%03zu.data")
Set up neural network weights from files.
void calculateSymmetryFunctions (Structure &structure, bool const derivatives)
Calculate all symmetry functions for all atoms in given structure.
void calculateSymmetryFunctionGroups (Structure &structure, bool const derivatives)
Calculate all symmetry function groups for all atoms in given structure.
void calculateAtomicNeuralNetworks (Structure &structure, bool const derivatives) const
Calculate atomic neural networks for all atoms in given structure.
void calculateEnergy (Structure &structure) const
Calculate potential energy for a given structure.
void calculateForces (Structure &structure) const
Calculate forces for all atoms in given structure.
void addEnergyOffset (Structure &structure, bool ref=true)
Add atomic energy offsets to reference energy.
void removeEnergyOffset (Structure &structure, bool ref=true)
Remove atomic energy offsets from reference energy.
double getEnergyOffset (Structure const &structure) const
Get atomic energy offset for given structure.
double getEnergyWithOffset (Structure const &structure, bool ref=true) const
Add atomic energy offsets and return energy.
double normalizedEnergy (double energy) const
Apply normalization to given energy.
double normalizedEnergy (Structure const &structure, bool ref=true) const
Apply normalization to given energy of structure.
double normalizedForce (double force) const
Apply normalization to given force.
double physicalEnergy (double energy) const
Undo normalization for a given energy.
double physicalEnergy (Structure const &structure, bool ref=true) const
Undo normalization for a given energy of structure.
double physicalForce (double force) const
Undo normalization for a given force.
void convertToNormalizedUnits (Structure &structure) const
Convert one structure to normalized units.
void convertToPhysicalUnits (Structure &structure) const
Convert one structure to physical units.
std::size_t getNumExtrapolationWarnings () const
Count total number of extrapolation warnings encountered for all elements and symmetry functions.
void resetExtrapolationWarnings ()
Erase all extrapolation warnings and reset counters.
double getMeanEnergy () const
Getter for Mode::meanEnergy.
double getConvEnergy () const
Getter for Mode::convEnergy.
double getConvLength () const
Getter for Mode::convLength.
double getMaxCutoffRadius () const
Getter for Mode::maxCutoffRadius.
std::size_t getNumElements () const
Getter for Mode::numElements.
std::vector< std::size_t > getNumSymmetryFunctions () const
Get number of symmetry functions per element.
bool useNormalization () const
Check if normalization is enabled.
bool settingsKeywordExists (std::string const &keyword) const
Check if keyword was found in settings file.
std::string settingsGetValue (std::string const &keyword) const
Get value for given keyword in Settings instance.
std::vector< std::size_t > pruneSymmetryFunctionsRange (double threshold)
Prune symmetry functions according to their range and write settings file.
std::vector< std::size_t > pruneSymmetryFunctionsSensitivity (double threshold, std::vector< std::vector< double > > sensitivity)
Prune symmetry functions with sensitivity analysis data.
void writePrunedSettingsFile (std::vector< std::size_t > prune, std::string fileName="output.nn") const
Copy settings file but comment out lines provided.
void writeSettingsFile (std::ofstream *const &file) const
Write complete settings file.
Public Attributes
ElementMap elementMap
Global element map, populated by setupElementMap().
Log log
Global log file.
Protected Attributes
bool normalize
bool checkExtrapolationWarnings
std::size_t numElements
std::vector< std::size_t > minNeighbors
std::vector< double > minCutoffRadius
double maxCutoffRadius
double cutoffAlpha
double meanEnergy
double convEnergy
double convLength
Settings settings
SymmetryFunction::ScalingType scalingType
CutoffFunction::CutoffType cutoffType
std::vector< Element > elements
Detailed Description
Base class for all NNP applications.
This top-level class is the anchor point for existing and future applications. It contains functions to set up an existing neural network potential and calculate energies and forces for configurations given as Structure. A minimal setup requires some consecutive functions calls as this minimal example shows:
Mode mode;
mode.initialize();
mode.loadSettingsFile();
mode.setupElementMap();
mode.setupElements();
mode.setupCutoff();
mode.setupSymmetryFunctions();
mode.setupSymmetryFunctionGroups();
mode.setupSymmetryFunctionStatistics(false, false, true, false);
mode.setupNeuralNetwork();
To load weights and scaling information from files add these lines:
mode.setupSymmetryFunctionScaling();
mode.setupNeuralNetworkWeights();
The NNP is now ready! If we load a structure from a data file:
Structure structure;
ifstream file;
file.open("input.data");
structure.setupElementMap(mode.elementMap);
structure.readFromFile(file);
file.close();
we can finally predict the energy and forces from the neural network potential:
structure.calculateNeighborList(mode.getMaxCutoffRadius());
mode.calculateSymmetryFunctionGroups(structure, true);
mode.calculateAtomicNeuralNetworks(structure, true);
mode.calculateEnergy(structure);
mode.calculateForces(structure);
cout << structure.energy << '\n';
The resulting potential energy is stored in Structure::energy, the forces on individual atoms are located within the Structure::atoms vector in Atom::f.
Definition at line 82 of file Mode.h.
Constructor & Destructor Documentation
Mode()
Mode::Mode ()
Definition at line 33 of file Mode.cpp.
            : normalize                 (false),
                checkExtrapolationWarnings(false),
                numElements               (0    ),
                maxCutoffRadius           (0.0  ),
                cutoffAlpha               (0.0  ),
                meanEnergy                (0.0  ),
                convEnergy                (1.0  ),
                convLength                (1.0  )
 {
 }
Member Function Documentation
initialize()
void Mode::initialize ()
Write welcome message with version information.
Definition at line 44 of file Mode.cpp.
References log, NNP_GIT_BRANCH, NNP_GIT_REV, NNP_GIT_REV_SHORT, NNP_VERSION, and nnp::strpr().
Referenced by nnp::InterfaceLammps::initialize(), main(), and nnp::Prediction::setup().
 {
     log << "\n";
     log << "*****************************************"
            "**************************************\n";
     log << "\n";
     log << "   NNP LIBRARY v" NNP_VERSION "\n";
     log << "   ------------------\n";
     log << "\n";
     log << "Git branch  : " NNP_GIT_BRANCH "\n";
     log << "Git revision: " NNP_GIT_REV_SHORT " (" NNP_GIT_REV ")\n";
     log << "\n";
 #ifdef _OPENMP
     log << strpr("Number of OpenMP threads: %d", omp_get_max_threads());
     log << "\n";
 #endif
     log << "*****************************************"
            "**************************************\n";
     return;
 }
loadSettingsFile()
void Mode::loadSettingsFile (std::string const & fileName = "input.nn")
Open settings file and load all keywords into memory.
Parameters
[in] fileName Settings file name.
Definition at line 67 of file Mode.cpp.
References nnp::Settings::info(), nnp::Settings::loadFile(), log, and settings.
Referenced by nnp::InterfaceLammps::initialize(), main(), and nnp::Prediction::setup().
 {
     log << "\n";
     log << "*** SETUP: SETTINGS FILE ****************"
            "**************************************\n";
     log << "\n";
     settings.loadFile(fileName);
     log << settings.info();
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupGeneric()
void Mode::setupGeneric ()
Combine multiple setup routines and provide a basic NNP setup.
Sets up elements, symmetry functions, symmetry function groups, neural networks. No symmetry function scaling data is read, no weights are set.
Definition at line 83 of file Mode.cpp.
References setupCutoff(), setupElementMap(), setupElements(), setupNeuralNetwork(), setupNormalization(), setupSymmetryFunctionGroups(), setupSymmetryFunctionMemory(), and setupSymmetryFunctions().
Referenced by nnp::InterfaceLammps::initialize(), main(), and nnp::Prediction::setup().
 {
     setupNormalization();
     setupElementMap();
     setupElements();
     setupCutoff();
     setupSymmetryFunctions();
 #ifdef IMPROVED_SFD_MEMORY
     setupSymmetryFunctionMemory(false);
 #endif
 #ifndef NOSFGROUPS
     setupSymmetryFunctionGroups();
 #endif
     setupNeuralNetwork();
     return;
 }
setupNormalization()
void Mode::setupNormalization ()
Set up normalization.
If the keywords mean_energy, conv_length and conv_length are present, the provided conversion factors are used to internally use a different unit system.
Definition at line 101 of file Mode.cpp.
References convEnergy, convLength, nnp::Settings::keywordExists(), log, meanEnergy, normalize, settings, and nnp::strpr().
Referenced by setupGeneric().
 {
     log << "\n";
     log << "*** SETUP: NORMALIZATION ****************"
            "**************************************\n";
     log << "\n";
     if (settings.keywordExists("mean_energy") &&
         settings.keywordExists("conv_energy") &&
         settings.keywordExists("conv_length"))
     {
         normalize = true;
         meanEnergy = atof(settings["mean_energy"].c_str());
         convEnergy = atof(settings["conv_energy"].c_str());
         convLength = atof(settings["conv_length"].c_str());
         log << "Data set normalization is used.\n";
         log << strpr("Mean energy per atom     : %24.16E\n", meanEnergy);
         log << strpr("Conversion factor energy : %24.16E\n", convEnergy);
         log << strpr("Conversion factor length : %24.16E\n", convLength);
         if (settings.keywordExists("atom_energy"))
         {
             log << "\n";
             log << "Atomic energy offsets are used in addition to"
                    " data set normalization.\n";
             log << "Offsets will be subtracted from reference energies BEFORE"
                    " normalization is applied.\n";
         }
     }
     else if ((!settings.keywordExists("mean_energy")) &&
              (!settings.keywordExists("conv_energy")) &&
              (!settings.keywordExists("conv_length")))
     {
         normalize = false;
         log << "Data set normalization is not used.\n";
     }
     else
     {
         throw runtime_error("ERROR: Incorrect usage of normalization"
                             " keywords.\n"
                             "       Use all or none of \"mean_energy\", "
                             "\"conv_energy\" and \"conv_length\".\n");
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupElementMap()
void Mode::setupElementMap ()
Set up the element map.
Uses keyword elements. This function should follow immediately after settings are loaded via loadSettingsFile().
Definition at line 150 of file Mode.cpp.
References nnp::ElementMap::atomicNumber(), elementMap, log, nnp::ElementMap::registerElements(), settings, nnp::ElementMap::size(), and nnp::strpr().
Referenced by main(), and setupGeneric().
 {
     log << "\n";
     log << "*** SETUP: ELEMENT MAP ******************"
            "**************************************\n";
     log << "\n";
     elementMap.registerElements(settings["elements"]);
     log << strpr("Number of element strings found: %d\n", elementMap.size());
     for (size_t i = 0; i < elementMap.size(); ++i)
     {
         log << strpr("Element %2zu: %2s (%3zu)\n", i, elementMap[i].c_str(),
                      elementMap.atomicNumber(i));
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupElements()
void Mode::setupElements ()
Set up all Element instances.
Uses keywords number_of_elements and atom_energy. This function should follow immediately after setupElementMap().
Definition at line 171 of file Mode.cpp.
References elementMap, elements, nnp::Settings::getValues(), nnp::Settings::keywordExists(), log, numElements, nnp::reduce(), settings, nnp::ElementMap::size(), nnp::split(), and nnp::strpr().
Referenced by main(), and setupGeneric().
 {
     log << "\n";
     log << "*** SETUP: ELEMENTS *********************"
            "**************************************\n";
     log << "\n";
     numElements = (size_t)atoi(settings["number_of_elements"].c_str());
     if (numElements != elementMap.size())
     {
         throw runtime_error("ERROR: Inconsistent number of elements.\n");
     }
     log << strpr("Number of elements is consistent: %zu\n", numElements);
     for (size_t i = 0; i < numElements; ++i)
     {
         elements.push_back(Element(i, elementMap));
     }
     if (settings.keywordExists("atom_energy"))
     {
         Settings::KeyRange r = settings.getValues("atom_energy");
         for (Settings::KeyMap::const_iterator it = r.first;
              it != r.second; ++it)
         {
             vector<string> args    = split(reduce(it->second.first));
             size_t         element = elementMap[args.at(0)];
             elements.at(element).
                 setAtomicEnergyOffset(atof(args.at(1).c_str()));
         }
     }
     log << "Atomic energy offsets per element:\n";
     for (size_t i = 0; i < elementMap.size(); ++i)
     {
         log << strpr("Element %2zu: %16.8E\n",
                      i, elements.at(i).getAtomicEnergyOffset());
     }
     log << "Energy offsets are automatically subtracted from reference "
            "energies.\n";
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupCutoff()
void Mode::setupCutoff ()
Set up cutoff function for all symmetry functions.
Uses keyword cutoff_type. Cutoff parameters are read from settings keywords and stored internally. As soon as setupSymmetryFunctions() is called the settings are restored and used for all symmetry functions. Thus, this function must be called before setupSymmetryFunctions().
Definition at line 217 of file Mode.cpp.
References nnp::CutoffFunction::CT_COS, nnp::CutoffFunction::CT_EXP, nnp::CutoffFunction::CT_HARD, nnp::CutoffFunction::CT_POLY1, nnp::CutoffFunction::CT_POLY2, nnp::CutoffFunction::CT_POLY3, nnp::CutoffFunction::CT_POLY4, nnp::CutoffFunction::CT_TANH, nnp::CutoffFunction::CT_TANHU, cutoffAlpha, cutoffType, log, settings, nnp::split(), and nnp::strpr().
Referenced by main(), and setupGeneric().
 {
     log << "\n";
     log << "*** SETUP: CUTOFF FUNCTIONS *************"
            "**************************************\n";
     log << "\n";
     vector<string> args = split(settings["cutoff_type"]);
     cutoffType = (CutoffFunction::CutoffType) atoi(args.at(0).c_str());
     if (args.size() > 1)
     {
         cutoffAlpha = atof(args.at(1).c_str());
         if (0.0 < cutoffAlpha && cutoffAlpha >= 1.0)
         {
             throw invalid_argument("ERROR: 0 <= alpha < 1.0 is required.\n");
         }
     }
     log << strpr("Parameter alpha for inner cutoff: %f\n", cutoffAlpha);
     log << "Inner cutoff = Symmetry function cutoff * alpha\n";
     log << "Equal cutoff function type for all symmetry functions:\n";
     if (cutoffType == CutoffFunction::CT_COS)
     {
         log << strpr("CutoffFunction::CT_COS (%d)\n", cutoffType);
         log << "x := (r - rc * alpha) / (rc - rc * alpha)\n";
         log << "f(x) = 1/2 * (cos(pi*x) + 1)\n";
     }
     else if (cutoffType == CutoffFunction::CT_TANHU)
     {
         log << strpr("CutoffFunction::CT_TANHU (%d)\n", cutoffType);
         log << "f(r) = tanh^3(1 - r/rc)\n";
         if (cutoffAlpha > 0.0)
         {
             log << "WARNING: Inner cutoff parameter not used in combination"
                    " with this cutoff function.\n";
         }
     }
     else if (cutoffType == CutoffFunction::CT_TANH)
     {
         log << strpr("CutoffFunction::CT_TANH (%d)\n", cutoffType);
         log << "f(r) = c * tanh^3(1 - r/rc), f(0) = 1\n";
         if (cutoffAlpha > 0.0)
         {
             log << "WARNING: Inner cutoff parameter not used in combination"
                    " with this cutoff function.\n";
         }
     }
     else if (cutoffType == CutoffFunction::CT_POLY1)
     {
         log << strpr("CutoffFunction::CT_POLY1 (%d)\n", cutoffType);
         log << "x := (r - rc * alpha) / (rc - rc * alpha)\n";
         log << "f(x) = (2x - 3)x^2 + 1\n";
     }
     else if (cutoffType == CutoffFunction::CT_POLY2)
     {
         log << strpr("CutoffFunction::CT_POLY2 (%d)\n", cutoffType);
         log << "x := (r - rc * alpha) / (rc - rc * alpha)\n";
         log << "f(x) = ((15 - 6x)x - 10)x^3 + 1\n";
     }
     else if (cutoffType == CutoffFunction::CT_POLY3)
     {
         log << strpr("CutoffFunction::CT_POLY3 (%d)\n", cutoffType);
         log << "x := (r - rc * alpha) / (rc - rc * alpha)\n";
         log << "f(x) = (x(x(20x - 70) + 84) - 35)x^4 + 1\n";
     }
     else if (cutoffType == CutoffFunction::CT_POLY4)
     {
         log << strpr("CutoffFunction::CT_POLY4 (%d)\n", cutoffType);
         log << "x := (r - rc * alpha) / (rc - rc * alpha)\n";
         log << "f(x) = (x(x((315 - 70x)x - 540) + 420) - 126)x^5 + 1\n";
     }
     else if (cutoffType == CutoffFunction::CT_EXP)
     {
         log << strpr("CutoffFunction::CT_EXP (%d)\n", cutoffType);
         log << "x := (r - rc * alpha) / (rc - rc * alpha)\n";
         log << "f(x) = exp(-1 / 1 - x^2)\n";
     }
     else if (cutoffType == CutoffFunction::CT_HARD)
     {
         log << strpr("CutoffFunction::CT_HARD (%d)\n", cutoffType);
         log << "f(r) = 1\n";
         log << "WARNING: Hard cutoff used!\n";
     }
     else
     {
         throw invalid_argument("ERROR: Unknown cutoff type.\n");
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupSymmetryFunctions()
void Mode::setupSymmetryFunctions ()
Set up all symmetry functions.
Uses keyword symfunction_short. Reads all symmetry functions from settings and automatically assigns them to the correct element.
Definition at line 312 of file Mode.cpp.
References convLength, cutoffAlpha, cutoffType, elementMap, elements, nnp::Settings::getValues(), log, maxCutoffRadius, minCutoffRadius, minNeighbors, normalize, numElements, nnp::reduce(), settings, nnp::split(), and nnp::strpr().
Referenced by main(), and setupGeneric().
 {
     log << "\n";
     log << "*** SETUP: SYMMETRY FUNCTIONS ***********"
            "**************************************\n";
     log << "\n";
     Settings::KeyRange r = settings.getValues("symfunction_short");
     for (Settings::KeyMap::const_iterator it = r.first; it != r.second; ++it)
     {
         vector<string> args    = split(reduce(it->second.first));
         size_t         element = elementMap[args.at(0)];
         elements.at(element).addSymmetryFunction(it->second.first,
                                                  it->second.second);
     }
     log << "Abbreviations:\n";
     log << "--------------\n";
     log << "ind .... Symmetry function index.\n";
     log << "ec ..... Central atom element.\n";
     log << "ty ..... Symmetry function type.\n";
     log << "e1 ..... Neighbor 1 element.\n";
     log << "e2 ..... Neighbor 2 element.\n";
     log << "eta .... Gaussian width eta.\n";
     log << "rs ..... Shift distance of Gaussian.\n";
     log << "la ..... Angle prefactor lambda.\n";
     log << "zeta ... Angle term exponent zeta.\n";
     log << "rc ..... Cutoff radius.\n";
     log << "ct ..... Cutoff type.\n";
     log << "ca ..... Cutoff alpha.\n";
     log << "ln ..... Line number in settings file.\n";
     log << "\n";
     maxCutoffRadius = 0.0;
     for (vector<Element>::iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         if (normalize) it->changeLengthUnitSymmetryFunctions(convLength);
         it->sortSymmetryFunctions();
         maxCutoffRadius = max(it->getMaxCutoffRadius(), maxCutoffRadius);
         it->setCutoffFunction(cutoffType, cutoffAlpha);
         log << strpr("Short range atomic symmetry functions element %2s :\n",
                      it->getSymbol().c_str());
         log << "-----------------------------------------"
                "--------------------------------------\n";
         log << " ind ec ty e1 e2       eta        rs la "
                "zeta        rc ct   ca    ln\n";
         log << "-----------------------------------------"
                "--------------------------------------\n";
         log << it->infoSymmetryFunctionParameters();
         log << "-----------------------------------------"
                "--------------------------------------\n";
     }
     minNeighbors.resize(numElements, 0);
     minCutoffRadius.resize(numElements, maxCutoffRadius);
     for (size_t i = 0; i < numElements; ++i)
     {
         minNeighbors.at(i) = elements.at(i).getMinNeighbors();
         minCutoffRadius.at(i) = elements.at(i).getMinCutoffRadius();
         log << strpr("Minimum cutoff radius for element %2s: %f\n",
                      elements.at(i).getSymbol().c_str(),
                      minCutoffRadius.at(i) / convLength);
     }
     log << strpr("Maximum cutoff radius (global)      : %f\n",
                  maxCutoffRadius / convLength);
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupSymmetryFunctionScalingNone()
void Mode::setupSymmetryFunctionScalingNone ()
Set up "empy" symmetry function scaling.
Does not use any keywords. Sets no scaling for all symmetry functions. Call after setupSymmetryFunctions(). Alternatively set scaling via setupSymmetryFunctionScaling().
Definition at line 384 of file Mode.cpp.
References elements, and log.
Referenced by main().
 {
     log << "\n";
     log << "*** SETUP: SYMMETRY FUNCTION SCALING ****"
            "**************************************\n";
     log << "\n";
     log << "No scaling for symmetry functions.\n";
     for (vector<Element>::iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         it->setScalingNone();
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupSymmetryFunctionScaling()
void Mode::setupSymmetryFunctionScaling (std::string const & fileName = "scaling.data")
Set up symmetry function scaling from file.
Parameters
[in] fileName Scaling file name.
Uses keywords scale_symmetry_functions, center_symmetry_functions, scale_symmetry_functions_sigma, scale_min_short and scale_max_short. Reads in scaling information and sets correct scaling behavior for all symmetry functions. Call after setupSymmetryFunctions().
Definition at line 404 of file Mode.cpp.
References elements, nnp::Settings::keywordExists(), log, scalingType, settings, nnp::SymmetryFunction::ST_CENTER, nnp::SymmetryFunction::ST_NONE, nnp::SymmetryFunction::ST_SCALE, nnp::SymmetryFunction::ST_SCALECENTER, nnp::SymmetryFunction::ST_SCALESIGMA, and nnp::strpr().
Referenced by nnp::InterfaceLammps::initialize(), main(), and nnp::Prediction::setup().
 {
     log << "\n";
     log << "*** SETUP: SYMMETRY FUNCTION SCALING ****"
            "**************************************\n";
     log << "\n";
     log << "Equal scaling type for all symmetry functions:\n";
     if (   ( settings.keywordExists("scale_symmetry_functions" ))
         && (!settings.keywordExists("center_symmetry_functions")))
     {
         scalingType = SymmetryFunction::ST_SCALE;
         log << strpr("Scaling type::ST_SCALE (%d)\n", scalingType);
         log << "Gs = Smin + (Smax - Smin) * (G - Gmin) / (Gmax - Gmin)\n";
     }
     else if (   (!settings.keywordExists("scale_symmetry_functions" ))
              && ( settings.keywordExists("center_symmetry_functions")))
     {
         scalingType = SymmetryFunction::ST_CENTER;
         log << strpr("Scaling type::ST_CENTER (%d)\n", scalingType);
         log << "Gs = G - Gmean\n";
     }
     else if (   ( settings.keywordExists("scale_symmetry_functions" ))
              && ( settings.keywordExists("center_symmetry_functions")))
     {
         scalingType = SymmetryFunction::ST_SCALECENTER;
         log << strpr("Scaling type::ST_SCALECENTER (%d)\n", scalingType);
         log << "Gs = Smin + (Smax - Smin) * (G - Gmean) / (Gmax - Gmin)\n";
     }
     else if (settings.keywordExists("scale_symmetry_functions_sigma"))
     {
         scalingType = SymmetryFunction::ST_SCALESIGMA;
         log << strpr("Scaling type::ST_SCALESIGMA (%d)\n", scalingType);
         log << "Gs = Smin + (Smax - Smin) * (G - Gmean) / Gsigma\n";
     }
     else
     {
         scalingType = SymmetryFunction::ST_NONE;
         log << strpr("Scaling type::ST_NONE (%d)\n", scalingType);
         log << "Gs = G\n";
         log << "WARNING: No symmetry function scaling!\n";
     }
     double Smin = 0.0;
     double Smax = 0.0;
     if (scalingType == SymmetryFunction::ST_SCALE ||
         scalingType == SymmetryFunction::ST_SCALECENTER ||
         scalingType == SymmetryFunction::ST_SCALESIGMA)
     {
         if (settings.keywordExists("scale_min_short"))
         {
             Smin = atof(settings["scale_min_short"].c_str());
         }
         else
         {
             log << "WARNING: Keyword \"scale_min_short\" not found.\n";
             log << "         Default value for Smin = 0.0.\n";
             Smin = 0.0;
         }
         if (settings.keywordExists("scale_max_short"))
         {
             Smax = atof(settings["scale_max_short"].c_str());
         }
         else
         {
             log << "WARNING: Keyword \"scale_max_short\" not found.\n";
             log << "         Default value for Smax = 1.0.\n";
             Smax = 1.0;
         }
         log << strpr("Smin = %f\n", Smin);
         log << strpr("Smax = %f\n", Smax);
     }
     log << strpr("Symmetry function scaling statistics from file: %s\n",
                  fileName.c_str());
     log << "-----------------------------------------"
            "--------------------------------------\n";
     ifstream file;
     file.open(fileName.c_str());
     if (!file.is_open())
     {
         throw runtime_error("ERROR: Could not open file: \"" + fileName
                             + "\".\n");
     }
     string line;
     vector<string> lines;
     while (getline(file, line))
     {
         if (line.at(0) != '#') lines.push_back(line);
     }
     file.close();
     log << "\n";
     log << "Abbreviations:\n";
     log << "--------------\n";
     log << "ind ..... Symmetry function index.\n";
     log << "min ..... Minimum symmetry function value.\n";
     log << "max ..... Maximum symmetry function value.\n";
     log << "mean .... Mean symmetry function value.\n";
     log << "sigma ... Standard deviation of symmetry function values.\n";
     log << "sf ...... Scaling factor for derivatives.\n";
     log << "Smin .... Desired minimum scaled symmetry function value.\n";
     log << "Smax .... Desired maximum scaled symmetry function value.\n";
     log << "t ....... Scaling type.\n";
     log << "\n";
     for (vector<Element>::iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         it->setScaling(scalingType, lines, Smin, Smax);
         log << strpr("Scaling data for symmetry functions element %2s :\n",
                      it->getSymbol().c_str());
         log << "-----------------------------------------"
                "--------------------------------------\n";
         log << " ind       min       max      mean     sigma        sf  Smin  Smax t\n";
         log << "-----------------------------------------"
                "--------------------------------------\n";
         log << it->infoSymmetryFunctionScaling();
         log << "-----------------------------------------"
                "--------------------------------------\n";
         lines.erase(lines.begin(), lines.begin() + it->numSymmetryFunctions());
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupSymmetryFunctionGroups()
void Mode::setupSymmetryFunctionGroups ()
Set up symmetry function groups.
Does not use any keywords. Call after setupSymmetryFunctions() and ensure that correct scaling behavior has already been set.
Definition at line 534 of file Mode.cpp.
References elements, log, and nnp::strpr().
Referenced by setupGeneric().
 {
     log << "\n";
     log << "*** SETUP: SYMMETRY FUNCTION GROUPS *****"
            "**************************************\n";
     log << "\n";
     log << "Abbreviations:\n";
     log << "--------------\n";
     log << "ind .... Symmetry function group index.\n";
     log << "ec ..... Central atom element.\n";
     log << "ty ..... Symmetry function type.\n";
     log << "e1 ..... Neighbor 1 element.\n";
     log << "e2 ..... Neighbor 2 element.\n";
     log << "eta .... Gaussian width eta.\n";
     log << "rs ..... Shift distance of Gaussian.\n";
     log << "la ..... Angle prefactor lambda.\n";
     log << "zeta ... Angle term exponent zeta.\n";
     log << "rc ..... Cutoff radius.\n";
     log << "ct ..... Cutoff type.\n";
     log << "ca ..... Cutoff alpha.\n";
     log << "ln ..... Line number in settings file.\n";
     log << "mi ..... Member index.\n";
     log << "sfi .... Symmetry function index.\n";
     log << "e ...... Recalculate exponential term.\n";
     log << "\n";
     for (vector<Element>::iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         it->setupSymmetryFunctionGroups();
         log << strpr("Short range atomic symmetry function groups "
                      "element %2s :\n", it->getSymbol().c_str());
         log << "-----------------------------------------"
                "--------------------------------------\n";
         log << " ind ec ty e1 e2       eta        rs la "
                "zeta        rc ct   ca    ln   mi  sfi e\n";
         log << "-----------------------------------------"
                "--------------------------------------\n";
         log << it->infoSymmetryFunctionGroups();
         log << "-----------------------------------------"
                "--------------------------------------\n";
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupSymmetryFunctionMemory()
void Mode::setupSymmetryFunctionMemory (bool verbose = false)
Extract required memory dimensions for symmetry function derivatives.
Parameters
[in] verbose If true, print all symmetry function lines.
Call after symmetry functions have been set up and sorted.
Definition at line 583 of file Mode.cpp.
References elementMap, elements, nnp::SymmetryFunction::getIndex(), nnp::SymmetryFunction::getIndexPerElement(), log, numElements, nnp::SymmetryFunction::parameterLine(), and nnp::strpr().
Referenced by setupGeneric().
 {
     log << "\n";
     log << "*** SETUP: SYMMETRY FUNCTION MEMORY *****"
            "**************************************\n";
     log << "\n";
     for (auto& e : elements)
     {
         e.setupSymmetryFunctionMemory();
         vector<
         size_t> symmetryFunctionNumTable = e.getSymmetryFunctionNumTable();
         vector<
         vector<size_t>> symmetryFunctionTable = e.getSymmetryFunctionTable();
         log << strpr("Symmetry function derivatives memory table "
                      "for element %2s :\n", e.getSymbol().c_str());
         log << "-----------------------------------------"
                "--------------------------------------\n";
         log << "Relevant symmetry functions for neighbors with element:\n";
         for (size_t i = 0; i < numElements; ++i)
         {
             log << strpr("- %2s: %4zu of %4zu (%5.1f %)\n",
                          elementMap[i].c_str(),
                          symmetryFunctionNumTable.at(i),
                          e.numSymmetryFunctions(),
                          (100.0 * symmetryFunctionNumTable.at(i))
                          / e.numSymmetryFunctions());
             if (verbose)
             {
                 log << "-----------------------------------------"
                        "--------------------------------------\n";
                 for (auto isf : symmetryFunctionTable.at(i))
                 {
                     SymmetryFunction const& sf = e.getSymmetryFunction(isf);
                     log << sf.parameterLine();
                 }
                 log << "-----------------------------------------"
                        "--------------------------------------\n";
             }
         }
         log << "-----------------------------------------"
                "--------------------------------------\n";
     }
     if (verbose)
     {
         for (auto& e : elements)
         {
             log << strpr("%2s - symmetry function per-element index table:\n",
                          e.getSymbol().c_str());
             log << "-----------------------------------------"
                    "--------------------------------------\n";
             log << " ind";
             for (size_t i = 0; i < numElements; ++i)
             {
                 log << strpr(" %4s", elementMap[i].c_str());
             }
             log << "\n";
             log << "-----------------------------------------"
                    "--------------------------------------\n";
             for (size_t i = 0; i < e.numSymmetryFunctions(); ++i)
             {
                 SymmetryFunction const& sf = e.getSymmetryFunction(i);
                 log << strpr("%4zu", sf.getIndex() + 1);
                 vector<size_t> indexPerElement = sf.getIndexPerElement();
                 for (auto ipe : sf.getIndexPerElement())
                 {
                     if (ipe == numeric_limits<size_t>::max())
                     {
                         log << strpr("     ");
                     }
                     else
                     {
                         log << strpr(" %4zu", ipe + 1);
                     }
                 }
                 log << "\n";
             }
             log << "-----------------------------------------"
                    "--------------------------------------\n";
         }
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupSymmetryFunctionStatistics()
void Mode::setupSymmetryFunctionStatistics (bool collectStatistics, bool collectExtrapolationWarnings, bool writeExtrapolationWarnings, bool stopOnExtrapolationWarnings)
Set up symmetry function statistics collection.
Parameters
[in] collectStatistics Whether statistics (min, max, mean, sigma) is collected.
[in] collectExtrapolationWarnings Whether extrapolation warnings are logged.
[in] writeExtrapolationWarnings Write extrapolation warnings immediately when they occur.
[in] stopOnExtrapolationWarnings Throw error immediately when an extrapolation warning occurs.
Does not use any keywords. Calling this setup function is not required, by default no statistics collection is enabled (all arguments false). Call after setupElements().
Definition at line 672 of file Mode.cpp.
References checkExtrapolationWarnings, elements, log, and nnp::strpr().
Referenced by nnp::InterfaceLammps::initialize(), main(), and nnp::Prediction::setup().
 {
     log << "\n";
     log << "*** SETUP: SYMMETRY FUNCTION STATISTICS *"
            "**************************************\n";
     log << "\n";
     log << "Equal symmetry function statistics for all elements.\n";
     log << strpr("Collect min/max/mean/sigma                        : %d\n",
                  (int)collectStatistics);
     log << strpr("Collect extrapolation warnings                    : %d\n",
                  (int)collectExtrapolationWarnings);
     log << strpr("Write extrapolation warnings immediately to stderr: %d\n",
                  (int)writeExtrapolationWarnings);
     log << strpr("Halt on any extrapolation warning                 : %d\n",
                  (int)stopOnExtrapolationWarnings);
     for (vector<Element>::iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         it->statistics.collectStatistics = collectStatistics;
         it->statistics.collectExtrapolationWarnings =
                                                   collectExtrapolationWarnings;
         it->statistics.writeExtrapolationWarnings = writeExtrapolationWarnings;
         it->statistics.stopOnExtrapolationWarnings =
                                                    stopOnExtrapolationWarnings;
     }
     checkExtrapolationWarnings = collectStatistics
                               || collectExtrapolationWarnings
                               || writeExtrapolationWarnings
                               || stopOnExtrapolationWarnings;
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupNeuralNetwork()
void Mode::setupNeuralNetwork ()
Set up neural networks for all elements.
Uses keywords global_hidden_layers_short, global_nodes_short, global_activation_short, normalize_nodes. Call after setupSymmetryFunctions(), only then the number of input layer neurons is known.
Definition at line 712 of file Mode.cpp.
References nnp::NeuralNetwork::AF_COS, nnp::NeuralNetwork::AF_EXP, nnp::NeuralNetwork::AF_GAUSSIAN, nnp::NeuralNetwork::AF_HARMONIC, nnp::NeuralNetwork::AF_IDENTITY, nnp::NeuralNetwork::AF_LOGISTIC, nnp::NeuralNetwork::AF_RELU, nnp::NeuralNetwork::AF_REVLOGISTIC, nnp::NeuralNetwork::AF_SOFTPLUS, nnp::NeuralNetwork::AF_TANH, elementMap, elements, nnp::Element::getSymbol(), nnp::Settings::getValues(), nnp::NeuralNetwork::info(), nnp::Settings::keywordExists(), log, nnp::Element::neuralNetwork, numElements, nnp::Element::numSymmetryFunctions(), nnp::reduce(), nnp::NeuralNetwork::setNormalizeNeurons(), settings, nnp::split(), and nnp::strpr().
Referenced by setupGeneric().
 {
     log << "\n";
     log << "*** SETUP: NEURAL NETWORKS **************"
            "**************************************\n";
     log << "\n";
     struct NeuralNetworkTopology
     {
         int                                       numLayers = 0;
         vector<int>                               numNeuronsPerLayer;
         vector<NeuralNetwork::ActivationFunction> activationFunctionsPerLayer;
     };
     vector<NeuralNetworkTopology> nnt(numElements);
     size_t globalNumHiddenLayers =
         (size_t)atoi(settings["global_hidden_layers_short"].c_str());
     vector<string> globalNumNeuronsPerHiddenLayer =
         split(reduce(settings["global_nodes_short"]));
     vector<string> globalActivationFunctions =
         split(reduce(settings["global_activation_short"]));
     for (size_t i = 0; i < numElements; ++i)
     {
         NeuralNetworkTopology& t = nnt.at(i);
         t.numLayers = 2 + globalNumHiddenLayers;
         t.numNeuronsPerLayer.resize(t.numLayers, 0);
         t.activationFunctionsPerLayer.resize(t.numLayers,
                                              NeuralNetwork::AF_IDENTITY);
         for (int i = 0; i < t.numLayers; i++)
         {
             NeuralNetwork::
             ActivationFunction& a = t.activationFunctionsPerLayer[i];
             if (i == 0)
             {
                 t.numNeuronsPerLayer[i] = 0;
                 a = NeuralNetwork::AF_IDENTITY;
             }
             else if (i == t.numLayers - 1)
             {
                 t.numNeuronsPerLayer[i] = 1;
                 a = NeuralNetwork::AF_IDENTITY;
             }
             else
             {
                 t.numNeuronsPerLayer[i] =
                     atoi(globalNumNeuronsPerHiddenLayer.at(i-1).c_str());
                 if (globalActivationFunctions.at(i-1) == "l")
                 {
                     a = NeuralNetwork::AF_IDENTITY;
                 }
                 else if (globalActivationFunctions.at(i-1) == "t")
                 {
                     a = NeuralNetwork::AF_TANH;
                 }
                 else if (globalActivationFunctions.at(i-1) == "s")
                 {
                     a = NeuralNetwork::AF_LOGISTIC;
                 }
                 else if (globalActivationFunctions.at(i-1) == "p")
                 {
                     a = NeuralNetwork::AF_SOFTPLUS;
                 }
                 else if (globalActivationFunctions.at(i-1) == "r")
                 {
                     a = NeuralNetwork::AF_RELU;
                 }
                 else if (globalActivationFunctions.at(i-1) == "g")
                 {
                     a = NeuralNetwork::AF_GAUSSIAN;
                 }
                 else if (globalActivationFunctions.at(i-1) == "c")
                 {
                     a = NeuralNetwork::AF_COS;
                 }
                 else if (globalActivationFunctions.at(i-1) == "S")
                 {
                     a = NeuralNetwork::AF_REVLOGISTIC;
                 }
                 else if (globalActivationFunctions.at(i-1) == "e")
                 {
                     a = NeuralNetwork::AF_EXP;
                 }
                 else if (globalActivationFunctions.at(i-1) == "h")
                 {
                     a = NeuralNetwork::AF_HARMONIC;
                 }
                 else
                 {
                     throw runtime_error("ERROR: Unknown activation "
                                         "function.\n");
                 }
             }
         }
     }
     if (settings.keywordExists("element_nodes_short"))
     {
         Settings::KeyRange r = settings.getValues("element_nodes_short");
         for (Settings::KeyMap::const_iterator it = r.first;
              it != r.second; ++it)
         {
             vector<string> args = split(reduce(it->second.first));
             size_t e = elementMap[args.at(0)];
             size_t l = atoi(args.at(1).c_str());
             nnt.at(e).numNeuronsPerLayer.at(l) =
                 (size_t)atoi(args.at(2).c_str());
         }
     }
     bool normalizeNeurons = settings.keywordExists("normalize_nodes");
     log << strpr("Normalize neurons (all elements): %d\n",
                  (int)normalizeNeurons);
     log << "-----------------------------------------"
            "--------------------------------------\n";
     for (size_t i = 0; i < numElements; ++i)
     {
         Element& e = elements.at(i);
         NeuralNetworkTopology& t = nnt.at(i);
         t.numNeuronsPerLayer[0] = e.numSymmetryFunctions();
         e.neuralNetwork = new NeuralNetwork(
                                          t.numLayers,
                                          t.numNeuronsPerLayer.data(),
                                          t.activationFunctionsPerLayer.data());
         e.neuralNetwork->setNormalizeNeurons(normalizeNeurons);
         log << strpr("Atomic short range NN for "
                      "element %2s :\n", e.getSymbol().c_str());
         log << e.neuralNetwork->info();
         log << "-----------------------------------------"
                "--------------------------------------\n";
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
setupNeuralNetworkWeights()
void Mode::setupNeuralNetworkWeights (std::string const & fileNameFormat = "weights.%03zu.data")
Set up neural network weights from files.
Parameters
[in] fileNameFormat Format for weights file name. The string must contain one placeholder for the atomic number.
Does not use any keywords. The weight files should contain one weight per line, see NeuralNetwork::setConnections() for the correct order.
Definition at line 855 of file Mode.cpp.
References elements, log, nnp::reduce(), nnp::split(), and nnp::strpr().
Referenced by nnp::InterfaceLammps::initialize(), nnp::Training::initializeWeights(), main(), and nnp::Prediction::setup().
 {
     log << "\n";
     log << "*** SETUP: NEURAL NETWORK WEIGHTS *******"
            "**************************************\n";
     log << "\n";
     log << strpr("Weight file name format: %s\n", fileNameFormat.c_str());
     for (vector<Element>::iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         string fileName = strpr(fileNameFormat.c_str(), it->getAtomicNumber());
         log << strpr("Weight file for element %2s: %s\n",
                      it->getSymbol().c_str(),
                      fileName.c_str());
         ifstream file;
         file.open(fileName.c_str());
         if (!file.is_open())
         {
             throw runtime_error("ERROR: Could not open file: \"" + fileName
                                 + "\".\n");
         }
         string line;
         vector<double> weights;
         while (getline(file, line))
         {
             if (line.at(0) != '#')
             {
                 vector<string> splitLine = split(reduce(line));
                 weights.push_back(atof(splitLine.at(0).c_str()));
             }
         }
         it->neuralNetwork->setConnections(&(weights.front()));
         file.close();
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
calculateSymmetryFunctions()
void Mode::calculateSymmetryFunctions (Structure & structure, bool const derivatives)
Calculate all symmetry functions for all atoms in given structure.
Parameters
[in] structure Input structure.
[in] derivatives If true calculate also derivatives of symmetry functions.
This function should be replaced by calculateSymmetryFunctionGroups() whenever possible. Results are stored in Atom::G. If derivatives are calculated, additional results are stored in Atom::dGdr and Atom::Neighbor::dGdr.
Definition at line 897 of file Mode.cpp.
References nnp::Atom::allocate(), nnp::Structure::atoms, nnp::Element::calculateSymmetryFunctions(), checkExtrapolationWarnings, nnp::Atom::element, elements, nnp::Element::getIndex(), nnp::Atom::getNumNeighbors(), nnp::Element::getSymmetryFunctionNumTable(), nnp::Structure::hasSymmetryFunctionDerivatives, nnp::Atom::hasSymmetryFunctionDerivatives, nnp::Structure::hasSymmetryFunctions, nnp::Atom::hasSymmetryFunctions, nnp::Atom::index, nnp::Atom::indexStructure, log, minCutoffRadius, minNeighbors, nnp::Atom::numSymmetryFunctionDerivatives, nnp::Atom::numSymmetryFunctions, nnp::Element::numSymmetryFunctions(), nnp::strpr(), and nnp::Element::updateSymmetryFunctionStatistics().
Referenced by nnp::Training::calculateError(), nnp::Training::calculateWeightDerivatives(), main(), nnp::Prediction::predict(), nnp::InterfaceLammps::process(), and nnp::Training::update().
 {
     // Skip calculation for whole structure if results are already saved.
     if (structure.hasSymmetryFunctionDerivatives) return;
     if (structure.hasSymmetryFunctions && !derivatives) return;
     Atom* a = NULL;
     Element* e = NULL;
 #ifdef _OPENMP
     #pragma omp parallel for private (a, e)
 #endif
     for (size_t i = 0; i < structure.atoms.size(); ++i)
     {
         // Pointer to atom.
         a = &(structure.atoms.at(i));
         // Skip calculation for individual atom if results are already saved.
         if (a->hasSymmetryFunctionDerivatives) continue;
         if (a->hasSymmetryFunctions && !derivatives) continue;
         // Get element of atom and set number of symmetry functions.
         e = &(elements.at(a->element));
         a->numSymmetryFunctions = e->numSymmetryFunctions();
         if (derivatives)
         {
             a->numSymmetryFunctionDerivatives
                 = e->getSymmetryFunctionNumTable();
         }
 #ifndef NONEIGHCHECK
         // Check if atom has low number of neighbors.
         size_t numNeighbors = a->getNumNeighbors(
                                             minCutoffRadius.at(e->getIndex()));
         if (numNeighbors < minNeighbors.at(e->getIndex()))
         {
             log << strpr("WARNING: Structure %6zu Atom %6zu : %zu "
                          "neighbors.\n",
                          a->indexStructure,
                          a->index,
                          numNeighbors);
         }
 #endif
         // Allocate symmetry function data vectors in atom.
         a->allocate(derivatives);
         // Calculate symmetry functions (and derivatives).
         e->calculateSymmetryFunctions(*a, derivatives);
         // Remember that symmetry functions of this atom have been calculated.
         a->hasSymmetryFunctions = true;
         if (derivatives) a->hasSymmetryFunctionDerivatives = true;
     }
     // If requested, check extrapolation warnings or update statistics.
     // Needed to shift this out of the loop above to make it thread-safe.
     if (checkExtrapolationWarnings)
     {
         for (size_t i = 0; i < structure.atoms.size(); ++i)
         {
             a = &(structure.atoms.at(i));
             e = &(elements.at(a->element));
             e->updateSymmetryFunctionStatistics(*a);
         }
     }
     // Remember that symmetry functions of this structure have been calculated.
     structure.hasSymmetryFunctions = true;
     if (derivatives) structure.hasSymmetryFunctionDerivatives = true;
     return;
 }
calculateSymmetryFunctionGroups()
void Mode::calculateSymmetryFunctionGroups (Structure & structure, bool const derivatives)
Calculate all symmetry function groups for all atoms in given structure.
Parameters
[in] structure Input structure.
[in] derivatives If true calculate also derivatives of symmetry functions.
This function replaces calculateSymmetryFunctions() when symmetry function groups are enabled (faster, default behavior). Results are stored in Atom::G. If derivatives are calculated, additional results are stored in Atom::dGdr and Atom::Neighbor::dGdr.
Definition at line 971 of file Mode.cpp.
References nnp::Atom::allocate(), nnp::Structure::atoms, nnp::Element::calculateSymmetryFunctionGroups(), checkExtrapolationWarnings, nnp::Atom::element, elements, nnp::Element::getIndex(), nnp::Atom::getNumNeighbors(), nnp::Element::getSymmetryFunctionNumTable(), nnp::Structure::hasSymmetryFunctionDerivatives, nnp::Atom::hasSymmetryFunctionDerivatives, nnp::Structure::hasSymmetryFunctions, nnp::Atom::hasSymmetryFunctions, nnp::Atom::index, nnp::Atom::indexStructure, log, minCutoffRadius, minNeighbors, nnp::Atom::numSymmetryFunctionDerivatives, nnp::Atom::numSymmetryFunctions, nnp::Element::numSymmetryFunctions(), nnp::strpr(), and nnp::Element::updateSymmetryFunctionStatistics().
Referenced by nnp::Training::calculateError(), nnp::Training::calculateWeightDerivatives(), main(), nnp::Prediction::predict(), nnp::InterfaceLammps::process(), and nnp::Training::update().
 {
     // Skip calculation for whole structure if results are already saved.
     if (structure.hasSymmetryFunctionDerivatives) return;
     if (structure.hasSymmetryFunctions && !derivatives) return;
     Atom* a = NULL;
     Element* e = NULL;
 #ifdef _OPENMP
     #pragma omp parallel for private (a, e)
 #endif
     for (size_t i = 0; i < structure.atoms.size(); ++i)
     {
         // Pointer to atom.
         a = &(structure.atoms.at(i));
         // Skip calculation for individual atom if results are already saved.
         if (a->hasSymmetryFunctionDerivatives) continue;
         if (a->hasSymmetryFunctions && !derivatives) continue;
         // Get element of atom and set number of symmetry functions.
         e = &(elements.at(a->element));
         a->numSymmetryFunctions = e->numSymmetryFunctions();
         if (derivatives)
         {
             a->numSymmetryFunctionDerivatives
                 = e->getSymmetryFunctionNumTable();
         }
 #ifndef NONEIGHCHECK
         // Check if atom has low number of neighbors.
         size_t numNeighbors = a->getNumNeighbors(
                                             minCutoffRadius.at(e->getIndex()));
         if (numNeighbors < minNeighbors.at(e->getIndex()))
         {
             log << strpr("WARNING: Structure %6zu Atom %6zu : %zu "
                          "neighbors.\n",
                          a->indexStructure,
                          a->index,
                          numNeighbors);
         }
 #endif
         // Allocate symmetry function data vectors in atom.
         a->allocate(derivatives);
         // Calculate symmetry functions (and derivatives).
         e->calculateSymmetryFunctionGroups(*a, derivatives);
         // Remember that symmetry functions of this atom have been calculated.
         a->hasSymmetryFunctions = true;
         if (derivatives) a->hasSymmetryFunctionDerivatives = true;
     }
     // If requested, check extrapolation warnings or update statistics.
     // Needed to shift this out of the loop above to make it thread-safe.
     if (checkExtrapolationWarnings)
     {
         for (size_t i = 0; i < structure.atoms.size(); ++i)
         {
             a = &(structure.atoms.at(i));
             e = &(elements.at(a->element));
             e->updateSymmetryFunctionStatistics(*a);
         }
     }
     // Remember that symmetry functions of this structure have been calculated.
     structure.hasSymmetryFunctions = true;
     if (derivatives) structure.hasSymmetryFunctionDerivatives = true;
     return;
 }
calculateAtomicNeuralNetworks()
void Mode::calculateAtomicNeuralNetworks (Structure & structure, bool const derivatives) const
Calculate atomic neural networks for all atoms in given structure.
Parameters
[in] structure Input structure.
[in] derivatives If true calculate also derivatives of neural networks with respect to input layer neurons (required for force calculation).
The atomic energy is stored in Atom::energy. If derivatives are calculated the results are stored in Atom::dEdG. The atomic energy energy offset (keyword atom_energy) is also added at this point.
Definition at line 1045 of file Mode.cpp.
References nnp::Structure::atoms, nnp::NeuralNetwork::calculateDEdG(), elements, nnp::NeuralNetwork::getOutput(), nnp::Element::neuralNetwork, nnp::NeuralNetwork::propagate(), and nnp::NeuralNetwork::setInput().
Referenced by nnp::Training::calculateError(), main(), nnp::Prediction::predict(), nnp::InterfaceLammps::process(), and nnp::Training::update().
 {
     for (vector<Atom>::iterator it = structure.atoms.begin();
          it != structure.atoms.end(); ++it)
     {
         Element const& e = elements.at(it->element);
         e.neuralNetwork->setInput(&((it->G).front()));
         e.neuralNetwork->propagate();
         if (derivatives) e.neuralNetwork->calculateDEdG(&((it->dEdG).front()));
         e.neuralNetwork->getOutput(&(it->energy));
     }
     return;
 }
calculateEnergy()
void Mode::calculateEnergy (Structure & structure) const
Calculate potential energy for a given structure.
Parameters
[in] structure Input structure.
Sum up potential energy from atomic energy contributions. Result is stored in Structure::energy.
Definition at line 1061 of file Mode.cpp.
References nnp::Structure::atoms, and nnp::Structure::energy.
Referenced by nnp::Training::calculateError(), main(), nnp::Prediction::predict(), nnp::InterfaceLammps::process(), and nnp::Training::update().
 {
     // Loop over all atoms and add atomic contributions to total energy.
     structure.energy = 0.0;
     for (vector<Atom>::iterator it = structure.atoms.begin();
          it != structure.atoms.end(); ++it)
     {
         structure.energy += it->energy;
     }
     return;
 }
calculateForces()
void Mode::calculateForces (Structure & structure) const
Calculate forces for all atoms in given structure.
Parameters
[in] structure Input structure.
Combine intermediate results from symmetry function and neural network computation to atomic forces. Results are stored in Atom::f.
Definition at line 1074 of file Mode.cpp.
References nnp::Structure::atoms, nnp::Atom::dEdG, nnp::Atom::dGdr, nnp::Atom::element, elements, nnp::Atom::f, nnp::Atom::index, nnp::Atom::neighbors, nnp::Atom::neighborsUnique, and nnp::Atom::numSymmetryFunctions.
Referenced by nnp::Training::calculateError(), main(), nnp::Prediction::predict(), and nnp::Training::update().
 {
     Atom* ai = NULL;
     // Loop over all atoms, center atom i (ai).
 #ifdef _OPENMP
     #pragma omp parallel for private(ai)
 #endif
     for (size_t i = 0; i < structure.atoms.size(); ++i)
     {
         // Set pointer to atom.
         ai = &(structure.atoms.at(i));
         // Reset forces.
         ai->f[0] = 0.0;
         ai->f[1] = 0.0;
         ai->f[2] = 0.0;
         // First add force contributions from atom i itself (gradient of
         // atomic energy E_i).
         for (size_t j = 0; j < ai->numSymmetryFunctions; ++j)
         {
             ai->f -= ai->dEdG.at(j) * ai->dGdr.at(j);
         }
         // Now loop over all neighbor atoms j of atom i. These may hold
         // non-zero derivatives of their symmetry functions with respect to
         // atom i's coordinates. Some atoms may appear multiple times in the
         // neighbor list because of periodic boundary conditions. To avoid
         // that the same contributions are added multiple times use the
         // "unique neighbor" list (but skip the first entry, this is always
         // atom i itself).
         for (vector<size_t>::const_iterator it =
              ai->neighborsUnique.begin() + 1;
              it != ai->neighborsUnique.end(); ++it)
         {
             // Define shortcut for atom j (aj).
             Atom& aj = structure.atoms.at(*it);
 #ifdef IMPROVED_SFD_MEMORY
             vector<vector<size_t> > const& tableFull
                 = elements.at(aj.element).getSymmetryFunctionTable();
 #endif
             // Loop over atom j's neighbors (n), atom i should be one of them.
             for (vector<Atom::Neighbor>::const_iterator n =
                  aj.neighbors.begin(); n != aj.neighbors.end(); ++n)
             {
                 // If atom j's neighbor is atom i add force contributions.
                 if (n->index == ai->index)
                 {
 #ifdef IMPROVED_SFD_MEMORY
                     vector<size_t> const& table = tableFull.at(n->element);
                     for (size_t j = 0; j < n->dGdr.size(); ++j)
                     {
                         ai->f -= aj.dEdG.at(table.at(j)) * n->dGdr.at(j);
                     }
 #else
                     for (size_t j = 0; j < aj.numSymmetryFunctions; ++j)
                     {
                         ai->f -= aj.dEdG.at(j) * n->dGdr.at(j);
                     }
 #endif
                 }
             }
         }
     }
     return;
 }
addEnergyOffset()
void Mode::addEnergyOffset (Structure & structure, bool ref = true)
Add atomic energy offsets to reference energy.
Parameters
[in] structure Input structure.
[in] ref If true, use reference energy, otherwise use NN energy.
Definition at line 1142 of file Mode.cpp.
References elements, nnp::Structure::energy, nnp::Structure::energyRef, nnp::Structure::numAtomsPerElement, and numElements.
Referenced by main(), nnp::Prediction::predict(), nnp::InterfaceLammps::process(), and nnp::Training::writeSetsToFiles().
 {
     for (size_t i = 0; i < numElements; ++i)
     {
         if (ref)
         {
             structure.energyRef += structure.numAtomsPerElement.at(i)
                                  * elements.at(i).getAtomicEnergyOffset();
         }
         else
         {
             structure.energy += structure.numAtomsPerElement.at(i)
                               * elements.at(i).getAtomicEnergyOffset();
         }
     }
     return;
 }
removeEnergyOffset()
void Mode::removeEnergyOffset (Structure & structure, bool ref = true)
Remove atomic energy offsets from reference energy.
Parameters
[in] structure Input structure.
[in] ref If true, use reference energy, otherwise use NN energy.
This function should be called immediately after structures are read in.
Definition at line 1161 of file Mode.cpp.
References elements, nnp::Structure::energy, nnp::Structure::energyRef, nnp::Structure::numAtomsPerElement, and numElements.
Referenced by nnp::Dataset::distributeStructures(), nnp::Prediction::readStructureFromFile(), and nnp::Training::writeSetsToFiles().
 {
     for (size_t i = 0; i < numElements; ++i)
     {
         if (ref)
         {
             structure.energyRef -= structure.numAtomsPerElement.at(i)
                                  * elements.at(i).getAtomicEnergyOffset();
         }
         else
         {
             structure.energy -= structure.numAtomsPerElement.at(i)
                               * elements.at(i).getAtomicEnergyOffset();
         }
     }
     return;
 }
getEnergyOffset()
double Mode::getEnergyOffset (Structure const & structure) const
Get atomic energy offset for given structure.
Parameters
[in] structure Input structure.
Returns
Summed atomic energy offsets for structure.
Definition at line 1180 of file Mode.cpp.
References elements, nnp::Structure::numAtomsPerElement, and numElements.
Referenced by main(), and nnp::Dataset::writeSymmetryFunctionFile().
 {
     double result = 0.0;
     for (size_t i = 0; i < numElements; ++i)
     {
         result += structure.numAtomsPerElement.at(i)
                 * elements.at(i).getAtomicEnergyOffset();
     }
     return result;
 }
getEnergyWithOffset()
double Mode::getEnergyWithOffset (Structure const & structure, bool ref = true) const
Add atomic energy offsets and return energy.
Parameters
[in] structure Input structure.
[in] ref If true, use reference energy, otherwise use NN energy.
Returns
Reference or NNP energy with energy offsets added.
Note
If normalization is used, ensure that structure energy is already in physical units.
Definition at line 1193 of file Mode.cpp.
References elements, nnp::Structure::energy, nnp::Structure::energyRef, nnp::Structure::numAtomsPerElement, and numElements.
Referenced by main().
 {
     double result;
     if (ref) result = structure.energyRef;
     else     result = structure.energy;
     for (size_t i = 0; i < numElements; ++i)
     {
         result += structure.numAtomsPerElement.at(i)
                 * elements.at(i).getAtomicEnergyOffset();
     }
     return result;
 }
normalizedEnergy() [1/2]
double Mode::normalizedEnergy (double energy) const
Apply normalization to given energy.
Parameters
[in] energy Input energy in physical units.
Returns
Energy in normalized units.
Definition at line 1208 of file Mode.cpp.
References convEnergy.
 {
     return energy * convEnergy;
 }
normalizedEnergy() [2/2]
double Mode::normalizedEnergy (Structure const & structure, bool ref = true) const
Apply normalization to given energy of structure.
Parameters
[in] structure Input structure with energy in physical units.
[in] ref If true, use reference energy, otherwise use NN energy.
Returns
Energy in normalized units.
Definition at line 1213 of file Mode.cpp.
References convEnergy, nnp::Structure::energy, nnp::Structure::energyRef, meanEnergy, and nnp::Structure::numAtoms.
 {
     if (ref)
     {
         return (structure.energyRef - structure.numAtoms * meanEnergy)
                * convEnergy;
     }
     else
     {
         return (structure.energy - structure.numAtoms * meanEnergy)
                * convEnergy;
     }
 }
normalizedForce()
double Mode::normalizedForce (double force) const
Apply normalization to given force.
Parameters
[in] force Input force in physical units.
Returns
Force in normalized units.
Definition at line 1227 of file Mode.cpp.
References convEnergy, and convLength.
 {
     return force * convEnergy / convLength;
 }
physicalEnergy() [1/2]
double Mode::physicalEnergy (double energy) const
Undo normalization for a given energy.
Parameters
[in] energy Input energy in normalized units.
Returns
Energy in physical units.
Definition at line 1232 of file Mode.cpp.
References convEnergy.
Referenced by nnp::Training::calculateError(), nnp::InterfaceLammps::getAtomicEnergy(), main(), nnp::InterfaceLammps::process(), nnp::Training::writeLearningCurve(), and nnp::Dataset::writeSymmetryFunctionFile().
 {
     return energy / convEnergy;
 }
physicalEnergy() [2/2]
double Mode::physicalEnergy (Structure const & structure, bool ref = true) const
Undo normalization for a given energy of structure.
Parameters
[in] structure Input structure with energy in normalized units.
[in] ref If true, use reference energy, otherwise use NN energy.
Returns
Energy in physical units.
Definition at line 1237 of file Mode.cpp.
References convEnergy, nnp::Structure::energy, nnp::Structure::energyRef, meanEnergy, and nnp::Structure::numAtoms.
 {
     if (ref)
     {
         return structure.energyRef / convEnergy + structure.numAtoms
                * meanEnergy;
     }
     else
     {
         return structure.energy / convEnergy + structure.numAtoms * meanEnergy;
     }
 }
physicalForce()
double Mode::physicalForce (double force) const
Undo normalization for a given force.
Parameters
[in] force Input force in normalized units.
Returns
Force in physical units.
Definition at line 1250 of file Mode.cpp.
References convEnergy, and convLength.
Referenced by nnp::Training::calculateError(), main(), and nnp::Training::writeLearningCurve().
 {
     return force * convLength / convEnergy;
 }
convertToNormalizedUnits()
void Mode::convertToNormalizedUnits (Structure & structure) const
Convert one structure to normalized units.
Parameters
[in,out] structure Input structure.
Definition at line 1255 of file Mode.cpp.
References convEnergy, convLength, meanEnergy, and nnp::Structure::toNormalizedUnits().
 {
     structure.toNormalizedUnits(meanEnergy, convEnergy, convLength);
     return;
 }
convertToPhysicalUnits()
void Mode::convertToPhysicalUnits (Structure & structure) const
Convert one structure to physical units.
Parameters
[in,out] structure Input structure.
Definition at line 1262 of file Mode.cpp.
References convEnergy, convLength, meanEnergy, and nnp::Structure::toPhysicalUnits().
Referenced by main().
 {
     structure.toPhysicalUnits(meanEnergy, convEnergy, convLength);
     return;
 }
getNumExtrapolationWarnings()
size_t Mode::getNumExtrapolationWarnings () const
Count total number of extrapolation warnings encountered for all elements and symmetry functions.
Returns
Number of extrapolation warnings.
Definition at line 1280 of file Mode.cpp.
References elements.
Referenced by LAMMPS_NS::PairNNP::handleExtrapolationWarnings(), and main().
 {
     size_t numExtrapolationWarnings = 0;
     for (vector<Element>::const_iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         numExtrapolationWarnings +=
             it->statistics.countExtrapolationWarnings();
     }
     return numExtrapolationWarnings;
 }
resetExtrapolationWarnings()
void Mode::resetExtrapolationWarnings ()
Erase all extrapolation warnings and reset counters.
Definition at line 1269 of file Mode.cpp.
References elements.
Referenced by main().
 {
     for (vector<Element>::iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         it->statistics.resetExtrapolationWarnings();
     }
     return;
 }
getMeanEnergy()
double nnp::Mode::getMeanEnergy () const inline
Getter for Mode::meanEnergy.
Returns
Mean energy per atom.
Definition at line 487 of file Mode.h.
References meanEnergy.
Referenced by main().
 {
     return meanEnergy;
 }
getConvEnergy()
double nnp::Mode::getConvEnergy () const inline
Getter for Mode::convEnergy.
Returns
Energy unit conversion factor.
Definition at line 492 of file Mode.h.
References convEnergy.
Referenced by main().
 {
     return convEnergy;
 }
getConvLength()
double nnp::Mode::getConvLength () const inline
Getter for Mode::convLength.
Returns
Length unit conversion factor.
Definition at line 497 of file Mode.h.
References convLength.
Referenced by main().
 {
     return convLength;
 }
getMaxCutoffRadius()
double nnp::Mode::getMaxCutoffRadius () const inline
Getter for Mode::maxCutoffRadius.
Returns
Maximum cutoff radius of all symmetry functions.
The maximum cutoff radius is determined by setupSymmetryFunctions().
Definition at line 502 of file Mode.h.
References maxCutoffRadius.
Referenced by main().
 {
     return maxCutoffRadius;
 }
getNumElements()
std::size_t nnp::Mode::getNumElements () const inline
Getter for Mode::numElements.
Returns
Number of elements defined.
The number of elements is determined by setupElements().
Definition at line 507 of file Mode.h.
References numElements.
Referenced by main().
 {
     return numElements;
 }
getNumSymmetryFunctions()
vector< size_t > Mode::getNumSymmetryFunctions () const
Get number of symmetry functions per element.
Returns
Vector with number of symmetry functions for each element.
Definition at line 1294 of file Mode.cpp.
References elements.
Referenced by main().
 {
     vector<size_t> v;
     for (vector<Element>::const_iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         v.push_back(it->numSymmetryFunctions());
     }
     return v;
 }
useNormalization()
bool nnp::Mode::useNormalization () const inline
Check if normalization is enabled.
Returns
Value of normalize.
Definition at line 512 of file Mode.h.
References normalize.
Referenced by main().
 {
     return normalize;
 }
settingsKeywordExists()
bool Mode::settingsKeywordExists (std::string const & keyword) const
Check if keyword was found in settings file.
Parameters
[in] keyword Keyword for which value is requested.
Returns
true if keyword exists, false otherwise.
Definition at line 1307 of file Mode.cpp.
References nnp::Settings::keywordExists(), and settings.
Referenced by main().
 {
     return settings.keywordExists(keyword);
 }
settingsGetValue()
string Mode::settingsGetValue (std::string const & keyword) const
Get value for given keyword in Settings instance.
Parameters
[in] keyword Keyword for which value is requested.
Returns
Value string corresponding to keyword.
Definition at line 1312 of file Mode.cpp.
References nnp::Settings::getValue(), and settings.
 {
     return settings.getValue(keyword);
 }
pruneSymmetryFunctionsRange()
vector< size_t > Mode::pruneSymmetryFunctionsRange (double threshold)
Prune symmetry functions according to their range and write settings file.
Parameters
[in] threshold Symmetry functions with range (max - min) smaller than this threshold will be pruned.
Returns
List of line numbers with symmetry function to be removed.
Definition at line 1342 of file Mode.cpp.
References elements, nnp::SymmetryFunction::getGmax(), and nnp::SymmetryFunction::getGmin().
Referenced by main().
 {
     vector<size_t> prune;
     // Check if symmetry functions have low range.
     for (vector<Element>::const_iterator it = elements.begin();
          it != elements.end(); ++it)
     {
         for (size_t i = 0; i < it->numSymmetryFunctions(); ++i)
         {
             SymmetryFunction const& s = it->getSymmetryFunction(i);
             if (fabs(s.getGmax() - s.getGmin()) < threshold)
             {
                 prune.push_back(it->getSymmetryFunction(i).getLineNumber());
             }
         }
     }
     return prune;
 }
pruneSymmetryFunctionsSensitivity()
vector< size_t > Mode::pruneSymmetryFunctionsSensitivity (double threshold, std::vector< std::vector< double > > sensitivity)
Prune symmetry functions with sensitivity analysis data.
Parameters
[in] threshold Symmetry functions with sensitivity lower than this threshold will be pruned.
[in] sensitivity Sensitivity data for each element and symmetry function.
Returns
List of line numbers with symmetry function to be removed.
Definition at line 1363 of file Mode.cpp.
References elements, and numElements.
Referenced by main().
 {
     vector<size_t> prune;
     for (size_t i = 0; i < numElements; ++i)
     {
         for (size_t j = 0; j < elements.at(i).numSymmetryFunctions(); ++j)
         {
             if (sensitivity.at(i).at(j) < threshold)
             {
                 prune.push_back(
                         elements.at(i).getSymmetryFunction(j).getLineNumber());
             }
         }
     }
     return prune;
 }
writePrunedSettingsFile()
void Mode::writePrunedSettingsFile (std::vector< std::size_t > prune, std::string fileName = "output.nn") const
Copy settings file but comment out lines provided.
Parameters
[in] prune List of line numbers to comment out.
[in] fileName Output file name.
Definition at line 1318 of file Mode.cpp.
References nnp::Settings::getSettingsLines(), and settings.
Referenced by main().
 {
     ofstream file(fileName.c_str());
     vector<string> settingsLines = settings.getSettingsLines();
     for (size_t i = 0; i < settingsLines.size(); ++i)
     {
         if (find(prune.begin(), prune.end(), i) != prune.end())
         {
             file << "# ";
         }
         file << settingsLines.at(i) << '\n';
     }
     file.close();
     return;
 }
writeSettingsFile()
void Mode::writeSettingsFile (std::ofstream *const & file) const
Write complete settings file.
Parameters
[in,out] file Settings file.
Definition at line 1335 of file Mode.cpp.
References settings, and nnp::Settings::writeSettingsFile().
Referenced by main().
 {
     settings.writeSettingsFile(file);
     return;
 }
Member Data Documentation
elementMap
ElementMap nnp::Mode::elementMap
Global element map, populated by setupElementMap().
Definition at line 462 of file Mode.h.
Referenced by nnp::Dataset::distributeStructures(), nnp::InterfaceLammps::initialize(), main(), nnp::Prediction::readStructureFromFile(), nnp::Training::selectSets(), setupElementMap(), setupElements(), setupNeuralNetwork(), setupSymmetryFunctionMemory(), setupSymmetryFunctions(), nnp::Dataset::writeAtomicEnvironmentFile(), nnp::Dataset::writeNeighborLists(), nnp::Dataset::writeSymmetryFunctionFile(), nnp::Dataset::writeSymmetryFunctionHistograms(), and nnp::Training::writeUpdaterStatus().
log
Log nnp::Mode::log
Global log file.
Definition at line 464 of file Mode.h.
Referenced by nnp::Training::calculateError(), nnp::Training::calculateNeighborLists(), calculateSymmetryFunctionGroups(), calculateSymmetryFunctions(), nnp::Training::checkSelectionMode(), nnp::Dataset::collectSymmetryFunctionStatistics(), nnp::Dataset::distributeStructures(), LAMMPS_NS::PairNNP::init_style(), nnp::InterfaceLammps::initialize(), initialize(), nnp::Training::initializeWeights(), nnp::Training::initializeWeightsMemory(), loadSettingsFile(), nnp::Training::loop(), main(), nnp::Training::selectSets(), setupCutoff(), setupElementMap(), setupElements(), nnp::Dataset::setupMPI(), setupNeuralNetwork(), setupNeuralNetworkWeights(), setupNormalization(), nnp::Dataset::setupRandomNumberGenerator(), setupSymmetryFunctionGroups(), setupSymmetryFunctionMemory(), setupSymmetryFunctions(), setupSymmetryFunctionScaling(), setupSymmetryFunctionScalingNone(), setupSymmetryFunctionStatistics(), nnp::Training::setupTraining(), nnp::Dataset::sortNeighborLists(), nnp::Dataset::writeAtomicEnvironmentFile(), nnp::InterfaceLammps::writeExtrapolationWarnings(), nnp::Dataset::writeNeighborHistogram(), nnp::Dataset::writeNeighborLists(), nnp::Training::writeSetsToFiles(), nnp::Dataset::writeSymmetryFunctionFile(), nnp::Dataset::writeSymmetryFunctionHistograms(), and nnp::Dataset::writeSymmetryFunctionScaling().
normalize
bool nnp::Mode::normalize protected
Definition at line 467 of file Mode.h.
Referenced by nnp::InterfaceLammps::addNeighbor(), nnp::Training::calculateError(), nnp::Training::calculateNeighborLists(), nnp::InterfaceLammps::getAtomicEnergy(), nnp::InterfaceLammps::getForces(), nnp::InterfaceLammps::getMaxCutoffRadius(), nnp::Prediction::predict(), nnp::InterfaceLammps::process(), nnp::Prediction::readStructureFromFile(), setupNormalization(), setupSymmetryFunctions(), useNormalization(), nnp::Training::writeLearningCurve(), and nnp::Dataset::writeSymmetryFunctionFile().
checkExtrapolationWarnings
bool nnp::Mode::checkExtrapolationWarnings protected
Definition at line 468 of file Mode.h.
Referenced by calculateSymmetryFunctionGroups(), calculateSymmetryFunctions(), and setupSymmetryFunctionStatistics().
numElements
std::size_t nnp::Mode::numElements protected
Definition at line 469 of file Mode.h.
Referenced by addEnergyOffset(), nnp::Training::calculateWeightDerivatives(), getEnergyOffset(), getEnergyWithOffset(), getNumElements(), nnp::Training::getWeights(), nnp::Training::initializeWeights(), nnp::Training::initializeWeightsMemory(), pruneSymmetryFunctionsSensitivity(), removeEnergyOffset(), nnp::Training::selectSets(), nnp::InterfaceLammps::setLocalAtoms(), setupElements(), setupNeuralNetwork(), setupSymmetryFunctionMemory(), setupSymmetryFunctions(), nnp::Training::setWeights(), nnp::Training::update(), nnp::Dataset::writeAtomicEnvironmentFile(), nnp::Dataset::writeNeighborLists(), nnp::Training::writeNeuronStatistics(), and nnp::Training::writeWeights().
minNeighbors
std::vector<std::size_t> nnp::Mode::minNeighbors protected
Definition at line 470 of file Mode.h.
Referenced by calculateSymmetryFunctionGroups(), calculateSymmetryFunctions(), setupSymmetryFunctions(), and nnp::Dataset::writeNeighborHistogram().
minCutoffRadius
std::vector<double> nnp::Mode::minCutoffRadius protected
Definition at line 471 of file Mode.h.
Referenced by calculateSymmetryFunctionGroups(), calculateSymmetryFunctions(), and setupSymmetryFunctions().
maxCutoffRadius
double nnp::Mode::maxCutoffRadius protected
Definition at line 472 of file Mode.h.
Referenced by nnp::Training::calculateNeighborLists(), nnp::InterfaceLammps::getMaxCutoffRadius(), getMaxCutoffRadius(), nnp::Prediction::predict(), and setupSymmetryFunctions().
cutoffAlpha
double nnp::Mode::cutoffAlpha protected
Definition at line 473 of file Mode.h.
Referenced by setupCutoff(), and setupSymmetryFunctions().
meanEnergy
double nnp::Mode::meanEnergy protected
Definition at line 474 of file Mode.h.
Referenced by convertToNormalizedUnits(), convertToPhysicalUnits(), getMeanEnergy(), normalizedEnergy(), physicalEnergy(), nnp::Prediction::predict(), nnp::Prediction::readStructureFromFile(), setupNormalization(), nnp::Dataset::toNormalizedUnits(), and nnp::Dataset::toPhysicalUnits().
convEnergy
double nnp::Mode::convEnergy protected
Definition at line 475 of file Mode.h.
Referenced by convertToNormalizedUnits(), convertToPhysicalUnits(), getConvEnergy(), nnp::InterfaceLammps::getForces(), normalizedEnergy(), normalizedForce(), physicalEnergy(), physicalForce(), nnp::Prediction::predict(), nnp::Prediction::readStructureFromFile(), setupNormalization(), nnp::Dataset::toNormalizedUnits(), and nnp::Dataset::toPhysicalUnits().
convLength
double nnp::Mode::convLength protected
Definition at line 476 of file Mode.h.
Referenced by nnp::InterfaceLammps::addNeighbor(), nnp::Training::calculateNeighborLists(), convertToNormalizedUnits(), convertToPhysicalUnits(), getConvLength(), nnp::InterfaceLammps::getForces(), nnp::InterfaceLammps::getMaxCutoffRadius(), normalizedForce(), physicalForce(), nnp::Prediction::predict(), nnp::Prediction::readStructureFromFile(), setupNormalization(), setupSymmetryFunctions(), nnp::Dataset::toNormalizedUnits(), and nnp::Dataset::toPhysicalUnits().
settings
Settings nnp::Mode::settings protected
Definition at line 477 of file Mode.h.
Referenced by nnp::Training::initializeWeights(), loadSettingsFile(), nnp::Training::selectSets(), settingsGetValue(), settingsKeywordExists(), setupCutoff(), setupElementMap(), setupElements(), setupNeuralNetwork(), setupNormalization(), nnp::Dataset::setupRandomNumberGenerator(), setupSymmetryFunctions(), setupSymmetryFunctionScaling(), nnp::Training::setupTraining(), writePrunedSettingsFile(), and writeSettingsFile().
scalingType
SymmetryFunction::ScalingType nnp::Mode::scalingType protected
Definition at line 478 of file Mode.h.
Referenced by setupSymmetryFunctionScaling().
cutoffType
CutoffFunction::CutoffType nnp::Mode::cutoffType protected
Definition at line 479 of file Mode.h.
Referenced by setupCutoff(), and setupSymmetryFunctions().
elements
std::vector<Element> nnp::Mode::elements protected
Definition at line 480 of file Mode.h.
Referenced by addEnergyOffset(), nnp::Training::addTrainingLogEntry(), calculateAtomicNeuralNetworks(), calculateForces(), calculateSymmetryFunctionGroups(), calculateSymmetryFunctions(), nnp::Training::calculateWeightDerivatives(), nnp::InterfaceLammps::clearExtrapolationWarnings(), nnp::Dataset::collectSymmetryFunctionStatistics(), nnp::InterfaceLammps::extractEWBuffer(), nnp::InterfaceLammps::fillEWBuffer(), getEnergyOffset(), getEnergyWithOffset(), nnp::InterfaceLammps::getEWBufferSize(), nnp::InterfaceLammps::getForces(), getNumExtrapolationWarnings(), getNumSymmetryFunctions(), nnp::Training::getWeights(), nnp::Training::initializeWeights(), nnp::Training::initializeWeightsMemory(), pruneSymmetryFunctionsRange(), pruneSymmetryFunctionsSensitivity(), removeEnergyOffset(), resetExtrapolationWarnings(), nnp::Training::resetNeuronStatistics(), setupElements(), setupNeuralNetwork(), setupNeuralNetworkWeights(), setupSymmetryFunctionGroups(), setupSymmetryFunctionMemory(), setupSymmetryFunctions(), setupSymmetryFunctionScaling(), setupSymmetryFunctionScalingNone(), setupSymmetryFunctionStatistics(), nnp::Training::setupTraining(), nnp::Training::setWeights(), nnp::Training::update(), nnp::InterfaceLammps::writeExtrapolationWarnings(), nnp::Training::writeNeuronStatistics(), nnp::Dataset::writeSymmetryFunctionHistograms(), nnp::Dataset::writeSymmetryFunctionScaling(), and nnp::Training::writeWeights().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/Mode.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/Mode.cpp