n2p2 - A neural network potential package: nnp::SymmetryFunctionAngularNarrow Class Reference
nnp::SymmetryFunctionAngularNarrow Class Reference
Angular symmetry function (type 3)
#include <SymmetryFunctionAngularNarrow.h>
Public Member Functions
SymmetryFunctionAngularNarrow (ElementMap const &elementMap)
Constructor, sets type = 3.
bool operator== (SymmetryFunction const &rhs) const
Overload == operator.
bool operator!= (SymmetryFunction const &rhs) const
Overload != operator.
bool operator< (SymmetryFunction const &rhs) const
Overload < operator.
bool operator> (SymmetryFunction const &rhs) const
Overload > operator.
bool operator<= (SymmetryFunction const &rhs) const
Overload <= operator.
bool operator>= (SymmetryFunction const &rhs) const
Overload >= operator.
void setParameters (std::string const &parameterString)
Set symmetry function parameters.
void changeLengthUnit (double convLength)
Change length unit.
std::string getSettingsLine () const
Get settings file line from currently set parameters.
void calculate (Atom &atom, bool const derivatives) const
Calculate symmetry function for one atom.
std::string parameterLine () const
Give symmetry function parameters in one line.
std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
bool getUseIntegerPow () const
Get private useIntegerPow member variable.
std::size_t getE1 () const
Get private e1 member variable.
std::size_t getE2 () const
Get private e2 member variable.
int getZetaInt () const
Get private zetaInt member variable.
double getLambda () const
Get private lambda member variable.
double getEta () const
Get private eta member variable.
double getZeta () const
Get private zeta member variable.
double getRs () const
Get private rs member variable.
double calculateRadialPart (double distance) const
Calculate (partial) symmetry function value for one given distance.
double calculateAngularPart (double angle) const
Calculate (partial) symmetry function value for one given angle.
bool checkRelevantElement (std::size_t index) const
Check whether symmetry function is relevant for given element.
Public Member Functions inherited from nnp::SymmetryFunction
virtual ~SymmetryFunction ()
Virtual destructor.
void setCutoffFunction (CutoffFunction::CutoffType cutoffType, double cutoffAlpha)
Set cutoff function type and parameter.
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
double scale (double value) const
Apply symmetry function scaling and/or centering.
double unscale (double value) const
Undo symmetry function scaling and/or centering.
std::size_t getType () const
Get private type member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getLineNumber () const
Get private lineNumber member variable.
std::size_t getEc () const
Get private ec member variable.
std::size_t getMinNeighbors () const
Get private minNeighbors member variable.
double getRc () const
Get private rc member variable.
double getGmin () const
Get private Gmin member variable.
double getGmax () const
Get private Gmax member variable.
double getScalingFactor () const
Get private scalingFactor member variable.
double getCutoffAlpha () const
Get private cutoffAlpha member variable.
double getConvLength () const
Get private convLength member variable.
CutoffFunction::CutoffType getCutoffType () const
Get private cutoffType member variable.
std::set< std::string > getParameters () const
Get private parameters member variable.
std::vector< std::size_t > getIndexPerElement () const
Get private indexPerElement member variable.
void setIndex (std::size_t index)
Set private index member variable.
void setIndexPerElement (std::size_t elementIndex, std::size_t index)
Set private indexPerElement member variable.
void setLineNumber (std::size_t lineNumber)
Set line number.
std::string scalingLine () const
Get string with scaling information.
Private Attributes
bool useIntegerPow
Whether to use integer version of power function (faster).
std::size_t e1
Element index of neighbor atom 1.
std::size_t e2
Element index of neighbor atom 2.
int zetaInt
Integer version of .
double lambda
Cosine shift factor.
double eta
Width of gaussian.
double zeta
Exponent of cosine term.
double rs
Shift of gaussian.
Additional Inherited Members
Public Types inherited from nnp::SymmetryFunction
enum ScalingType {
ST_NONE, ST_SCALE, ST_CENTER, ST_SCALECENTER,
ST_SCALESIGMA
}
List of available scaling types.
Protected Types inherited from nnp::SymmetryFunction
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymmetryFunction
SymmetryFunction (std::size_t type, ElementMap const &)
Constructor, initializes type.
std::string getPrintFormat () const
Generate format string for symmetry function parameter printing.
Static Protected Member Functions inherited from nnp::SymmetryFunction
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymmetryFunction
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function index (per element).
std::size_t lineNumber
Line number.
std::size_t ec
Element index of center atom.
std::size_t minNeighbors
Minimum number of neighbors required.
double Smin
Minimum for scaling range.
double Smax
Maximum for scaling range.
double Gmin
Minimum unscaled symmetry function value.
double Gmax
Maximum unscaled symmetry function value.
double Gmean
Mean unscaled symmetry function value.
double Gsigma
Sigma of unscaled symmetry function values.
double rc
Cutoff radius .
double scalingFactor
Scaling factor.
double cutoffAlpha
Cutoff parameter .
double convLength
Data set normalization length conversion factor.
CutoffFunction fc
Cutoff function used by this symmetry function.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function.
ScalingType scalingType
Symmetry function scaling type used by this symmetry function.
std::set< std::string > parameters
Set with symmetry function parameter IDs (lookup for printing).
std::vector< std::size_t > indexPerElement
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
Static Protected Attributes inherited from nnp::SymmetryFunction
static std::size_t const sfinfoWidth = 12
Width of the SFINFO parameter description field (see parameterInfo()).
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Angular symmetry function (type 3)
Parameter string:
<element-central> 3 <element-neighbor1> <element-neighbor2> <eta> <lambda> <zeta> <rcutoff> <<rshift>>
where
<element-central> ..... element symbol of central atom
<element-neighbor1> ... element symbol of neighbor atom 1
<element-neighbor2> ... element symbol of neighbor atom 2
<eta> .................
<lambda> ..............
<zeta> ................
<rcutoff> .............
<<rshift>> ............ (optional, default)
Definition at line 55 of file SymmetryFunctionAngularNarrow.h.
Constructor & Destructor Documentation
SymmetryFunctionAngularNarrow()
SymmetryFunctionAngularNarrow::SymmetryFunctionAngularNarrow (ElementMap const & elementMap)
Constructor, sets type = 3.
Definition at line 31 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::minNeighbors, operator==(), and nnp::SymmetryFunction::parameters.
                                                             :
     SymmetryFunction(3, elementMap),
     useIntegerPow(false),
     e1           (0    ),
     e2           (0    ),
     zetaInt      (0    ),
     lambda       (0.0  ),
     eta          (0.0  ),
     zeta         (0.0  ),
     rs           (0.0  )
 {
     minNeighbors = 2;
     parameters.insert("e1");
     parameters.insert("e2");
     parameters.insert("eta");
     parameters.insert("zeta");
     parameters.insert("lambda");
     parameters.insert("rs");
 }
Member Function Documentation
operator==()
bool SymmetryFunctionAngularNarrow::operator== (SymmetryFunction const & rhs) const virtual
Overload == operator.
Implements nnp::SymmetryFunction.
Definition at line 52 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::cutoffAlpha, nnp::SymmetryFunction::cutoffType, e1, e2, nnp::SymmetryFunction::ec, eta, nnp::SymmetryFunction::getEc(), nnp::SymmetryFunction::getType(), lambda, operator<(), nnp::SymmetryFunction::rc, nnp::SymmetryFunction::type, and zeta.
Referenced by SymmetryFunctionAngularNarrow().
 {
     if (ec   != rhs.getEc()  ) return false;
     if (type != rhs.getType()) return false;
     SymmetryFunctionAngularNarrow const& c =
         dynamic_cast<SymmetryFunctionAngularNarrow const&>(rhs);
     if (cutoffType  != c.cutoffType ) return false;
     if (cutoffAlpha != c.cutoffAlpha) return false;
     if (rc          != c.rc         ) return false;
     if (eta         != c.eta        ) return false;
     if (zeta        != c.zeta       ) return false;
     if (lambda      != c.lambda     ) return false;
     if (e1          != c.e1         ) return false;
     if (e2          != c.e2         ) return false;
     return true;
 }
operator!=()
bool nnp::SymmetryFunctionAngularNarrow::operator!= (SymmetryFunction const & rhs) const inline virtual
Overload != operator.
Implements nnp::SymmetryFunction.
Definition at line 181 of file SymmetryFunctionAngularNarrow.h.
References operator>().
 {
     return !((*this) == rhs);
 }
operator<()
bool SymmetryFunctionAngularNarrow::operator< (SymmetryFunction const & rhs) const virtual
Overload < operator.
Implements nnp::SymmetryFunction.
Definition at line 70 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::cutoffAlpha, nnp::SymmetryFunction::cutoffType, e1, e2, nnp::SymmetryFunction::ec, eta, nnp::SymmetryFunction::getEc(), nnp::SymmetryFunction::getType(), lambda, nnp::SymmetryFunction::rc, rs, setParameters(), nnp::SymmetryFunction::type, and zeta.
Referenced by operator==().
 {
     if      (ec   < rhs.getEc()  ) return true;
     else if (ec   > rhs.getEc()  ) return false;
     if      (type < rhs.getType()) return true;
     else if (type > rhs.getType()) return false;
     SymmetryFunctionAngularNarrow const& c =
         dynamic_cast<SymmetryFunctionAngularNarrow const&>(rhs);
     if      (cutoffType  < c.cutoffType ) return true;
     else if (cutoffType  > c.cutoffType ) return false;
     if      (cutoffAlpha < c.cutoffAlpha) return true;
     else if (cutoffAlpha > c.cutoffAlpha) return false;
     if      (rc          < c.rc         ) return true;
     else if (rc          > c.rc         ) return false;
     if      (eta         < c.eta        ) return true;
     else if (eta         > c.eta        ) return false;
     if      (rs          < c.rs         ) return true;
     else if (rs          > c.rs         ) return false;
     if      (zeta        < c.zeta       ) return true;
     else if (zeta        > c.zeta       ) return false;
     if      (lambda      < c.lambda     ) return true;
     else if (lambda      > c.lambda     ) return false;
     if      (e1          < c.e1         ) return true;
     else if (e1          > c.e1         ) return false;
     if      (e2          < c.e2         ) return true;
     else if (e2          > c.e2         ) return false;
     return false;
 }
operator>()
bool nnp::SymmetryFunctionAngularNarrow::operator> (SymmetryFunction const & rhs) const inline virtual
Overload > operator.
Implements nnp::SymmetryFunction.
Definition at line 187 of file SymmetryFunctionAngularNarrow.h.
References operator<=().
Referenced by operator!=().
 {
     return rhs < (*this);
 }
operator<=()
bool nnp::SymmetryFunctionAngularNarrow::operator<= (SymmetryFunction const & rhs) const inline virtual
Overload <= operator.
Implements nnp::SymmetryFunction.
Definition at line 193 of file SymmetryFunctionAngularNarrow.h.
References operator>=().
Referenced by operator>().
 {
     return !((*this) > rhs);
 }
operator>=()
bool nnp::SymmetryFunctionAngularNarrow::operator>= (SymmetryFunction const & rhs) const inline virtual
Overload >= operator.
Implements nnp::SymmetryFunction.
Definition at line 199 of file SymmetryFunctionAngularNarrow.h.
Referenced by operator<=().
 {
     return !((*this) < rhs);
 }
setParameters()
void SymmetryFunctionAngularNarrow::setParameters (std::string const & parameterString) virtual
Set symmetry function parameters.
Parameters
[in] parameterString String containing angular symmetry function parameters.
Implements nnp::SymmetryFunction.
Definition at line 100 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::cutoffAlpha, e1, e2, nnp::SymmetryFunction::ec, nnp::SymmetryFunction::elementMap, eta, nnp::SymmetryFunction::fc, lambda, nnp::SymmetryFunction::rc, nnp::reduce(), rs, nnp::CutoffFunction::setCutoffParameter(), nnp::CutoffFunction::setCutoffRadius(), nnp::split(), nnp::SymmetryFunction::type, useIntegerPow, zeta, and zetaInt.
Referenced by operator<().
 {
     vector<string> splitLine = split(reduce(parameterString));
     if (type != (size_t)atoi(splitLine.at(1).c_str()))
     {
         throw runtime_error("ERROR: Incorrect symmetry function type.\n");
     }
     ec     = elementMap[splitLine.at(0)];
     e1     = elementMap[splitLine.at(2)];
     e2     = elementMap[splitLine.at(3)];
     eta    = atof(splitLine.at(4).c_str());
     lambda = atof(splitLine.at(5).c_str());
     zeta   = atof(splitLine.at(6).c_str());
     rc     = atof(splitLine.at(7).c_str());
     // Shift parameter is optional.
     if (splitLine.size() > 8)
     {
         rs = atof(splitLine.at(8).c_str());
     }
     fc.setCutoffRadius(rc);
     fc.setCutoffParameter(cutoffAlpha);
     if (e1 > e2)
     {
         size_t tmp = e1;
         e1         = e2;
         e2         = tmp;
     }
     zetaInt = round(zeta);
     if (fabs(zeta - zetaInt) <= numeric_limits<double>::min())
     {
         useIntegerPow = true;
     }
     else
     {
         useIntegerPow = false;
     }
     return;
 }
changeLengthUnit()
void SymmetryFunctionAngularNarrow::changeLengthUnit (double convLength) virtual
Change length unit.
Parameters
[in] convLength Multiplicative length unit conversion factor.
Implements nnp::SymmetryFunction.
Definition at line 145 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::convLength, nnp::SymmetryFunction::cutoffAlpha, eta, nnp::SymmetryFunction::fc, nnp::SymmetryFunction::rc, rs, nnp::CutoffFunction::setCutoffParameter(), and nnp::CutoffFunction::setCutoffRadius().
 {
     this->convLength = convLength;
     eta /= convLength * convLength;
     rc *= convLength;
     rs *= convLength;
     fc.setCutoffRadius(rc);
     fc.setCutoffParameter(cutoffAlpha);
     return;
 }
getSettingsLine()
string SymmetryFunctionAngularNarrow::getSettingsLine () const virtual
Get settings file line from currently set parameters.
Returns
Settings file string ("symfunction_short ...").
Implements nnp::SymmetryFunction.
Definition at line 158 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::convLength, e1, e2, nnp::SymmetryFunction::ec, nnp::SymmetryFunction::elementMap, eta, lambda, nnp::SymmetryFunction::rc, rs, nnp::strpr(), nnp::SymmetryFunction::type, and zeta.
 {
     string s = strpr("symfunction_short %2s %2zu %2s %2s %16.8E %16.8E "
                      "%16.8E %16.8E %16.8E\n",
                      elementMap[ec].c_str(),
                      type,
                      elementMap[e1].c_str(),
                      elementMap[e2].c_str(),
                      eta * convLength * convLength,
                      lambda,
                      zeta,
                      rc / convLength,
                      rs / convLength);
     return s;
 }
calculate()
void SymmetryFunctionAngularNarrow::calculate (Atom & atom, bool const derivatives) const virtual
Calculate symmetry function for one atom.
Parameters
[in,out] atom Atom for which the symmetry function is caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymmetryFunction.
Definition at line 175 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::Atom::Neighbor::cutoffAlpha, nnp::SymmetryFunction::cutoffAlpha, nnp::Atom::Neighbor::cutoffType, nnp::SymmetryFunction::cutoffType, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dfc, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, e1, e2, nnp::Atom::Neighbor::element, eta, nnp::Atom::Neighbor::fc, nnp::SymmetryFunction::fc, nnp::CutoffFunction::fdf(), nnp::Atom::G, nnp::SymmetryFunction::index, nnp::SymmetryFunction::indexPerElement, lambda, nnp::Atom::neighbors, nnp::Vec3D::norm2(), nnp::Atom::numNeighbors, nnp::pow_int(), nnp::Atom::Neighbor::rc, nnp::SymmetryFunction::rc, rs, nnp::SymmetryFunction::scale(), nnp::SymmetryFunction::scalingFactor, useIntegerPow, zeta, and zetaInt.
 {
     double const pnorm  = pow(2.0, 1.0 - zeta);
     double const pzl    = zeta * lambda;
     double const rc2    = rc * rc;
     double       result = 0.0;
     size_t numNeighbors = atom.numNeighbors;
     // Prevent problematic condition in loop test below (j < numNeighbors - 1).
     if (numNeighbors == 0) numNeighbors = 1;
     for (size_t j = 0; j < numNeighbors - 1; j++)
     {
         Atom::Neighbor& nj = atom.neighbors[j];
         size_t const nej = nj.element;
         double const rij = nj.d;
         if ((e1 == nej || e2 == nej) && rij < rc)
         {
             double const r2ij   = rij * rij;
             // Calculate cutoff function and derivative.
 #ifdef NOCFCACHE
             double pfcij;
             double pdfcij;
             fc.fdf(rij, pfcij, pdfcij);
 #else
             // If cutoff radius matches with the one in the neighbor storage
             // we can use the previously calculated value.
             double& pfcij = nj.fc;
             double& pdfcij = nj.dfc;
             if (nj.cutoffType != cutoffType ||
                 nj.rc != rc ||
                 nj.cutoffAlpha != cutoffAlpha)
             {
                 fc.fdf(rij, pfcij, pdfcij);
                 nj.rc = rc;
                 nj.cutoffType = cutoffType;
                 nj.cutoffAlpha = cutoffAlpha;
             }
 #endif
             for (size_t k = j + 1; k < numNeighbors; k++)
             {
                 Atom::Neighbor& nk = atom.neighbors[k];
                 size_t const nek = nk.element;
                 if ((e1 == nej && e2 == nek) ||
                     (e2 == nej && e1 == nek))
                 {
                     double const rik = nk.d;
                     if (rik < rc)
                     {
                         Vec3D drjk = nk.dr - nj.dr;
                         double rjk = drjk.norm2();;
                         if (rjk < rc2)
{
                             // Energy calculation.
 #ifdef NOCFCACHE
                             double pfcik;
                             double pdfcik;
                             fc.fdf(rik, pfcik, pdfcik);
 #else
                             double& pfcik = nk.fc;
                             double& pdfcik = nk.dfc;
                             if (nk.cutoffType != cutoffType ||
                                 nk.rc != rc ||
                                 nk.cutoffAlpha != cutoffAlpha)
{
                                 fc.fdf(rik, pfcik, pdfcik);
                                 nk.rc = rc;
                                 nk.cutoffType = cutoffType;
                                 nk.cutoffAlpha = cutoffAlpha;
                             }
 #endif
                             rjk = sqrt(rjk);
                             double pfcjk;
                             double pdfcjk;
                             fc.fdf(rjk, pfcjk, pdfcjk);
                             Vec3D drij = nj.dr;
                             Vec3D drik = nk.dr;
                             double costijk = drij * drik;;
                             double rinvijik = 1.0 / rij / rik;
                             costijk *= rinvijik;
                             double const pfc = pfcij * pfcik * pfcjk;
                             double const r2ik = rik * rik;
                             double const rijs = rij - rs;
                             double const riks = rik - rs;
                             double const rjks = rjk - rs;
                             double const pexp = exp(-eta * (rijs * rijs +
                                                             riks * riks +
                                                             rjks * rjks));
                             double const plambda = 1.0 + lambda * costijk;
                             double       fg = pexp;
                             if (plambda <= 0.0) fg = 0.0;
                             else
{
                                 if (useIntegerPow)
{
                                     fg *= pow_int(plambda, zetaInt - 1);
                                 }
                                 else
{
                                     fg *= pow(plambda, zeta - 1.0);
                                 }
                             }
                             result += fg * plambda * pfc;
                             // Force calculation.
                             if (!derivatives) continue;
                             fg       *= pnorm;
                             rinvijik *= pzl;
                             costijk  *= pzl;
                             double const p2etapl = 2.0 * eta * plambda;
                             double const p1 = fg * (pfc * (rinvijik - costijk
                                             / r2ij - p2etapl * rijs / rij)
                                             + pfcik * pfcjk * pdfcij * plambda
                                             / rij);
                             double const p2 = fg * (pfc * (rinvijik - costijk
                                             / r2ik - p2etapl * riks / rik)
                                             + pfcij * pfcjk * pdfcik * plambda
                                             / rik);
                             double const p3 = fg * (pfc * (rinvijik + p2etapl
                                             * rjks / rjk) - pfcij * pfcik
                                             * pdfcjk * plambda / rjk);
                             drij *= p1 * scalingFactor;
                             drik *= p2 * scalingFactor;
                             drjk *= p3 * scalingFactor;
                             // Save force contributions in Atom storage.
                             atom.dGdr[index] += drij + drik;
 #ifdef IMPROVED_SFD_MEMORY
                             nj.dGdr[indexPerElement[nej]] -= drij + drjk;
                             nk.dGdr[indexPerElement[nek]] -= drik - drjk;
 #else
                             nj.dGdr[index] -= drij + drjk;
                             nk.dGdr[index] -= drik - drjk;
 #endif
                         } // rjk <= rc
                     } // rik <= rc
                 } // elem
             } // k
         } // rij <= rc
     } // j
     result *= pnorm;
     atom.G[index] = scale(result);
     return;
 }
parameterLine()
string SymmetryFunctionAngularNarrow::parameterLine () const virtual
Give symmetry function parameters in one line.
Returns
String containing symmetry function parameter values.
Implements nnp::SymmetryFunction.
Definition at line 326 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::convLength, nnp::SymmetryFunction::cutoffAlpha, nnp::SymmetryFunction::cutoffType, e1, e2, nnp::SymmetryFunction::ec, nnp::SymmetryFunction::elementMap, eta, nnp::SymmetryFunction::getPrintFormat(), nnp::SymmetryFunction::index, lambda, nnp::SymmetryFunction::lineNumber, nnp::SymmetryFunction::rc, rs, nnp::strpr(), nnp::SymmetryFunction::type, and zeta.
 {
     return strpr(getPrintFormat().c_str(),
                  index + 1,
                  elementMap[ec].c_str(),
                  type,
                  elementMap[e1].c_str(),
                  elementMap[e2].c_str(),
                  eta * convLength * convLength,
                  rs / convLength,
                  lambda,
                  zeta,
                  rc / convLength,
                  (int)cutoffType,
                  cutoffAlpha,
                  lineNumber + 1);
 }
parameterInfo()
vector< string > SymmetryFunctionAngularNarrow::parameterInfo () const virtual
Get description with parameter names and values.
Returns
Vector of parameter description strings.
Reimplemented from nnp::SymmetryFunction.
Definition at line 344 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::convLength, e1, e2, nnp::SymmetryFunction::elementMap, eta, lambda, nnp::pad(), nnp::SymmetryFunction::parameterInfo(), rs, nnp::SymmetryFunction::sfinfoWidth, nnp::strpr(), and zeta.
 {
     vector<string> v = SymmetryFunction::parameterInfo();
     string s;
     size_t w = sfinfoWidth;
     s = "e1";
     v.push_back(strpr((pad(s, w) + "%s"    ).c_str(), elementMap[e1].c_str()));
     s = "e2";
     v.push_back(strpr((pad(s, w) + "%s"    ).c_str(), elementMap[e2].c_str()));
     s = "eta";
     v.push_back(strpr((pad(s, w) + "%14.8E").c_str(),
                       eta * convLength * convLength));
     s = "lambda";
     v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), lambda));
     s = "zeta";
     v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), zeta));
     s = "rs";
     v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), rs / convLength));
     return v;
 }
getUseIntegerPow()
bool nnp::SymmetryFunctionAngularNarrow::getUseIntegerPow () const inline
Get private useIntegerPow member variable.
Definition at line 204 of file SymmetryFunctionAngularNarrow.h.
References useIntegerPow.
 {
     return useIntegerPow;
 }
getE1()
std::size_t nnp::SymmetryFunctionAngularNarrow::getE1 () const inline
Get private e1 member variable.
Definition at line 209 of file SymmetryFunctionAngularNarrow.h.
References e1.
Referenced by nnp::SymmetryFunctionGroupAngularNarrow::addMember().
 {
     return e1;
 }
getE2()
std::size_t nnp::SymmetryFunctionAngularNarrow::getE2 () const inline
Get private e2 member variable.
Definition at line 214 of file SymmetryFunctionAngularNarrow.h.
References e2.
Referenced by nnp::SymmetryFunctionGroupAngularNarrow::addMember().
 {
     return e2;
 }
getZetaInt()
int nnp::SymmetryFunctionAngularNarrow::getZetaInt () const inline
Get private zetaInt member variable.
Definition at line 219 of file SymmetryFunctionAngularNarrow.h.
References zetaInt.
 {
     return zetaInt;
 }
getLambda()
double nnp::SymmetryFunctionAngularNarrow::getLambda () const inline
Get private lambda member variable.
Definition at line 224 of file SymmetryFunctionAngularNarrow.h.
References lambda.
 {
     return lambda;
 }
getEta()
double nnp::SymmetryFunctionAngularNarrow::getEta () const inline
Get private eta member variable.
Definition at line 229 of file SymmetryFunctionAngularNarrow.h.
References eta.
 {
     return eta;
 }
getZeta()
double nnp::SymmetryFunctionAngularNarrow::getZeta () const inline
Get private zeta member variable.
Definition at line 234 of file SymmetryFunctionAngularNarrow.h.
References zeta.
 {
     return zeta;
 }
getRs()
double nnp::SymmetryFunctionAngularNarrow::getRs () const inline
Get private rs member variable.
Definition at line 239 of file SymmetryFunctionAngularNarrow.h.
References rs.
 {
     return rs;
 }
calculateRadialPart()
double SymmetryFunctionAngularNarrow::calculateRadialPart (double distance) const virtual
Calculate (partial) symmetry function value for one given distance.
Parameters
[in] distance Distance between two atoms.
Returns
Implements nnp::SymmetryFunction.
Definition at line 367 of file SymmetryFunctionAngularNarrow.cpp.
References nnp::SymmetryFunction::convLength, eta, nnp::CutoffFunction::f(), nnp::SymmetryFunction::fc, p, and rs.
 {
     double const& r = distance * convLength;
     double const p = exp(-eta * (r - rs) * (r - rs)) * fc.f(r);
     return p * p * p;
 }
calculateAngularPart()
double SymmetryFunctionAngularNarrow::calculateAngularPart (double angle) const virtual
Calculate (partial) symmetry function value for one given angle.
Parameters
[in] angle Angle between triplet of atoms (in radians).
Returns
Implements nnp::SymmetryFunction.
Definition at line 376 of file SymmetryFunctionAngularNarrow.cpp.
References lambda, and zeta.
 {
     return 2.0 * pow((1.0 + lambda * cos(angle)) / 2.0, zeta);
 }
checkRelevantElement()
bool SymmetryFunctionAngularNarrow::checkRelevantElement (std::size_t index) const virtual
Check whether symmetry function is relevant for given element.
Parameters
[in] index Index of given element.
Returns
True if symmetry function is sensitive to given element, false otherwise.
Implements nnp::SymmetryFunction.
Definition at line 381 of file SymmetryFunctionAngularNarrow.cpp.
References e1, and e2.
 {
     if (index == e1 || index == e2) return true;
     else return false;
 }
Member Data Documentation
useIntegerPow
bool nnp::SymmetryFunctionAngularNarrow::useIntegerPow private
Whether to use integer version of power function (faster).
Definition at line 159 of file SymmetryFunctionAngularNarrow.h.
Referenced by calculate(), getUseIntegerPow(), and setParameters().
e1
std::size_t nnp::SymmetryFunctionAngularNarrow::e1 private
Element index of neighbor atom 1.
Definition at line 161 of file SymmetryFunctionAngularNarrow.h.
Referenced by calculate(), checkRelevantElement(), getE1(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
e2
std::size_t nnp::SymmetryFunctionAngularNarrow::e2 private
Element index of neighbor atom 2.
Definition at line 163 of file SymmetryFunctionAngularNarrow.h.
Referenced by calculate(), checkRelevantElement(), getE2(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
zetaInt
int nnp::SymmetryFunctionAngularNarrow::zetaInt private
Integer version of .
Definition at line 165 of file SymmetryFunctionAngularNarrow.h.
Referenced by calculate(), getZetaInt(), and setParameters().
lambda
double nnp::SymmetryFunctionAngularNarrow::lambda private
Cosine shift factor.
Definition at line 167 of file SymmetryFunctionAngularNarrow.h.
Referenced by calculate(), calculateAngularPart(), getLambda(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
eta
double nnp::SymmetryFunctionAngularNarrow::eta private
Width of gaussian.
Definition at line 169 of file SymmetryFunctionAngularNarrow.h.
Referenced by calculate(), calculateRadialPart(), changeLengthUnit(), getEta(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
zeta
double nnp::SymmetryFunctionAngularNarrow::zeta private
Exponent of cosine term.
Definition at line 171 of file SymmetryFunctionAngularNarrow.h.
Referenced by calculate(), calculateAngularPart(), getSettingsLine(), getZeta(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
rs
double nnp::SymmetryFunctionAngularNarrow::rs private
Shift of gaussian.
Definition at line 173 of file SymmetryFunctionAngularNarrow.h.
Referenced by calculate(), calculateRadialPart(), changeLengthUnit(), getRs(), getSettingsLine(), operator<(), parameterInfo(), parameterLine(), and setParameters().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunctionAngularNarrow.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunctionAngularNarrow.cpp