n2p2 - A neural network potential package: nnp::SymmetryFunctionGroupRadial Class Reference
nnp::SymmetryFunctionGroupRadial Class Reference
Radial symmetry function group (type 2)
#include <SymmetryFunctionGroupRadial.h>
Public Member Functions
SymmetryFunctionGroupRadial (ElementMap const &elementMap)
Constructor, sets type = 2.
bool operator== (SymmetryFunctionGroup const &rhs) const
Overload == operator.
bool operator!= (SymmetryFunctionGroup const &rhs) const
Overload != operator.
bool operator< (SymmetryFunctionGroup const &rhs) const
Overload < operator.
bool operator> (SymmetryFunctionGroup const &rhs) const
Overload > operator.
bool operator<= (SymmetryFunctionGroup const &rhs) const
Overload <= operator.
bool operator>= (SymmetryFunctionGroup const &rhs) const
Overload >= operator.
bool addMember (SymmetryFunction const *const symmetryFunction)
Potentially add a member to group.
void sortMembers ()
Sort member symmetry functions.
void setScalingFactors ()
Fill scalingFactors with values from member symmetry functions.
void calculate (Atom &atom, bool const derivatives) const
Calculate all symmetry functions of this group for one atom.
std::vector< std::string > parameterLines () const
Give symmetry function group parameters on multiple lines.
Public Member Functions inherited from nnp::SymmetryFunctionGroup
virtual ~SymmetryFunctionGroup ()
Virtual destructor.
void setIndex (std::size_t index)
Set private index member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getType () const
Get private type member variable.
std::size_t getEc () const
Get private ec member variable.
Private Attributes
std::size_t e1
Element index of neighbor atom (common feature).
std::vector< SymmetryFunctionRadial const * > members
Vector of all group member pointers.
std::vector< double > eta
Vector containing values of all member symmetry functions.
std::vector< double > rs
Vector containing values of all member symmetry functions.
Additional Inherited Members
Protected Types inherited from nnp::SymmetryFunctionGroup
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymmetryFunctionGroup
SymmetryFunctionGroup (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
std::string getPrintFormatCommon () const
Get common parameter line format string.
std::string getPrintFormatMember () const
Get member parameter line format string.
Static Protected Member Functions inherited from nnp::SymmetryFunctionGroup
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymmetryFunctionGroup
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function group index.
std::size_t ec
Element index of center atom (common feature).
double rc
Cutoff radius (common feature).
double cutoffAlpha
Cutoff function parameter (common feature).
double convLength
Data set normalization length conversion factor.
CutoffFunction fc
Cutoff function used by this symmetry function group.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function group (common feature).
std::vector< size_t > memberIndex
Vector containing indices of all member symmetry functions.
std::vector< double > scalingFactors
Scaling factors of all member symmetry functions.
std::set< std::string > parametersCommon
Set of common parameters IDs.
std::set< std::string > parametersMember
Set of common parameters IDs.
std::vector< std::vector< std::size_t > > memberIndexPerElement
Vector containing per-element indices of all member symmetry functions.
Static Protected Attributes inherited from nnp::SymmetryFunctionGroup
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Radial symmetry function group (type 2)
Common features:
element of central atom
element of neighbor atom
cutoff type
Definition at line 46 of file SymmetryFunctionGroupRadial.h.
Constructor & Destructor Documentation
SymmetryFunctionGroupRadial()
SymmetryFunctionGroupRadial::SymmetryFunctionGroupRadial (ElementMap const & elementMap)
Constructor, sets type = 2.
Definition at line 31 of file SymmetryFunctionGroupRadial.cpp.
References operator==(), nnp::SymmetryFunctionGroup::parametersCommon, and nnp::SymmetryFunctionGroup::parametersMember.
                                                           :
     SymmetryFunctionGroup(2, elementMap),
     e1(0)
 {
     parametersCommon.insert("e1");
     parametersMember.insert("eta");
     parametersMember.insert("rs");
     parametersMember.insert("mindex");
     parametersMember.insert("sfindex");
 }
Member Function Documentation
operator==()
bool SymmetryFunctionGroupRadial::operator== (SymmetryFunctionGroup const & rhs) const virtual
Overload == operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 44 of file SymmetryFunctionGroupRadial.cpp.
References nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffType, e1, nnp::SymmetryFunctionGroup::ec, nnp::SymmetryFunctionGroup::getEc(), nnp::SymmetryFunctionGroup::getType(), operator<(), nnp::SymmetryFunctionGroup::rc, and nnp::SymmetryFunctionGroup::type.
Referenced by SymmetryFunctionGroupRadial().
 {
     if (ec   != rhs.getEc()  ) return false;
     if (type != rhs.getType()) return false;
     SymmetryFunctionGroupRadial const& c =
         dynamic_cast<SymmetryFunctionGroupRadial const&>(rhs);
     if (cutoffType  != c.cutoffType ) return false;
     if (cutoffAlpha != c.cutoffAlpha) return false;
     if (rc          != c.rc         ) return false;
     if (e1          != c.e1         ) return false;
     return true;
 }
operator!=()
bool nnp::SymmetryFunctionGroupRadial::operator!= (SymmetryFunctionGroup const & rhs) const inline virtual
Overload != operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 117 of file SymmetryFunctionGroupRadial.h.
References operator>().
 {
     return !((*this) == rhs);
 }
operator<()
bool SymmetryFunctionGroupRadial::operator< (SymmetryFunctionGroup const & rhs) const virtual
Overload < operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 58 of file SymmetryFunctionGroupRadial.cpp.
References addMember(), nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffType, e1, nnp::SymmetryFunctionGroup::ec, nnp::SymmetryFunctionGroup::getEc(), nnp::SymmetryFunctionGroup::getType(), nnp::SymmetryFunctionGroup::rc, and nnp::SymmetryFunctionGroup::type.
Referenced by operator==().
 {
     if      (ec   < rhs.getEc()  ) return true;
     else if (ec   > rhs.getEc()  ) return false;
     if      (type < rhs.getType()) return true;
     else if (type > rhs.getType()) return false;
     SymmetryFunctionGroupRadial const& c =
         dynamic_cast<SymmetryFunctionGroupRadial const&>(rhs);
     if      (cutoffType  < c.cutoffType ) return true;
     else if (cutoffType  > c.cutoffType ) return false;
     if      (cutoffAlpha < c.cutoffAlpha) return true;
     else if (cutoffAlpha > c.cutoffAlpha) return false;
     if      (rc          < c.rc         ) return true;
     else if (rc          > c.rc         ) return false;
     if      (e1          < c.e1         ) return true;
     else if (e1          > c.e1         ) return false;
     return false;
 }
operator>()
bool nnp::SymmetryFunctionGroupRadial::operator> (SymmetryFunctionGroup const & rhs) const inline virtual
Overload > operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 123 of file SymmetryFunctionGroupRadial.h.
References operator<=().
Referenced by operator!=().
 {
     return rhs < (*this);
 }
operator<=()
bool nnp::SymmetryFunctionGroupRadial::operator<= (SymmetryFunctionGroup const & rhs) const inline virtual
Overload <= operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 129 of file SymmetryFunctionGroupRadial.h.
References operator>=().
Referenced by operator>().
 {
     return !((*this) > rhs);
 }
operator>=()
bool nnp::SymmetryFunctionGroupRadial::operator>= (SymmetryFunctionGroup const & rhs) const inline virtual
Overload >= operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 135 of file SymmetryFunctionGroupRadial.h.
Referenced by operator<=().
 {
     return !((*this) < rhs);
 }
addMember()
bool SymmetryFunctionGroupRadial::addMember (SymmetryFunction const *const symmetryFunction) virtual
Potentially add a member to group.
Parameters
[in] symmetryFunction Candidate symmetry function.
Returns
If addition was successful.
If symmetry function is compatible with common feature list its pointer will be added to members.
Implements nnp::SymmetryFunctionGroup.
Definition at line 78 of file SymmetryFunctionGroupRadial.cpp.
References nnp::SymmetryFunctionGroup::convLength, nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffType, e1, nnp::SymmetryFunctionGroup::ec, nnp::SymmetryFunctionGroup::fc, nnp::SymmetryFunction::getConvLength(), nnp::SymmetryFunction::getCutoffAlpha(), nnp::SymmetryFunction::getCutoffType(), nnp::SymmetryFunctionRadial::getE1(), nnp::SymmetryFunction::getEc(), nnp::SymmetryFunction::getRc(), nnp::SymmetryFunction::getType(), members, nnp::SymmetryFunctionGroup::rc, nnp::CutoffFunction::setCutoffParameter(), nnp::CutoffFunction::setCutoffRadius(), nnp::CutoffFunction::setCutoffType(), and nnp::SymmetryFunctionGroup::type.
Referenced by operator<().
 {
     if (symmetryFunction->getType() != type) return false;
     SymmetryFunctionRadial const* sf =
         dynamic_cast<SymmetryFunctionRadial const*>(symmetryFunction);
     if (members.empty())
     {
         cutoffType  = sf->getCutoffType();
         cutoffAlpha = sf->getCutoffAlpha();
         ec          = sf->getEc();
         rc          = sf->getRc();
         e1          = sf->getE1();
         convLength  = sf->getConvLength();
         fc.setCutoffType(cutoffType);
         fc.setCutoffRadius(rc);
         fc.setCutoffParameter(cutoffAlpha);
     }
     if (sf->getCutoffType()  != cutoffType ) return false;
     if (sf->getCutoffAlpha() != cutoffAlpha) return false;
     if (sf->getEc()          != ec         ) return false;
     if (sf->getRc()          != rc         ) return false;
     if (sf->getE1()          != e1         ) return false;
     if (sf->getConvLength()  != convLength )
     {
         throw runtime_error("ERROR: Unable to add symmetry function members "
                             "with different conversion factors.\n");
     }
     members.push_back(sf);
     return true;
 }
sortMembers()
void SymmetryFunctionGroupRadial::sortMembers () virtual
Sort member symmetry functions.
Also allocate and precalculate additional stuff.
Implements nnp::SymmetryFunctionGroup.
Definition at line 115 of file SymmetryFunctionGroupRadial.cpp.
References eta, nnp::SymmetryFunctionGroup::getIndex(), nnp::SymmetryFunctionGroup::memberIndex, nnp::SymmetryFunctionGroup::memberIndexPerElement, members, and rs.
 {
     sort(members.begin(),
          members.end(),
          comparePointerTargets<SymmetryFunctionRadial const>);
     for (size_t i = 0; i < members.size(); i++)
     {
         memberIndex.push_back(members[i]->getIndex());
         eta.push_back(members[i]->getEta());
         rs.push_back(members[i]->getRs());
         memberIndexPerElement.push_back(members[i]->getIndexPerElement());
     }
     return;
 }
setScalingFactors()
void SymmetryFunctionGroupRadial::setScalingFactors () virtual
Fill scalingFactors with values from member symmetry functions.
Implements nnp::SymmetryFunctionGroup.
Definition at line 132 of file SymmetryFunctionGroupRadial.cpp.
References members, and nnp::SymmetryFunctionGroup::scalingFactors.
 {
     scalingFactors.resize(members.size(), 0.0);
     for (size_t i = 0; i < members.size(); i++)
     {
         scalingFactors.at(i) = members[i]->getScalingFactor();
     }
     return;
 }
calculate()
void SymmetryFunctionGroupRadial::calculate (Atom & atom, bool const derivatives) const virtual
Calculate all symmetry functions of this group for one atom.
Parameters
[in,out] atom Atom for which symmetry functions are caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymmetryFunctionGroup.
Definition at line 149 of file SymmetryFunctionGroupRadial.cpp.
References nnp::Atom::Neighbor::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::Atom::Neighbor::cutoffType, nnp::SymmetryFunctionGroup::cutoffType, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dfc, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, e1, nnp::Atom::Neighbor::element, eta, nnp::Atom::Neighbor::fc, nnp::SymmetryFunctionGroup::fc, nnp::CutoffFunction::fdf(), nnp::Atom::G, nnp::SymmetryFunctionGroup::memberIndex, nnp::SymmetryFunctionGroup::memberIndexPerElement, members, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::Vec3D::r, nnp::Atom::Neighbor::rc, nnp::SymmetryFunctionGroup::rc, rs, and nnp::SymmetryFunctionGroup::scalingFactors.
 {
     double* result = new double[members.size()];
     for (size_t k = 0; k < members.size(); ++k)
     {
         result[k] = 0.0;
     }
     for (size_t j = 0; j < atom.numNeighbors; ++j)
     {
         Atom::Neighbor& n = atom.neighbors[j];
         if (e1 == n.element && n.d < rc)
         {
             // Energy calculation.
             double const rij = n.d;
             // Calculate cutoff function and derivative.
 #ifdef NOCFCACHE
             double pfc;
             double pdfc;
             fc.fdf(rij, pfc, pdfc);
 #else
             // If cutoff radius matches with the one in the neighbor storage
             // we can use the previously calculated value.
             double& pfc = n.fc;
             double& pdfc = n.dfc;
             if (n.cutoffType != cutoffType ||
                 n.rc != rc ||
                 n.cutoffAlpha != cutoffAlpha)
             {
                 fc.fdf(rij, pfc, pdfc);
                 n.rc = rc;
                 n.cutoffType = cutoffType;
                 n.cutoffAlpha = cutoffAlpha;
             }
 #endif
             double const* const d1 = n.dr.r;
             for (size_t k = 0; k < members.size(); ++k)
             {
                 double pexp = exp(-eta[k] * (rij - rs[k]) * (rij - rs[k]));
                 result[k] += pexp * pfc;
                 // Force calculation.
                 if (!derivatives) continue;
                 double const p1 = scalingFactors[k] * (pdfc - 2.0 * eta[k]
                                 * (rij - rs[k]) * pfc) * pexp / rij;
                 // SIMPLE EXPRESSIONS:
                 //Vec3D const dij = p1 * atom.neighbors[j].dr;
                 double const p1drijx = p1 * d1[0];
                 double const p1drijy = p1 * d1[1];
                 double const p1drijz = p1 * d1[2];
                 // Save force contributions in Atom storage.
 #ifdef IMPROVED_SFD_MEMORY
                 size_t ki = memberIndex[k];
 #else
                 size_t const ki = memberIndex[k];
 #endif
                 // SIMPLE EXPRESSIONS:
                 //atom.dGdr[ki]              += dij;
                 //atom.neighbors[j].dGdr[ki] -= dij;
                 double* dGdr = atom.dGdr[ki].r;
                 dGdr[0] += p1drijx;
                 dGdr[1] += p1drijy;
                 dGdr[2] += p1drijz;
 #ifdef IMPROVED_SFD_MEMORY
                 ki = memberIndexPerElement[k][e1];
 #endif
                 dGdr = n.dGdr[ki].r;
                 dGdr[0] -= p1drijx;
                 dGdr[1] -= p1drijy;
                 dGdr[2] -= p1drijz;
             }
         }
     }
     for (size_t k = 0; k < members.size(); ++k)
     {
         atom.G[memberIndex[k]] = members[k]->scale(result[k]);
     }
     delete[] result;
     return;
 }
parameterLines()
vector< string > SymmetryFunctionGroupRadial::parameterLines () const virtual
Give symmetry function group parameters on multiple lines.
Returns
Vector of string containing symmetry function parameters lines.
Implements nnp::SymmetryFunctionGroup.
Definition at line 237 of file SymmetryFunctionGroupRadial.cpp.
References nnp::SymmetryFunctionGroup::convLength, nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffType, e1, nnp::SymmetryFunctionGroup::ec, nnp::SymmetryFunctionGroup::elementMap, nnp::SymmetryFunctionGroup::getIndex(), nnp::SymmetryFunctionGroup::getPrintFormatCommon(), nnp::SymmetryFunctionGroup::getPrintFormatMember(), nnp::SymmetryFunctionGroup::index, members, nnp::SymmetryFunctionGroup::rc, nnp::strpr(), and nnp::SymmetryFunctionGroup::type.
 {
     vector<string> v;
     v.push_back(strpr(getPrintFormatCommon().c_str(),
                       index + 1,
                       elementMap[ec].c_str(),
                       type,
                       elementMap[e1].c_str(),
                       rc / convLength,
                       (int)cutoffType,
                       cutoffAlpha));
     for (size_t i = 0; i < members.size(); ++i)
     {
         v.push_back(strpr(getPrintFormatMember().c_str(),
                           members[i]->getEta() * convLength * convLength,
                           members[i]->getRs() / convLength,
                           members[i]->getLineNumber(),
                           i + 1,
                           members[i]->getIndex() + 1));
     }
     return v;
 }
Member Data Documentation
e1
std::size_t nnp::SymmetryFunctionGroupRadial::e1 private
Element index of neighbor atom (common feature).
Definition at line 103 of file SymmetryFunctionGroupRadial.h.
Referenced by addMember(), calculate(), operator<(), operator==(), and parameterLines().
members
std::vector<SymmetryFunctionRadial const*> nnp::SymmetryFunctionGroupRadial::members private
Vector of all group member pointers.
Definition at line 105 of file SymmetryFunctionGroupRadial.h.
Referenced by addMember(), calculate(), parameterLines(), setScalingFactors(), and sortMembers().
eta
std::vector<double> nnp::SymmetryFunctionGroupRadial::eta private
Vector containing values of all member symmetry functions.
Definition at line 107 of file SymmetryFunctionGroupRadial.h.
Referenced by calculate(), and sortMembers().
rs
std::vector<double> nnp::SymmetryFunctionGroupRadial::rs private
Vector containing values of all member symmetry functions.
Definition at line 109 of file SymmetryFunctionGroupRadial.h.
Referenced by calculate(), and sortMembers().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunctionGroupRadial.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunctionGroupRadial.cpp