n2p2 - A neural network potential package: nnp::SymmetryFunction Class Reference
nnp::SymmetryFunction Class Reference abstract
Symmetry function base class.
#include <SymmetryFunction.h>
Public Types
enum ScalingType {
ST_NONE, ST_SCALE, ST_CENTER, ST_SCALECENTER,
ST_SCALESIGMA
}
List of available scaling types.
Public Member Functions
virtual ~SymmetryFunction ()
Virtual destructor.
virtual bool operator== (SymmetryFunction const &rhs) const =0
Overload == operator.
virtual bool operator!= (SymmetryFunction const &rhs) const =0
Overload != operator.
virtual bool operator< (SymmetryFunction const &rhs) const =0
Overload < operator.
virtual bool operator> (SymmetryFunction const &rhs) const =0
Overload > operator.
virtual bool operator<= (SymmetryFunction const &rhs) const =0
Overload <= operator.
virtual bool operator>= (SymmetryFunction const &rhs) const =0
Overload >= operator.
virtual void setParameters (std::string const &parameterString)=0
Set parameters.
virtual void changeLengthUnit (double convLength)=0
Change length unit.
virtual std::string getSettingsLine () const =0
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate symmetry function for one atom.
virtual std::string parameterLine () const =0
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setCutoffFunction (CutoffFunction::CutoffType cutoffType, double cutoffAlpha)
Set cutoff function type and parameter.
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
double scale (double value) const
Apply symmetry function scaling and/or centering.
double unscale (double value) const
Undo symmetry function scaling and/or centering.
std::size_t getType () const
Get private type member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getLineNumber () const
Get private lineNumber member variable.
std::size_t getEc () const
Get private ec member variable.
std::size_t getMinNeighbors () const
Get private minNeighbors member variable.
double getRc () const
Get private rc member variable.
double getGmin () const
Get private Gmin member variable.
double getGmax () const
Get private Gmax member variable.
double getScalingFactor () const
Get private scalingFactor member variable.
double getCutoffAlpha () const
Get private cutoffAlpha member variable.
double getConvLength () const
Get private convLength member variable.
CutoffFunction::CutoffType getCutoffType () const
Get private cutoffType member variable.
std::set< std::string > getParameters () const
Get private parameters member variable.
std::vector< std::size_t > getIndexPerElement () const
Get private indexPerElement member variable.
void setIndex (std::size_t index)
Set private index member variable.
void setIndexPerElement (std::size_t elementIndex, std::size_t index)
Set private indexPerElement member variable.
void setLineNumber (std::size_t lineNumber)
Set line number.
std::string scalingLine () const
Get string with scaling information.
virtual double calculateRadialPart (double distance) const =0
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const =0
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const =0
Check whether symmetry function is relevant for given element.
Protected Types
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions
SymmetryFunction (std::size_t type, ElementMap const &)
Constructor, initializes type.
std::string getPrintFormat () const
Generate format string for symmetry function parameter printing.
Static Protected Member Functions
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function index (per element).
std::size_t lineNumber
Line number.
std::size_t ec
Element index of center atom.
std::size_t minNeighbors
Minimum number of neighbors required.
double Smin
Minimum for scaling range.
double Smax
Maximum for scaling range.
double Gmin
Minimum unscaled symmetry function value.
double Gmax
Maximum unscaled symmetry function value.
double Gmean
Mean unscaled symmetry function value.
double Gsigma
Sigma of unscaled symmetry function values.
double rc
Cutoff radius .
double scalingFactor
Scaling factor.
double cutoffAlpha
Cutoff parameter .
double convLength
Data set normalization length conversion factor.
CutoffFunction fc
Cutoff function used by this symmetry function.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function.
ScalingType scalingType
Symmetry function scaling type used by this symmetry function.
std::set< std::string > parameters
Set with symmetry function parameter IDs (lookup for printing).
std::vector< std::size_t > indexPerElement
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
Static Protected Attributes
static std::size_t const sfinfoWidth = 12
Width of the SFINFO parameter description field (see parameterInfo()).
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Symmetry function base class.
Actual symmetry functions derive from this class. Provides common functionality, e.g. scaling behavior.
Definition at line 40 of file SymmetryFunction.h.
Member Typedef Documentation
PrintFormat
typedef std::map<std::string, std::pair<std::string, std::string> > nnp::SymmetryFunction::PrintFormat protected
Definition at line 261 of file SymmetryFunction.h.
PrintOrder
typedef std::vector<std::string> nnp::SymmetryFunction::PrintOrder protected
Definition at line 262 of file SymmetryFunction.h.
Member Enumeration Documentation
ScalingType
enum nnp::SymmetryFunction::ScalingType
List of available scaling types.
Enumerator
ST_NONE
ST_SCALE
ST_CENTER
ST_SCALECENTER
ST_SCALESIGMA
Definition at line 44 of file SymmetryFunction.h.
     {
         ST_NONE,
         ST_SCALE,
         ST_CENTER,
         ST_SCALECENTER,
         ST_SCALESIGMA
     };
Constructor & Destructor Documentation
~SymmetryFunction()
virtual nnp::SymmetryFunction::~SymmetryFunction () inline virtual
Virtual destructor.
Definition at line 70 of file SymmetryFunction.h.
References calculate(), calculateAngularPart(), calculateRadialPart(), changeLengthUnit(), checkRelevantElement(), convLength, cutoffAlpha, cutoffType, getConvLength(), getCutoffAlpha(), getCutoffType(), getEc(), getGmax(), getGmin(), getIndex(), getIndexPerElement(), getLineNumber(), getMinNeighbors(), getParameters(), getRc(), getScalingFactor(), getSettingsLine(), getType(), index, lineNumber, operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), parameterInfo(), parameterLine(), scale(), scalingLine(), scalingType, setCutoffFunction(), setIndex(), setIndexPerElement(), setLineNumber(), setParameters(), setScalingType(), Smax, Smin, and unscale().
 {};
SymmetryFunction()
SymmetryFunction::SymmetryFunction (std::size_t type, ElementMap const &) protected
Constructor, initializes type.
Definition at line 121 of file SymmetryFunction.cpp.
References indexPerElement, parameters, and nnp::ElementMap::size().
                                                                             :
     type         (type                   ),
     elementMap   (elementMap             ),
     index        (0                      ),
     ec           (0                      ),
     minNeighbors (0                      ),
     Smin         (0.0                    ),
     Smax         (0.0                    ),
     Gmin         (0.0                    ),
     Gmax         (0.0                    ),
     Gmean        (0.0                    ),
     Gsigma       (0.0                    ),
     rc           (0.0                    ),
     scalingFactor(1.0                    ),
     cutoffAlpha  (0.0                    ),
     convLength   (1.0                    ),
     cutoffType   (CutoffFunction::CT_HARD),
     scalingType  (ST_NONE                )
 {
     // Add standard parameter IDs to set.
     parameters.insert("index");
     parameters.insert("ec");
     parameters.insert("type");
     parameters.insert("rc");
     parameters.insert("cutoffType");
     parameters.insert("cutoffAlpha");
     parameters.insert("lineNumber");
     // Initialize per-element index vector, use max to indicate
     // "uninitialized" state.
     indexPerElement.resize(elementMap.size(), numeric_limits<size_t>::max());
 }
Member Function Documentation
operator==()
virtual bool nnp::SymmetryFunction::operator== (SymmetryFunction const & rhs) const pure virtual
Overload == operator.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
operator!=()
virtual bool nnp::SymmetryFunction::operator!= (SymmetryFunction const & rhs) const pure virtual
Overload != operator.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
operator<()
virtual bool nnp::SymmetryFunction::operator< (SymmetryFunction const & rhs) const pure virtual
Overload < operator.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
operator>()
virtual bool nnp::SymmetryFunction::operator> (SymmetryFunction const & rhs) const pure virtual
Overload > operator.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
operator<=()
virtual bool nnp::SymmetryFunction::operator<= (SymmetryFunction const & rhs) const pure virtual
Overload <= operator.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
operator>=()
virtual bool nnp::SymmetryFunction::operator>= (SymmetryFunction const & rhs) const pure virtual
Overload >= operator.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
setParameters()
virtual void nnp::SymmetryFunction::setParameters (std::string const & parameterString) pure virtual
Set parameters.
Parameters
[in] parameterString String containing all parameters for this symmetry function.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
changeLengthUnit()
virtual void nnp::SymmetryFunction::changeLengthUnit (double convLength) pure virtual
Change length unit.
Parameters
[in] convLength Multiplicative length unit conversion factor.
Note
This will permanently change all symmetry function parameters with dimension length. For convenience, some member functions for printing (getSettingsLine(), parameterLine(), calculateRadialPart() and calculateAngularPart()) will temporarily undo this change. In contrast, the member getter functions, e.g. getRc(), will return the internally stored values.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
getSettingsLine()
virtual std::string nnp::SymmetryFunction::getSettingsLine () const pure virtual
Get settings file line from currently set parameters.
Returns
Settings file string ("symfunction_short ...").
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
calculate()
virtual void nnp::SymmetryFunction::calculate (Atom & atom, bool const derivatives) const pure virtual
Calculate symmetry function for one atom.
Parameters
[in,out] atom Atom for which the symmetry function is caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
parameterLine()
virtual std::string nnp::SymmetryFunction::parameterLine () const pure virtual
Give symmetry function parameters in one line.
Returns
String containing symmetry function parameter values.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by nnp::Mode::setupSymmetryFunctionMemory(), and ~SymmetryFunction().
parameterInfo()
vector< string > SymmetryFunction::parameterInfo () const virtual
Get description with parameter names and values.
Returns
Vector of parameter description strings.
Reimplemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Definition at line 37 of file SymmetryFunction.cpp.
References nnp::pad(), and nnp::strpr().
Referenced by nnp::SymmetryFunctionRadial::parameterInfo(), nnp::SymmetryFunctionWeightedRadial::parameterInfo(), nnp::SymmetryFunctionWeightedAngular::parameterInfo(), nnp::SymmetryFunctionAngularWide::parameterInfo(), nnp::SymmetryFunctionAngularNarrow::parameterInfo(), and ~SymmetryFunction().
 {
     vector<string> v;
     string s;
     size_t w = sfinfoWidth;
     s = "lineNumber";
     v.push_back(strpr((pad(s, w) + "%zu"   ).c_str(), lineNumber + 1));
     s = "index";
     v.push_back(strpr((pad(s, w) + "%zu"   ).c_str(), index + 1));
     s = "type";
     v.push_back(strpr((pad(s, w) + "%zu"   ).c_str(), type));
     s = "ec";
     v.push_back(strpr((pad(s, w) + "%s"    ).c_str(), elementMap[ec].c_str()));
     s = "rc";
     v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), rc / convLength));
     s = "cutoffType";
     v.push_back(strpr((pad(s, w) + "%d"    ).c_str(), (int)cutoffType));
     s = "cutoffAlpha";
     v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), cutoffAlpha));
     return v;
 }
setCutoffFunction()
void SymmetryFunction::setCutoffFunction (CutoffFunction::CutoffType cutoffType, double cutoffAlpha)
Set cutoff function type and parameter.
Parameters
[in] cutoffType Desired cutoff function for this symmetry function.
[in] cutoffAlpha Cutoff function parameter .
Definition at line 61 of file SymmetryFunction.cpp.
References fc, nnp::CutoffFunction::setCutoffParameter(), and nnp::CutoffFunction::setCutoffType().
Referenced by ~SymmetryFunction().
 {
     this->cutoffType = cutoffType;
     this->cutoffAlpha = cutoffAlpha;
     fc.setCutoffType(cutoffType);
     fc.setCutoffParameter(cutoffAlpha);
     return;
 }
setScalingType()
void SymmetryFunction::setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
Parameters
[in] scalingType Desired symmetry function scaling type.
[in] statisticsLine String containing symmetry function statistics ("min max mean sigma").
[in] Smin Minimum for scaling range .
[in] Smax Maximum for scaling range .
Definition at line 73 of file SymmetryFunction.cpp.
References nnp::reduce(), and nnp::split().
Referenced by ~SymmetryFunction().
 {
     this->scalingType = scalingType;
     vector<string> s = split(reduce(statisticsLine));
     if (((size_t)atoi(s.at(0).c_str()) != ec + 1) &&
         ((size_t)atoi(s.at(1).c_str()) != index + 1))
     {
         throw runtime_error("ERROR: Inconsistent scaling statistics.\n");
     }
     Gmin       = atof(s.at(2).c_str());
     Gmax       = atof(s.at(3).c_str());
     Gmean      = atof(s.at(4).c_str());
     // Older versions may not supply sigma.
     if (s.size() > 5)
     {
         Gsigma = atof(s.at(5).c_str());
     }
     this->Smin = Smin;
     this->Smax = Smax;
     if(scalingType == ST_NONE)
     {
         scalingFactor = 1.0;
     }
     else if (scalingType == ST_SCALE)
     {
         scalingFactor = (Smax - Smin) / (Gmax - Gmin);
     }
     else if (scalingType == ST_CENTER)
     {
         scalingFactor = 1.0;
     }
     else if (scalingType == ST_SCALECENTER)
     {
         scalingFactor = (Smax - Smin) / (Gmax - Gmin);
     }
     else if (scalingType == ST_SCALESIGMA)
     {
         scalingFactor = (Smax - Smin) / Gsigma;
     }
     return;
 }
scale()
double SymmetryFunction::scale (double value) const
Apply symmetry function scaling and/or centering.
Parameters
[in] value Raw symmetry function value.
Returns
Scaled symmetry function value.
Definition at line 154 of file SymmetryFunction.cpp.
References Gmean, Gmin, scalingFactor, scalingType, Smin, ST_CENTER, ST_NONE, ST_SCALE, ST_SCALECENTER, and ST_SCALESIGMA.
Referenced by nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), and ~SymmetryFunction().
 {
     if (scalingType == ST_NONE)
     {
         return value;
     }
     else if (scalingType == ST_SCALE)
     {
         return Smin + scalingFactor * (value - Gmin);
     }
     else if (scalingType == ST_CENTER)
     {
         return value - Gmean;
     }
     else if (scalingType == ST_SCALECENTER)
     {
         return Smin + scalingFactor * (value - Gmean);
     }
     else if (scalingType == ST_SCALESIGMA)
     {
         return Smin + scalingFactor * (value - Gmean);
     }
     else
     {
         return 0.0;
     }
 }
unscale()
double SymmetryFunction::unscale (double value) const
Undo symmetry function scaling and/or centering.
Parameters
[in] value Scaled symmetry function value.
Returns
Raw symmetry function value.
Definition at line 182 of file SymmetryFunction.cpp.
References Gmean, Gmin, scalingFactor, scalingType, Smin, ST_CENTER, ST_NONE, ST_SCALE, ST_SCALECENTER, and ST_SCALESIGMA.
Referenced by ~SymmetryFunction().
 {
     if (scalingType == ST_NONE)
     {
         return value;
     }
     else if (scalingType == ST_SCALE)
     {
         return (value - Smin) / scalingFactor + Gmin;
     }
     else if (scalingType == ST_CENTER)
     {
         return value + Gmean;
     }
     else if (scalingType == ST_SCALECENTER)
     {
         return (value - Smin) / scalingFactor + Gmean;
     }
     else if (scalingType == ST_SCALESIGMA)
     {
         return (value - Smin) / scalingFactor + Gmean;
     }
     else
     {
         return 0.0;
     }
 }
getType()
std::size_t nnp::SymmetryFunction::getType () const inline
Get private type member variable.
Definition at line 332 of file SymmetryFunction.h.
References type.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), nnp::SymmetryFunctionWeightedRadial::operator<(), nnp::SymmetryFunctionRadial::operator<(), nnp::SymmetryFunctionWeightedAngular::operator<(), nnp::SymmetryFunctionAngularWide::operator<(), nnp::SymmetryFunctionAngularNarrow::operator<(), nnp::SymmetryFunctionWeightedRadial::operator==(), nnp::SymmetryFunctionRadial::operator==(), nnp::SymmetryFunctionAngularWide::operator==(), nnp::SymmetryFunctionWeightedAngular::operator==(), nnp::SymmetryFunctionAngularNarrow::operator==(), and ~SymmetryFunction().
 {
     return type;
 }
getIndex()
std::size_t nnp::SymmetryFunction::getIndex () const inline
Get private index member variable.
Definition at line 342 of file SymmetryFunction.h.
References index.
Referenced by nnp::Mode::setupSymmetryFunctionMemory(), nnp::SetupAnalysis::writeSymmetryFunctionShape(), and ~SymmetryFunction().
 {
     return index;
 }
getLineNumber()
std::size_t nnp::SymmetryFunction::getLineNumber () const inline
Get private lineNumber member variable.
Definition at line 347 of file SymmetryFunction.h.
References lineNumber.
Referenced by ~SymmetryFunction().
 {
     return lineNumber;
 }
getEc()
std::size_t nnp::SymmetryFunction::getEc () const inline
Get private ec member variable.
Definition at line 337 of file SymmetryFunction.h.
References ec.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), nnp::SymmetryFunctionWeightedRadial::operator<(), nnp::SymmetryFunctionRadial::operator<(), nnp::SymmetryFunctionWeightedAngular::operator<(), nnp::SymmetryFunctionAngularWide::operator<(), nnp::SymmetryFunctionAngularNarrow::operator<(), nnp::SymmetryFunctionWeightedRadial::operator==(), nnp::SymmetryFunctionRadial::operator==(), nnp::SymmetryFunctionAngularWide::operator==(), nnp::SymmetryFunctionWeightedAngular::operator==(), nnp::SymmetryFunctionAngularNarrow::operator==(), and ~SymmetryFunction().
 {
     return ec;
 }
getMinNeighbors()
std::size_t nnp::SymmetryFunction::getMinNeighbors () const inline
Get private minNeighbors member variable.
Definition at line 352 of file SymmetryFunction.h.
References minNeighbors.
Referenced by ~SymmetryFunction().
 {
     return minNeighbors;
 }
getRc()
double nnp::SymmetryFunction::getRc () const inline
Get private rc member variable.
Definition at line 357 of file SymmetryFunction.h.
References rc.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), and ~SymmetryFunction().
 {
     return rc;
 }
getGmin()
double nnp::SymmetryFunction::getGmin () const inline
Get private Gmin member variable.
Definition at line 362 of file SymmetryFunction.h.
References Gmin.
Referenced by nnp::Mode::pruneSymmetryFunctionsRange(), and ~SymmetryFunction().
 {
     return Gmin;
 }
getGmax()
double nnp::SymmetryFunction::getGmax () const inline
Get private Gmax member variable.
Definition at line 367 of file SymmetryFunction.h.
References Gmax.
Referenced by nnp::Mode::pruneSymmetryFunctionsRange(), and ~SymmetryFunction().
 {
     return Gmax;
 }
getScalingFactor()
double nnp::SymmetryFunction::getScalingFactor () const inline
Get private scalingFactor member variable.
Definition at line 372 of file SymmetryFunction.h.
References scalingFactor.
Referenced by ~SymmetryFunction().
 {
     return scalingFactor;
 }
getCutoffAlpha()
double nnp::SymmetryFunction::getCutoffAlpha () const inline
Get private cutoffAlpha member variable.
Definition at line 377 of file SymmetryFunction.h.
References cutoffAlpha.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), and ~SymmetryFunction().
 {
     return cutoffAlpha;
 }
getConvLength()
double nnp::SymmetryFunction::getConvLength () const inline
Get private convLength member variable.
Definition at line 382 of file SymmetryFunction.h.
References convLength.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), and ~SymmetryFunction().
 {
     return convLength;
 }
getCutoffType()
CutoffFunction::CutoffType nnp::SymmetryFunction::getCutoffType () const inline
Get private cutoffType member variable.
Definition at line 399 of file SymmetryFunction.h.
References cutoffType.
Referenced by nnp::SymmetryFunctionGroupWeightedRadial::addMember(), nnp::SymmetryFunctionGroupRadial::addMember(), nnp::SymmetryFunctionGroupWeightedAngular::addMember(), nnp::SymmetryFunctionGroupAngularWide::addMember(), nnp::SymmetryFunctionGroupAngularNarrow::addMember(), and ~SymmetryFunction().
 {
     return cutoffType;
 }
getParameters()
std::set< std::string > nnp::SymmetryFunction::getParameters () const inline
Get private parameters member variable.
Definition at line 404 of file SymmetryFunction.h.
References parameters.
Referenced by ~SymmetryFunction().
 {
     return parameters;
 }
getIndexPerElement()
std::vector< std::size_t > nnp::SymmetryFunction::getIndexPerElement () const inline
Get private indexPerElement member variable.
Definition at line 409 of file SymmetryFunction.h.
References indexPerElement.
Referenced by nnp::Mode::setupSymmetryFunctionMemory(), and ~SymmetryFunction().
 {
     return indexPerElement;
 }
setIndex()
void nnp::SymmetryFunction::setIndex (std::size_t index) inline
Set private index member variable.
Parameters
[in] index Symmetry function index.
Definition at line 387 of file SymmetryFunction.h.
References index.
Referenced by ~SymmetryFunction().
 {
     this->index = index;
     return;
 }
setIndexPerElement()
void nnp::SymmetryFunction::setIndexPerElement (std::size_t elementIndex, std::size_t index) inline
Set private indexPerElement member variable.
Parameters
[in] elementIndex Element index.
[in] index Symmetry function index.
Definition at line 414 of file SymmetryFunction.h.
References index, and indexPerElement.
Referenced by ~SymmetryFunction().
 {
     indexPerElement.at(elementIndex) = index;
     return;
 }
setLineNumber()
void nnp::SymmetryFunction::setLineNumber (std::size_t lineNumber) inline
Set line number.
Parameters
[in] lineNumber Line number in settings file.
Definition at line 393 of file SymmetryFunction.h.
References lineNumber.
Referenced by ~SymmetryFunction().
 {
     this->lineNumber = lineNumber;
     return;
 }
scalingLine()
string SymmetryFunction::scalingLine () const
Get string with scaling information.
Returns
Scaling information string.
Definition at line 210 of file SymmetryFunction.cpp.
References Gmax, Gmean, Gmin, Gsigma, index, scalingFactor, scalingType, Smax, Smin, and nnp::strpr().
Referenced by ~SymmetryFunction().
 {
     return strpr("%4zu %9.2E %9.2E %9.2E %9.2E %9.2E %5.2f %5.2f %d\n",
                  index + 1,
                  Gmin,
                  Gmax,
                  Gmean,
                  Gsigma,
                  scalingFactor,
                  Smin,
                  Smax,
                  scalingType);
 }
calculateRadialPart()
virtual double nnp::SymmetryFunction::calculateRadialPart (double distance) const pure virtual
Calculate (partial) symmetry function value for one given distance.
Parameters
[in] distance Distance between two atoms.
Returns
Symmetry function value.
Note
This function is not used for actual calculations but only for plotting symmetry functions. Derived classes should implement a meaningful symmetry function value for visualization.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by nnp::SetupAnalysis::writeSymmetryFunctionShape(), and ~SymmetryFunction().
calculateAngularPart()
virtual double nnp::SymmetryFunction::calculateAngularPart (double angle) const pure virtual
Calculate (partial) symmetry function value for one given angle.
Parameters
[in] angle Angle between triplet of atoms (in radians).
Returns
Symmetry function value.
Note
This function is not used for actual calculations but only for plotting symmetry functions. Derived classes should implement a meaningful symmetry function value for visualization.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by nnp::SetupAnalysis::writeSymmetryFunctionShape(), and ~SymmetryFunction().
checkRelevantElement()
virtual bool nnp::SymmetryFunction::checkRelevantElement (std::size_t index) const pure virtual
Check whether symmetry function is relevant for given element.
Parameters
[in] index Index of given element.
Returns
True if symmetry function is sensitive to given element, false otherwise.
Implemented in nnp::SymmetryFunctionAngularNarrow, nnp::SymmetryFunctionAngularWide, nnp::SymmetryFunctionWeightedAngular, nnp::SymmetryFunctionRadial, and nnp::SymmetryFunctionWeightedRadial.
Referenced by ~SymmetryFunction().
initializePrintFormat()
SymmetryFunction::PrintFormat const SymmetryFunction::initializePrintFormat () static protected
Initialize static print format map for all possible parameters.
Definition at line 224 of file SymmetryFunction.cpp.
 {
     PrintFormat pf;
     pf["index"]       = make_pair("%4zu" , string(4, ' '));
     pf["ec"]          = make_pair("%2s"  , string(2, ' '));
     pf["type"]        = make_pair("%2zu" , string(2, ' '));
     pf["e1"]          = make_pair("%2s"  , string(2, ' '));
     pf["e2"]          = make_pair("%2s"  , string(2, ' '));
     pf["eta"]         = make_pair("%9.3E", string(9, ' '));
     pf["rs"]          = make_pair("%9.3E", string(9, ' '));
     pf["lambda"]      = make_pair("%2.0f", string(2, ' '));
     pf["zeta"]        = make_pair("%4.1f", string(4, ' '));
     pf["rc"]          = make_pair("%9.3E", string(9, ' '));
     pf["cutoffType"]  = make_pair("%2d"  , string(2, ' '));
     pf["cutoffAlpha"] = make_pair("%4.2f", string(4, ' '));
     pf["lineNumber"]  = make_pair("%5zu" , string(5, ' '));
     return pf;
 }
initializePrintOrder()
SymmetryFunction::PrintOrder const SymmetryFunction::initializePrintOrder () static protected
Initialize static print order vector for all possible parameters.
Definition at line 245 of file SymmetryFunction.cpp.
 {
     vector<string> po;
     po.push_back("index"      );
     po.push_back("ec"         );
     po.push_back("type"       );
     po.push_back("e1"         );
     po.push_back("e2"         );
     po.push_back("eta"        );
     po.push_back("rs"         );
     po.push_back("lambda"     );
     po.push_back("zeta"       );
     po.push_back("rc"         );
     po.push_back("cutoffType" );
     po.push_back("cutoffAlpha");
     po.push_back("lineNumber" );
     return po;
 }
getPrintFormat()
string SymmetryFunction::getPrintFormat () const protected
Generate format string for symmetry function parameter printing.
Returns
C-Style format string.
Definition at line 266 of file SymmetryFunction.cpp.
References parameters, printFormat, printOrder, and nnp::safeFind().
Referenced by nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), and nnp::SymmetryFunctionAngularNarrow::parameterLine().
 {
     string s;
     for (PrintOrder::const_iterator it = printOrder.begin();
          it != printOrder.end(); ++it)
     {
         // If parameter is present add format string.
         if (parameters.find(*it) != parameters.end())
         {
             s += safeFind(printFormat, (*it)).first + ' ';
         }
         // Else add just enough empty spaces.
         else
         {
             s += safeFind(printFormat, (*it)).second + ' ';
         }
     }
     // Remove extra space at the end.
     if (s.size () > 0)  s.resize (s.size () - 1);
     s += '\n';
     return s;
 }
Member Data Documentation
type
std::size_t nnp::SymmetryFunction::type protected
Symmetry function type.
Definition at line 264 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::getSettingsLine(), nnp::SymmetryFunctionWeightedRadial::getSettingsLine(), nnp::SymmetryFunctionWeightedAngular::getSettingsLine(), nnp::SymmetryFunctionAngularWide::getSettingsLine(), nnp::SymmetryFunctionAngularNarrow::getSettingsLine(), getType(), nnp::SymmetryFunctionWeightedRadial::operator<(), nnp::SymmetryFunctionRadial::operator<(), nnp::SymmetryFunctionAngularWide::operator<(), nnp::SymmetryFunctionWeightedAngular::operator<(), nnp::SymmetryFunctionAngularNarrow::operator<(), nnp::SymmetryFunctionWeightedRadial::operator==(), nnp::SymmetryFunctionRadial::operator==(), nnp::SymmetryFunctionWeightedAngular::operator==(), nnp::SymmetryFunctionAngularWide::operator==(), nnp::SymmetryFunctionAngularNarrow::operator==(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), and nnp::SymmetryFunctionAngularNarrow::setParameters().
elementMap
ElementMap nnp::SymmetryFunction::elementMap protected
Copy of element map.
Definition at line 266 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionWeightedRadial::getSettingsLine(), nnp::SymmetryFunctionRadial::getSettingsLine(), nnp::SymmetryFunctionAngularWide::getSettingsLine(), nnp::SymmetryFunctionWeightedAngular::getSettingsLine(), nnp::SymmetryFunctionAngularNarrow::getSettingsLine(), nnp::SymmetryFunctionRadial::parameterInfo(), nnp::SymmetryFunctionAngularWide::parameterInfo(), nnp::SymmetryFunctionAngularNarrow::parameterInfo(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), and nnp::SymmetryFunctionAngularNarrow::setParameters().
index
std::size_t nnp::SymmetryFunction::index protected
Symmetry function index (per element).
Definition at line 268 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), getIndex(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), scalingLine(), setIndex(), setIndexPerElement(), and ~SymmetryFunction().
lineNumber
std::size_t nnp::SymmetryFunction::lineNumber protected
Line number.
Definition at line 270 of file SymmetryFunction.h.
Referenced by getLineNumber(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), setLineNumber(), and ~SymmetryFunction().
ec
std::size_t nnp::SymmetryFunction::ec protected
Element index of center atom.
Definition at line 272 of file SymmetryFunction.h.
Referenced by getEc(), nnp::SymmetryFunctionRadial::getSettingsLine(), nnp::SymmetryFunctionWeightedRadial::getSettingsLine(), nnp::SymmetryFunctionAngularWide::getSettingsLine(), nnp::SymmetryFunctionWeightedAngular::getSettingsLine(), nnp::SymmetryFunctionAngularNarrow::getSettingsLine(), nnp::SymmetryFunctionWeightedRadial::operator<(), nnp::SymmetryFunctionRadial::operator<(), nnp::SymmetryFunctionAngularWide::operator<(), nnp::SymmetryFunctionWeightedAngular::operator<(), nnp::SymmetryFunctionAngularNarrow::operator<(), nnp::SymmetryFunctionWeightedRadial::operator==(), nnp::SymmetryFunctionRadial::operator==(), nnp::SymmetryFunctionWeightedAngular::operator==(), nnp::SymmetryFunctionAngularWide::operator==(), nnp::SymmetryFunctionAngularNarrow::operator==(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), and nnp::SymmetryFunctionAngularNarrow::setParameters().
minNeighbors
std::size_t nnp::SymmetryFunction::minNeighbors protected
Minimum number of neighbors required.
Definition at line 274 of file SymmetryFunction.h.
Referenced by getMinNeighbors(), nnp::SymmetryFunctionAngularNarrow::SymmetryFunctionAngularNarrow(), nnp::SymmetryFunctionAngularWide::SymmetryFunctionAngularWide(), nnp::SymmetryFunctionRadial::SymmetryFunctionRadial(), nnp::SymmetryFunctionWeightedAngular::SymmetryFunctionWeightedAngular(), and nnp::SymmetryFunctionWeightedRadial::SymmetryFunctionWeightedRadial().
Smin
double nnp::SymmetryFunction::Smin protected
Minimum for scaling range.
Definition at line 276 of file SymmetryFunction.h.
Referenced by scale(), scalingLine(), unscale(), and ~SymmetryFunction().
Smax
double nnp::SymmetryFunction::Smax protected
Maximum for scaling range.
Definition at line 278 of file SymmetryFunction.h.
Referenced by scalingLine(), and ~SymmetryFunction().
Gmin
double nnp::SymmetryFunction::Gmin protected
Minimum unscaled symmetry function value.
Definition at line 280 of file SymmetryFunction.h.
Referenced by getGmin(), scale(), scalingLine(), and unscale().
Gmax
double nnp::SymmetryFunction::Gmax protected
Maximum unscaled symmetry function value.
Definition at line 282 of file SymmetryFunction.h.
Referenced by getGmax(), and scalingLine().
Gmean
double nnp::SymmetryFunction::Gmean protected
Mean unscaled symmetry function value.
Definition at line 284 of file SymmetryFunction.h.
Referenced by scale(), scalingLine(), and unscale().
Gsigma
double nnp::SymmetryFunction::Gsigma protected
Sigma of unscaled symmetry function values.
Definition at line 286 of file SymmetryFunction.h.
Referenced by scalingLine().
rc
double nnp::SymmetryFunction::rc protected
Cutoff radius .
Definition at line 288 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), nnp::SymmetryFunctionWeightedRadial::changeLengthUnit(), nnp::SymmetryFunctionRadial::changeLengthUnit(), nnp::SymmetryFunctionWeightedAngular::changeLengthUnit(), nnp::SymmetryFunctionAngularWide::changeLengthUnit(), nnp::SymmetryFunctionAngularNarrow::changeLengthUnit(), getRc(), nnp::SymmetryFunctionWeightedRadial::getSettingsLine(), nnp::SymmetryFunctionRadial::getSettingsLine(), nnp::SymmetryFunctionAngularWide::getSettingsLine(), nnp::SymmetryFunctionWeightedAngular::getSettingsLine(), nnp::SymmetryFunctionAngularNarrow::getSettingsLine(), nnp::SymmetryFunctionRadial::operator<(), nnp::SymmetryFunctionWeightedRadial::operator<(), nnp::SymmetryFunctionAngularWide::operator<(), nnp::SymmetryFunctionWeightedAngular::operator<(), nnp::SymmetryFunctionAngularNarrow::operator<(), nnp::SymmetryFunctionWeightedRadial::operator==(), nnp::SymmetryFunctionRadial::operator==(), nnp::SymmetryFunctionAngularWide::operator==(), nnp::SymmetryFunctionWeightedAngular::operator==(), nnp::SymmetryFunctionAngularNarrow::operator==(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), and nnp::SymmetryFunctionAngularNarrow::setParameters().
scalingFactor
double nnp::SymmetryFunction::scalingFactor protected
Scaling factor.
Definition at line 290 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), getScalingFactor(), scale(), scalingLine(), and unscale().
cutoffAlpha
double nnp::SymmetryFunction::cutoffAlpha protected
Cutoff parameter .
Definition at line 292 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), nnp::SymmetryFunctionRadial::changeLengthUnit(), nnp::SymmetryFunctionWeightedRadial::changeLengthUnit(), nnp::SymmetryFunctionAngularWide::changeLengthUnit(), nnp::SymmetryFunctionWeightedAngular::changeLengthUnit(), nnp::SymmetryFunctionAngularNarrow::changeLengthUnit(), getCutoffAlpha(), nnp::SymmetryFunctionRadial::operator<(), nnp::SymmetryFunctionWeightedRadial::operator<(), nnp::SymmetryFunctionAngularWide::operator<(), nnp::SymmetryFunctionWeightedAngular::operator<(), nnp::SymmetryFunctionAngularNarrow::operator<(), nnp::SymmetryFunctionRadial::operator==(), nnp::SymmetryFunctionWeightedRadial::operator==(), nnp::SymmetryFunctionAngularWide::operator==(), nnp::SymmetryFunctionWeightedAngular::operator==(), nnp::SymmetryFunctionAngularNarrow::operator==(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), nnp::SymmetryFunctionAngularNarrow::setParameters(), and ~SymmetryFunction().
convLength
double nnp::SymmetryFunction::convLength protected
Data set normalization length conversion factor.
Definition at line 294 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionWeightedRadial::calculateRadialPart(), nnp::SymmetryFunctionRadial::calculateRadialPart(), nnp::SymmetryFunctionWeightedAngular::calculateRadialPart(), nnp::SymmetryFunctionAngularWide::calculateRadialPart(), nnp::SymmetryFunctionAngularNarrow::calculateRadialPart(), nnp::SymmetryFunctionWeightedRadial::changeLengthUnit(), nnp::SymmetryFunctionRadial::changeLengthUnit(), nnp::SymmetryFunctionAngularWide::changeLengthUnit(), nnp::SymmetryFunctionWeightedAngular::changeLengthUnit(), nnp::SymmetryFunctionAngularNarrow::changeLengthUnit(), getConvLength(), nnp::SymmetryFunctionWeightedRadial::getSettingsLine(), nnp::SymmetryFunctionRadial::getSettingsLine(), nnp::SymmetryFunctionAngularWide::getSettingsLine(), nnp::SymmetryFunctionWeightedAngular::getSettingsLine(), nnp::SymmetryFunctionAngularNarrow::getSettingsLine(), nnp::SymmetryFunctionRadial::parameterInfo(), nnp::SymmetryFunctionWeightedRadial::parameterInfo(), nnp::SymmetryFunctionAngularWide::parameterInfo(), nnp::SymmetryFunctionWeightedAngular::parameterInfo(), nnp::SymmetryFunctionAngularNarrow::parameterInfo(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), and ~SymmetryFunction().
fc
CutoffFunction nnp::SymmetryFunction::fc protected
Cutoff function used by this symmetry function.
Definition at line 296 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), nnp::SymmetryFunctionWeightedRadial::calculateRadialPart(), nnp::SymmetryFunctionRadial::calculateRadialPart(), nnp::SymmetryFunctionWeightedAngular::calculateRadialPart(), nnp::SymmetryFunctionAngularWide::calculateRadialPart(), nnp::SymmetryFunctionAngularNarrow::calculateRadialPart(), nnp::SymmetryFunctionWeightedRadial::changeLengthUnit(), nnp::SymmetryFunctionRadial::changeLengthUnit(), nnp::SymmetryFunctionAngularWide::changeLengthUnit(), nnp::SymmetryFunctionWeightedAngular::changeLengthUnit(), nnp::SymmetryFunctionAngularNarrow::changeLengthUnit(), nnp::SymmetryFunctionWeightedRadial::setParameters(), nnp::SymmetryFunctionRadial::setParameters(), nnp::SymmetryFunctionAngularWide::setParameters(), nnp::SymmetryFunctionWeightedAngular::setParameters(), and nnp::SymmetryFunctionAngularNarrow::setParameters().
cutoffType
CutoffFunction::CutoffType nnp::SymmetryFunction::cutoffType protected
Cutoff type used by this symmetry function.
Definition at line 298 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), getCutoffType(), nnp::SymmetryFunctionWeightedRadial::operator<(), nnp::SymmetryFunctionRadial::operator<(), nnp::SymmetryFunctionWeightedAngular::operator<(), nnp::SymmetryFunctionAngularWide::operator<(), nnp::SymmetryFunctionAngularNarrow::operator<(), nnp::SymmetryFunctionWeightedRadial::operator==(), nnp::SymmetryFunctionRadial::operator==(), nnp::SymmetryFunctionAngularWide::operator==(), nnp::SymmetryFunctionWeightedAngular::operator==(), nnp::SymmetryFunctionAngularNarrow::operator==(), nnp::SymmetryFunctionWeightedRadial::parameterLine(), nnp::SymmetryFunctionRadial::parameterLine(), nnp::SymmetryFunctionWeightedAngular::parameterLine(), nnp::SymmetryFunctionAngularWide::parameterLine(), nnp::SymmetryFunctionAngularNarrow::parameterLine(), and ~SymmetryFunction().
scalingType
ScalingType nnp::SymmetryFunction::scalingType protected
Symmetry function scaling type used by this symmetry function.
Definition at line 300 of file SymmetryFunction.h.
Referenced by scale(), scalingLine(), unscale(), and ~SymmetryFunction().
parameters
std::set<std::string> nnp::SymmetryFunction::parameters protected
Set with symmetry function parameter IDs (lookup for printing).
Definition at line 302 of file SymmetryFunction.h.
Referenced by getParameters(), getPrintFormat(), SymmetryFunction(), nnp::SymmetryFunctionAngularNarrow::SymmetryFunctionAngularNarrow(), nnp::SymmetryFunctionAngularWide::SymmetryFunctionAngularWide(), nnp::SymmetryFunctionRadial::SymmetryFunctionRadial(), nnp::SymmetryFunctionWeightedAngular::SymmetryFunctionWeightedAngular(), and nnp::SymmetryFunctionWeightedRadial::SymmetryFunctionWeightedRadial().
indexPerElement
std::vector<std::size_t> nnp::SymmetryFunction::indexPerElement protected
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
Definition at line 304 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::calculate(), nnp::SymmetryFunctionWeightedRadial::calculate(), nnp::SymmetryFunctionWeightedAngular::calculate(), nnp::SymmetryFunctionAngularWide::calculate(), nnp::SymmetryFunctionAngularNarrow::calculate(), getIndexPerElement(), setIndexPerElement(), and SymmetryFunction().
sfinfoWidth
size_t const SymmetryFunction::sfinfoWidth = 12 static protected
Width of the SFINFO parameter description field (see parameterInfo()).
Definition at line 306 of file SymmetryFunction.h.
Referenced by nnp::SymmetryFunctionRadial::parameterInfo(), nnp::SymmetryFunctionWeightedRadial::parameterInfo(), nnp::SymmetryFunctionWeightedAngular::parameterInfo(), nnp::SymmetryFunctionAngularWide::parameterInfo(), and nnp::SymmetryFunctionAngularNarrow::parameterInfo().
printFormat
SymmetryFunction::PrintFormat const SymmetryFunction::printFormat = initializePrintFormat() static protected
Map of parameter format strings and empty strings.
Definition at line 308 of file SymmetryFunction.h.
Referenced by getPrintFormat().
printOrder
SymmetryFunction::PrintOrder const SymmetryFunction::printOrder = initializePrintOrder() static protected
Vector of parameters in order of printing.
Definition at line 310 of file SymmetryFunction.h.
Referenced by getPrintFormat().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunction.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunction.cpp