n2p2 - A neural network potential package: nnp::SymmetryFunctionGroupAngularNarrow Class Reference
nnp::SymmetryFunctionGroupAngularNarrow Class Reference
Angular symmetry function group (type 3)
#include <SymmetryFunctionGroupAngularNarrow.h>
Public Member Functions
SymmetryFunctionGroupAngularNarrow (ElementMap const &elementMap)
Constructor, sets type = 3.
bool operator== (SymmetryFunctionGroup const &rhs) const
Overload == operator.
bool operator!= (SymmetryFunctionGroup const &rhs) const
Overload != operator.
bool operator< (SymmetryFunctionGroup const &rhs) const
Overload < operator.
bool operator> (SymmetryFunctionGroup const &rhs) const
Overload > operator.
bool operator<= (SymmetryFunctionGroup const &rhs) const
Overload <= operator.
bool operator>= (SymmetryFunctionGroup const &rhs) const
Overload >= operator.
bool addMember (SymmetryFunction const *const symmetryFunction)
Potentially add a member to group.
void sortMembers ()
Sort member symmetry functions.
void setScalingFactors ()
Fill scalingFactors with values from member symmetry functions.
void calculate (Atom &atom, bool const derivatives) const
Calculate all symmetry functions of this group for one atom.
std::vector< std::string > parameterLines () const
Give symmetry function group parameters on multiple lines.
Public Member Functions inherited from nnp::SymmetryFunctionGroup
virtual ~SymmetryFunctionGroup ()
Virtual destructor.
void setIndex (std::size_t index)
Set private index member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getType () const
Get private type member variable.
std::size_t getEc () const
Get private ec member variable.
Private Attributes
std::size_t e1
Element index of neighbor atom 1 (common feature).
std::size_t e2
Element index of neighbor atom 2 (common feature).
std::vector< SymmetryFunctionAngularNarrow const * > members
Vector of all group member pointers.
std::vector< bool > calculateExp
Vector indicating whether exponential term needs to be calculated.
std::vector< double > factorNorm
Vector containing precalculated normalizing factor for each zeta.
std::vector< double > factorDeriv
Vector containing precalculated normalizing factor for derivatives.
std::vector< bool > useIntegerPow
Vector containing values of all member symmetry functions.
std::vector< int > zetaInt
Vector containing values of all member symmetry functions.
std::vector< double > eta
Vector containing values of all member symmetry functions.
std::vector< double > zeta
Vector containing values of all member symmetry functions.
std::vector< double > lambda
Vector containing values of all member symmetry functions.
std::vector< double > zetaLambda
Vector containing values of all member symmetry functions.
std::vector< double > rs
Vector containing values of all member symmetry functions.
Additional Inherited Members
Protected Types inherited from nnp::SymmetryFunctionGroup
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymmetryFunctionGroup
SymmetryFunctionGroup (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
std::string getPrintFormatCommon () const
Get common parameter line format string.
std::string getPrintFormatMember () const
Get member parameter line format string.
Static Protected Member Functions inherited from nnp::SymmetryFunctionGroup
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymmetryFunctionGroup
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function group index.
std::size_t ec
Element index of center atom (common feature).
double rc
Cutoff radius (common feature).
double cutoffAlpha
Cutoff function parameter (common feature).
double convLength
Data set normalization length conversion factor.
CutoffFunction fc
Cutoff function used by this symmetry function group.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function group (common feature).
std::vector< size_t > memberIndex
Vector containing indices of all member symmetry functions.
std::vector< double > scalingFactors
Scaling factors of all member symmetry functions.
std::set< std::string > parametersCommon
Set of common parameters IDs.
std::set< std::string > parametersMember
Set of common parameters IDs.
std::vector< std::vector< std::size_t > > memberIndexPerElement
Vector containing per-element indices of all member symmetry functions.
Static Protected Attributes inherited from nnp::SymmetryFunctionGroup
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Angular symmetry function group (type 3)
Common features:
element of central atom
element of neighbor atom 1
element of neighbor atom 2
cutoff type
Definition at line 50 of file SymmetryFunctionGroupAngularNarrow.h.
Constructor & Destructor Documentation
SymmetryFunctionGroupAngularNarrow()
SymmetryFunctionGroupAngularNarrow::SymmetryFunctionGroupAngularNarrow (ElementMap const & elementMap)
Constructor, sets type = 3.
Definition at line 31 of file SymmetryFunctionGroupAngularNarrow.cpp.
References operator==(), nnp::SymmetryFunctionGroup::parametersCommon, and nnp::SymmetryFunctionGroup::parametersMember.
                                                                  :
     SymmetryFunctionGroup(3, elementMap),
     e1(0),
     e2(0)
 {
     parametersCommon.insert("e1");
     parametersCommon.insert("e2");
     parametersMember.insert("eta");
     parametersMember.insert("rs");
     parametersMember.insert("lambda");
     parametersMember.insert("zeta");
     parametersMember.insert("mindex");
     parametersMember.insert("sfindex");
     parametersMember.insert("calcexp");
 }
Member Function Documentation
operator==()
bool SymmetryFunctionGroupAngularNarrow::operator== (SymmetryFunctionGroup const & rhs) const virtual
Overload == operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 49 of file SymmetryFunctionGroupAngularNarrow.cpp.
References nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffType, e1, e2, nnp::SymmetryFunctionGroup::ec, nnp::SymmetryFunctionGroup::getEc(), nnp::SymmetryFunctionGroup::getType(), operator<(), nnp::SymmetryFunctionGroup::rc, and nnp::SymmetryFunctionGroup::type.
Referenced by SymmetryFunctionGroupAngularNarrow().
 {
     if (ec   != rhs.getEc()  ) return false;
     if (type != rhs.getType()) return false;
     SymmetryFunctionGroupAngularNarrow const& c =
         dynamic_cast<SymmetryFunctionGroupAngularNarrow const&>(rhs);
     if (cutoffType  != c.cutoffType ) return false;
     if (cutoffAlpha != c.cutoffAlpha) return false;
     if (rc          != c.rc         ) return false;
     if (e1          != c.e1         ) return false;
     if (e2          != c.e2         ) return false;
     return true;
 }
operator!=()
bool nnp::SymmetryFunctionGroupAngularNarrow::operator!= (SymmetryFunctionGroup const & rhs) const inline virtual
Overload != operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 139 of file SymmetryFunctionGroupAngularNarrow.h.
References operator>().
 {
     return !((*this) == rhs);
 }
operator<()
bool SymmetryFunctionGroupAngularNarrow::operator< (SymmetryFunctionGroup const & rhs) const virtual
Overload < operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 64 of file SymmetryFunctionGroupAngularNarrow.cpp.
References addMember(), nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffType, e1, e2, nnp::SymmetryFunctionGroup::ec, nnp::SymmetryFunctionGroup::getEc(), nnp::SymmetryFunctionGroup::getType(), nnp::SymmetryFunctionGroup::rc, and nnp::SymmetryFunctionGroup::type.
Referenced by operator==().
 {
     if      (ec   < rhs.getEc()  ) return true;
     else if (ec   > rhs.getEc()  ) return false;
     if      (type < rhs.getType()) return true;
     else if (type > rhs.getType()) return false;
     SymmetryFunctionGroupAngularNarrow const& c =
         dynamic_cast<SymmetryFunctionGroupAngularNarrow const&>(rhs);
     if      (cutoffType  < c.cutoffType ) return true;
     else if (cutoffType  > c.cutoffType ) return false;
     if      (cutoffAlpha < c.cutoffAlpha) return true;
     else if (cutoffAlpha > c.cutoffAlpha) return false;
     if      (rc          < c.rc         ) return true;
     else if (rc          > c.rc         ) return false;
     if      (e1          < c.e1         ) return true;
     else if (e1          > c.e1         ) return false;
     if      (e2          < c.e2         ) return true;
     else if (e2          > c.e2         ) return false;
     return false;
 }
operator>()
bool nnp::SymmetryFunctionGroupAngularNarrow::operator> (SymmetryFunctionGroup const & rhs) const inline virtual
Overload > operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 145 of file SymmetryFunctionGroupAngularNarrow.h.
References operator<=().
Referenced by operator!=().
 {
     return rhs < (*this);
 }
operator<=()
bool nnp::SymmetryFunctionGroupAngularNarrow::operator<= (SymmetryFunctionGroup const & rhs) const inline virtual
Overload <= operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 151 of file SymmetryFunctionGroupAngularNarrow.h.
References operator>=().
Referenced by operator>().
 {
     return !((*this) > rhs);
 }
operator>=()
bool nnp::SymmetryFunctionGroupAngularNarrow::operator>= (SymmetryFunctionGroup const & rhs) const inline virtual
Overload >= operator.
Implements nnp::SymmetryFunctionGroup.
Definition at line 157 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by operator<=().
 {
     return !((*this) < rhs);
 }
addMember()
bool SymmetryFunctionGroupAngularNarrow::addMember (SymmetryFunction const *const symmetryFunction) virtual
Potentially add a member to group.
Parameters
[in] symmetryFunction Candidate symmetry function.
Returns
If addition was successful.
If symmetry function is compatible with common feature list its pointer will be added to members.
Implements nnp::SymmetryFunctionGroup.
Definition at line 86 of file SymmetryFunctionGroupAngularNarrow.cpp.
References nnp::SymmetryFunctionGroup::convLength, nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffType, e1, e2, nnp::SymmetryFunctionGroup::ec, nnp::SymmetryFunctionGroup::fc, nnp::SymmetryFunction::getConvLength(), nnp::SymmetryFunction::getCutoffAlpha(), nnp::SymmetryFunction::getCutoffType(), nnp::SymmetryFunctionAngularNarrow::getE1(), nnp::SymmetryFunctionAngularNarrow::getE2(), nnp::SymmetryFunction::getEc(), nnp::SymmetryFunction::getRc(), nnp::SymmetryFunction::getType(), members, nnp::SymmetryFunctionGroup::rc, nnp::CutoffFunction::setCutoffParameter(), nnp::CutoffFunction::setCutoffRadius(), nnp::CutoffFunction::setCutoffType(), and nnp::SymmetryFunctionGroup::type.
Referenced by operator<().
 {
     if (symmetryFunction->getType() != type) return false;
     SymmetryFunctionAngularNarrow const* sf =
         dynamic_cast<SymmetryFunctionAngularNarrow const*>(
         symmetryFunction);
     if (members.empty())
     {
         cutoffType  = sf->getCutoffType();
         cutoffAlpha = sf->getCutoffAlpha();
         ec          = sf->getEc();
         rc          = sf->getRc();
         e1          = sf->getE1();
         e2          = sf->getE2();
         convLength  = sf->getConvLength();
         fc.setCutoffType(cutoffType);
         fc.setCutoffRadius(rc);
         fc.setCutoffParameter(cutoffAlpha);
     }
     if (sf->getCutoffType()  != cutoffType ) return false;
     if (sf->getCutoffAlpha() != cutoffAlpha) return false;
     if (sf->getEc()          != ec         ) return false;
     if (sf->getRc()          != rc         ) return false;
     if (sf->getE1()          != e1         ) return false;
     if (sf->getE2()          != e2         ) return false;
     if (sf->getConvLength()  != convLength )
     {
         throw runtime_error("ERROR: Unable to add symmetry function members "
                             "with different conversion factors.\n");
     }
     members.push_back(sf);
     return true;
 }
sortMembers()
void SymmetryFunctionGroupAngularNarrow::sortMembers () virtual
Sort member symmetry functions.
Also allocate and precalculate additional stuff.
Implements nnp::SymmetryFunctionGroup.
Definition at line 126 of file SymmetryFunctionGroupAngularNarrow.cpp.
References calculateExp, eta, factorDeriv, factorNorm, nnp::SymmetryFunctionGroup::getIndex(), lambda, nnp::SymmetryFunctionGroup::memberIndex, nnp::SymmetryFunctionGroup::memberIndexPerElement, members, rs, useIntegerPow, zeta, zetaInt, and zetaLambda.
 {
     sort(members.begin(),
          members.end(),
          comparePointerTargets<SymmetryFunctionAngularNarrow const>);
     // Members are now sorted with eta changing the slowest.
     for (size_t i = 0; i < members.size(); i++)
     {
         factorNorm.push_back(pow(2.0, 1.0 - members[i]->getZeta()));
         factorDeriv.push_back(2.0 * members[i]->getEta() /
                               members[i]->getZeta() / members[i]->getLambda());
         if (i == 0)
         {
             calculateExp.push_back(true);
         }
         else
         {
             if ( members[i - 1]->getEta() != members[i]->getEta() ||
                  members[i - 1]->getRs()  != members[i]->getRs() )
             {
                 calculateExp.push_back(true);
             }
             else
             {
                 calculateExp.push_back(false);
             }
         }
         useIntegerPow.push_back(members[i]->getUseIntegerPow());
         memberIndex.push_back(members[i]->getIndex());
         zetaInt.push_back(members[i]->getZetaInt());
         eta.push_back(members[i]->getEta());
         rs.push_back(members[i]->getRs());
         zeta.push_back(members[i]->getZeta());
         lambda.push_back(members[i]->getLambda());
         zetaLambda.push_back(members[i]->getZeta() * members[i]->getLambda());
         memberIndexPerElement.push_back(members[i]->getIndexPerElement());
     }
     return;
 }
setScalingFactors()
void SymmetryFunctionGroupAngularNarrow::setScalingFactors () virtual
Fill scalingFactors with values from member symmetry functions.
Implements nnp::SymmetryFunctionGroup.
Definition at line 168 of file SymmetryFunctionGroupAngularNarrow.cpp.
References factorNorm, members, and nnp::SymmetryFunctionGroup::scalingFactors.
 {
     scalingFactors.resize(members.size(), 0.0);
     for (size_t i = 0; i < members.size(); i++)
     {
         scalingFactors.at(i) = members[i]->getScalingFactor();
         factorNorm.at(i) *= scalingFactors.at(i);
     }
     return;
 }
calculate()
void SymmetryFunctionGroupAngularNarrow::calculate (Atom & atom, bool const derivatives) const virtual
Calculate all symmetry functions of this group for one atom.
Parameters
[in,out] atom Atom for which symmetry functions are caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymmetryFunctionGroup.
Definition at line 186 of file SymmetryFunctionGroupAngularNarrow.cpp.
References calculateExp, nnp::Atom::Neighbor::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::Atom::Neighbor::cutoffType, nnp::SymmetryFunctionGroup::cutoffType, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dfc, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, e1, e2, nnp::Atom::Neighbor::element, eta, factorDeriv, factorNorm, nnp::Atom::Neighbor::fc, nnp::SymmetryFunctionGroup::fc, nnp::CutoffFunction::fdf(), nnp::Atom::G, lambda, nnp::SymmetryFunctionGroup::memberIndex, nnp::SymmetryFunctionGroup::memberIndexPerElement, members, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::pow_int(), nnp::Vec3D::r, nnp::Atom::Neighbor::rc, nnp::SymmetryFunctionGroup::rc, rs, nnp::SymmetryFunctionGroup::scalingFactors, useIntegerPow, zeta, zetaInt, and zetaLambda.
 {
     double* result = new double[members.size()];
     for (size_t l = 0; l < members.size(); ++l)
     {
         result[l] = 0.0;
     }
     double const rc2 = rc * rc;
     size_t numNeighbors = atom.numNeighbors;
     // Prevent problematic condition in loop test below (j < numNeighbors - 1).
     if (numNeighbors == 0) numNeighbors = 1;
     for (size_t j = 0; j < numNeighbors - 1; j++)
     {
         Atom::Neighbor& nj = atom.neighbors[j];
         size_t const nej = nj.element;
         double const rij = nj.d;
         if ((e1 == nej || e2 == nej) && rij < rc)
         {
             double const r2ij = rij * rij;
             // Calculate cutoff function and derivative.
 #ifdef NOCFCACHE
             double pfcij;
             double pdfcij;
             fc.fdf(rij, pfcij, pdfcij);
 #else
             // If cutoff radius matches with the one in the neighbor storage
             // we can use the previously calculated value.
             double& pfcij = nj.fc;
             double& pdfcij = nj.dfc;
             if (nj.cutoffType != cutoffType ||
                 nj.rc != rc ||
                 nj.cutoffAlpha != cutoffAlpha)
             {
                 fc.fdf(rij, pfcij, pdfcij);
                 nj.rc = rc;
                 nj.cutoffType = cutoffType;
                 nj.cutoffAlpha = cutoffAlpha;
             }
 #endif
             // SIMPLE EXPRESSIONS:
             //Vec3D const drij(atom.neighbors[j].dr);
             //double const* const dr1 = drij.r;
             double const* const dr1 = nj.dr.r;
             for (size_t k = j + 1; k < numNeighbors; k++)
             {
                 Atom::Neighbor& nk = atom.neighbors[k];
                 size_t const nek = nk.element;
                 if ((e1 == nej && e2 == nek) ||
                     (e2 == nej && e1 == nek))
                 {
                     double const rik = nk.d;
                     if (rik < rc)
                     {
                         // SIMPLE EXPRESSIONS:
                         //Vec3D const drjk(atom.neighbors[k].dr
                         //               - atom.neighbors[j].dr);
                         //double rjk = drjk.norm2();
                         double const* const dr2 = nk.dr.r;
                         double dr3[3];
                         dr3[0] = dr2[0] - dr1[0];
                         dr3[1] = dr2[1] - dr1[1];
                         dr3[2] = dr2[2] - dr1[2];
                         double rjk = dr3[0] * dr3[0]
                                    + dr3[1] * dr3[1]
                                    + dr3[2] * dr3[2];
                         if (rjk < rc2)
{
                             // Energy calculation.
 #ifdef NOCFCACHE
                             double pfcik;
                             double pdfcik;
                             fc.fdf(rik, pfcik, pdfcik);
 #else
                             double& pfcik = nk.fc;
                             double& pdfcik = nk.dfc;
                             if (nk.cutoffType != cutoffType ||
                                 nk.rc != rc ||
                                 nk.cutoffAlpha != cutoffAlpha)
{
                                 fc.fdf(rik, pfcik, pdfcik);
                                 nk.rc = rc;
                                 nk.cutoffType = cutoffType;
                                 nk.cutoffAlpha = cutoffAlpha;
                             }
 #endif
                             rjk = sqrt(rjk);
                             double pfcjk;
                             double pdfcjk;
                             fc.fdf(rjk, pfcjk, pdfcjk);
                             // SIMPLE EXPRESSIONS:
                             //Vec3D const drik(atom.neighbors[k].dr);
                             //double const* const dr2 = drik.r;
                             //double const* const dr3 = drjk.r;
                             double const rinvijik = 1.0 / rij / rik;
                             // SIMPLE EXPRESSIONS:
                             //double const costijk = (drij * drik) * rinvijik;
                             double const costijk = (dr1[0] * dr2[0] +
                                                     dr1[1] * dr2[1] +
                                                     dr1[2] * dr2[2]) * rinvijik;
                             double const pfc = pfcij * pfcik * pfcjk;
                             double const r2ik = rik * rik;
                             double const r2sum = r2ij + r2ik + rjk * rjk;
                             double const pr1 = pfcik * pfcjk * pdfcij / rij;
                             double const pr2 = pfcij * pfcjk * pdfcik / rik;
                             double const pr3 = pfcij * pfcik * pdfcjk / rjk;
                             double vexp = 0.0;
                             double rijs = 0.0;
                             double riks = 0.0;
                             double rjks = 0.0;
                             for (size_t l = 0; l < members.size(); ++l)
{
                                 if (calculateExp[l])
{
                                     if (rs[l] > 0.0)
{
                                         rijs = rij - rs[l];
                                         riks = rik - rs[l];
                                         rjks = rjk - rs[l];
                                         vexp = exp(-eta[l] * (rijs * rijs
                                                             + riks * riks
                                                             + rjks * rjks));
                                     }
                                     else
{
                                         vexp = exp(-eta[l] * r2sum);
                                     }
                                 }
                                 double const plambda = 1.0
                                                      + lambda[l] * costijk;
                                 double fg = vexp;
                                 if (plambda <= 0.0) fg = 0.0;
                                 else
{
                                     if (useIntegerPow[l])
{
                                         fg *= pow_int(plambda, zetaInt[l] - 1);
                                     }
                                     else
{
                                         fg *= pow(plambda, zeta[l] - 1.0);
                                     }
                                 }
                                 result[l] += fg * plambda * pfc;
                                 // Force calculation.
                                 if (!derivatives) continue;
                                 fg *= factorNorm[l];
                                 double const pfczl = pfc * zetaLambda[l];
                                 double const p2etapl = plambda * factorDeriv[l];
                                 double p1;
                                 double p2;
                                 double p3;
                                 if (rs[l] > 0.0)
{
                                     p1 = fg * (pfczl * (rinvijik
                                        - costijk / r2ij - p2etapl
                                        * rijs / rij) + pr1 * plambda);
                                     p2 = fg * (pfczl * (rinvijik
                                        - costijk / r2ik - p2etapl
                                        * riks / rik) + pr2 * plambda);
                                     p3 = fg * (pfczl * (rinvijik
                                        + p2etapl * rjks / rjk)
                                        - pr3 * plambda);
                                 }
                                 else
{
                                     p1 = fg * (pfczl * (rinvijik - costijk
                                        / r2ij - p2etapl) + pr1 * plambda);
                                     p2 = fg * (pfczl * (rinvijik - costijk
                                        / r2ik - p2etapl) + pr2 * plambda);
                                     p3 = fg * (pfczl * (rinvijik + p2etapl)
                                        - pr3 * plambda);
                                 }
                                 // Save force contributions in Atom storage.
                                 //
                                 // SIMPLE EXPRESSIONS:
                                 //size_t const li = members[l]->getIndex();
                                 //atom.dGdr[li] += p1 * drij + p2 * drik;
                                 //atom.neighbors[j].dGdr[li] -= p1 * drij
                                 //                            + p3 * drjk;
                                 //atom.neighbors[k].dGdr[li] -= p2 * drik
                                 //                            - p3 * drjk;
                                 double const p1drijx = p1 * dr1[0];
                                 double const p1drijy = p1 * dr1[1];
                                 double const p1drijz = p1 * dr1[2];
                                 double const p2drikx = p2 * dr2[0];
                                 double const p2driky = p2 * dr2[1];
                                 double const p2drikz = p2 * dr2[2];
                                 double const p3drjkx = p3 * dr3[0];
                                 double const p3drjky = p3 * dr3[1];
                                 double const p3drjkz = p3 * dr3[2];
 #ifdef IMPROVED_SFD_MEMORY
                                 size_t li = memberIndex[l];
 #else
                                 size_t const li = memberIndex[l];
 #endif
                                 double* dGdr = atom.dGdr[li].r;
                                 dGdr[0] += p1drijx + p2drikx;
                                 dGdr[1] += p1drijy + p2driky;
                                 dGdr[2] += p1drijz + p2drikz;
 #ifdef IMPROVED_SFD_MEMORY
                                 li = memberIndexPerElement[l][nej];
 #endif
                                 dGdr = nj.dGdr[li].r;
                                 dGdr[0] -= p1drijx + p3drjkx;
                                 dGdr[1] -= p1drijy + p3drjky;
                                 dGdr[2] -= p1drijz + p3drjkz;
 #ifdef IMPROVED_SFD_MEMORY
                                 li = memberIndexPerElement[l][nek];
 #endif
                                 dGdr = nk.dGdr[li].r;
                                 dGdr[0] -= p2drikx - p3drjkx;
                                 dGdr[1] -= p2driky - p3drjky;
                                 dGdr[2] -= p2drikz - p3drjkz;
                             } // l
                         } // rjk <= rc
                     } // rik <= rc
                 } // elem
             } // k
         } // rij <= rc
     } // j
     for (size_t l = 0; l < members.size(); ++l)
     {
         result[l] *= factorNorm[l] / scalingFactors[l];
         atom.G[memberIndex[l]] = members[l]->scale(result[l]);
     }
     delete[] result;
     return;
 }
parameterLines()
vector< string > SymmetryFunctionGroupAngularNarrow::parameterLines () const virtual
Give symmetry function group parameters on multiple lines.
Returns
Vector of string containing symmetry function parameters lines.
Implements nnp::SymmetryFunctionGroup.
Definition at line 434 of file SymmetryFunctionGroupAngularNarrow.cpp.
References calculateExp, nnp::SymmetryFunctionGroup::convLength, nnp::SymmetryFunctionGroup::cutoffAlpha, nnp::SymmetryFunctionGroup::cutoffType, e1, e2, nnp::SymmetryFunctionGroup::ec, nnp::SymmetryFunctionGroup::elementMap, nnp::SymmetryFunctionGroup::getIndex(), nnp::SymmetryFunctionGroup::getPrintFormatCommon(), nnp::SymmetryFunctionGroup::getPrintFormatMember(), nnp::SymmetryFunctionGroup::index, members, nnp::SymmetryFunctionGroup::rc, nnp::strpr(), and nnp::SymmetryFunctionGroup::type.
 {
     vector<string> v;
     v.push_back(strpr(getPrintFormatCommon().c_str(),
                       index + 1,
                       elementMap[ec].c_str(),
                       type,
                       elementMap[e1].c_str(),
                       elementMap[e2].c_str(),
                       rc / convLength,
                       (int)cutoffType,
                       cutoffAlpha));
     for (size_t i = 0; i < members.size(); ++i)
     {
         v.push_back(strpr(getPrintFormatMember().c_str(),
                           members[i]->getEta() * convLength * convLength,
                           members[i]->getRs() / convLength,
                           members[i]->getLambda(),
                           members[i]->getZeta(),
                           members[i]->getLineNumber(),
                           i + 1,
                           members[i]->getIndex() + 1,
                           (int)calculateExp[i]));
     }
     return v;
 }
Member Data Documentation
e1
std::size_t nnp::SymmetryFunctionGroupAngularNarrow::e1 private
Element index of neighbor atom 1 (common feature).
Definition at line 107 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by addMember(), calculate(), operator<(), operator==(), and parameterLines().
e2
std::size_t nnp::SymmetryFunctionGroupAngularNarrow::e2 private
Element index of neighbor atom 2 (common feature).
Definition at line 109 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by addMember(), calculate(), operator<(), operator==(), and parameterLines().
members
std::vector<SymmetryFunctionAngularNarrow const*> nnp::SymmetryFunctionGroupAngularNarrow::members private
Vector of all group member pointers.
Definition at line 111 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by addMember(), calculate(), parameterLines(), setScalingFactors(), and sortMembers().
calculateExp
std::vector<bool> nnp::SymmetryFunctionGroupAngularNarrow::calculateExp private
Vector indicating whether exponential term needs to be calculated.
Definition at line 113 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), parameterLines(), and sortMembers().
factorNorm
std::vector<double> nnp::SymmetryFunctionGroupAngularNarrow::factorNorm private
Vector containing precalculated normalizing factor for each zeta.
Definition at line 115 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), setScalingFactors(), and sortMembers().
factorDeriv
std::vector<double> nnp::SymmetryFunctionGroupAngularNarrow::factorDeriv private
Vector containing precalculated normalizing factor for derivatives.
Definition at line 117 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), and sortMembers().
useIntegerPow
std::vector<bool> nnp::SymmetryFunctionGroupAngularNarrow::useIntegerPow private
Vector containing values of all member symmetry functions.
Definition at line 119 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), and sortMembers().
zetaInt
std::vector<int> nnp::SymmetryFunctionGroupAngularNarrow::zetaInt private
Vector containing values of all member symmetry functions.
Definition at line 121 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), and sortMembers().
eta
std::vector<double> nnp::SymmetryFunctionGroupAngularNarrow::eta private
Vector containing values of all member symmetry functions.
Definition at line 123 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), and sortMembers().
zeta
std::vector<double> nnp::SymmetryFunctionGroupAngularNarrow::zeta private
Vector containing values of all member symmetry functions.
Definition at line 125 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), and sortMembers().
lambda
std::vector<double> nnp::SymmetryFunctionGroupAngularNarrow::lambda private
Vector containing values of all member symmetry functions.
Definition at line 127 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), and sortMembers().
zetaLambda
std::vector<double> nnp::SymmetryFunctionGroupAngularNarrow::zetaLambda private
Vector containing values of all member symmetry functions.
Definition at line 129 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), and sortMembers().
rs
std::vector<double> nnp::SymmetryFunctionGroupAngularNarrow::rs private
Vector containing values of all member symmetry functions.
Definition at line 131 of file SymmetryFunctionGroupAngularNarrow.h.
Referenced by calculate(), and sortMembers().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunctionGroupAngularNarrow.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunctionGroupAngularNarrow.cpp