n2p2 - A neural network potential package: nnp::SymmetryFunctionRadial Class Reference
nnp::SymmetryFunctionRadial Class Reference
Radial symmetry function (type 2)
#include <SymmetryFunctionRadial.h>
Public Member Functions
SymmetryFunctionRadial (ElementMap const &elementMap)
Constructor, sets type = 2.
bool operator== (SymmetryFunction const &rhs) const
Overload == operator.
bool operator!= (SymmetryFunction const &rhs) const
Overload != operator.
bool operator< (SymmetryFunction const &rhs) const
Overload < operator.
bool operator> (SymmetryFunction const &rhs) const
Overload > operator.
bool operator<= (SymmetryFunction const &rhs) const
Overload <= operator.
bool operator>= (SymmetryFunction const &rhs) const
Overload >= operator.
void setParameters (std::string const &parameterString)
Set symmetry function parameters.
void changeLengthUnit (double convLength)
Change length unit.
std::string getSettingsLine () const
Get settings file line from currently set parameters.
void calculate (Atom &atom, bool const derivatives) const
Calculate symmetry function for one atom.
std::string parameterLine () const
Give symmetry function parameters in one line.
std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
std::size_t getE1 () const
Get private e1 member variable.
double getEta () const
Get private eta member variable.
double getRs () const
Get private rs member variable.
double calculateRadialPart (double distance) const
Calculate (partial) symmetry function value for one given distance.
double calculateAngularPart (double angle) const
Calculate (partial) symmetry function value for one given angle.
bool checkRelevantElement (std::size_t index) const
Check whether symmetry function is relevant for given element.
Public Member Functions inherited from nnp::SymmetryFunction
virtual ~SymmetryFunction ()
Virtual destructor.
void setCutoffFunction (CutoffFunction::CutoffType cutoffType, double cutoffAlpha)
Set cutoff function type and parameter.
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
double scale (double value) const
Apply symmetry function scaling and/or centering.
double unscale (double value) const
Undo symmetry function scaling and/or centering.
std::size_t getType () const
Get private type member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getLineNumber () const
Get private lineNumber member variable.
std::size_t getEc () const
Get private ec member variable.
std::size_t getMinNeighbors () const
Get private minNeighbors member variable.
double getRc () const
Get private rc member variable.
double getGmin () const
Get private Gmin member variable.
double getGmax () const
Get private Gmax member variable.
double getScalingFactor () const
Get private scalingFactor member variable.
double getCutoffAlpha () const
Get private cutoffAlpha member variable.
double getConvLength () const
Get private convLength member variable.
CutoffFunction::CutoffType getCutoffType () const
Get private cutoffType member variable.
std::set< std::string > getParameters () const
Get private parameters member variable.
std::vector< std::size_t > getIndexPerElement () const
Get private indexPerElement member variable.
void setIndex (std::size_t index)
Set private index member variable.
void setIndexPerElement (std::size_t elementIndex, std::size_t index)
Set private indexPerElement member variable.
void setLineNumber (std::size_t lineNumber)
Set line number.
std::string scalingLine () const
Get string with scaling information.
Private Attributes
std::size_t e1
Element index of neighbor atom.
double eta
Width of gaussian.
double rs
Shift of gaussian.
Additional Inherited Members
Public Types inherited from nnp::SymmetryFunction
enum ScalingType {
ST_NONE, ST_SCALE, ST_CENTER, ST_SCALECENTER,
ST_SCALESIGMA
}
List of available scaling types.
Protected Types inherited from nnp::SymmetryFunction
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymmetryFunction
SymmetryFunction (std::size_t type, ElementMap const &)
Constructor, initializes type.
std::string getPrintFormat () const
Generate format string for symmetry function parameter printing.
Static Protected Member Functions inherited from nnp::SymmetryFunction
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymmetryFunction
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function index (per element).
std::size_t lineNumber
Line number.
std::size_t ec
Element index of center atom.
std::size_t minNeighbors
Minimum number of neighbors required.
double Smin
Minimum for scaling range.
double Smax
Maximum for scaling range.
double Gmin
Minimum unscaled symmetry function value.
double Gmax
Maximum unscaled symmetry function value.
double Gmean
Mean unscaled symmetry function value.
double Gsigma
Sigma of unscaled symmetry function values.
double rc
Cutoff radius .
double scalingFactor
Scaling factor.
double cutoffAlpha
Cutoff parameter .
double convLength
Data set normalization length conversion factor.
CutoffFunction fc
Cutoff function used by this symmetry function.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function.
ScalingType scalingType
Symmetry function scaling type used by this symmetry function.
std::set< std::string > parameters
Set with symmetry function parameter IDs (lookup for printing).
std::vector< std::size_t > indexPerElement
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
Static Protected Attributes inherited from nnp::SymmetryFunction
static std::size_t const sfinfoWidth = 12
Width of the SFINFO parameter description field (see parameterInfo()).
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Radial symmetry function (type 2)
Parameter string:
<element-central> 2 <element-neighbor> <eta> <rshift> <rcutoff>
where
<element-central> .... element symbol of central atom
<element-neighbor> ... element symbol of neighbor atom
<eta> ................
<rshift> .............
<rcutoff> ............
Definition at line 49 of file SymmetryFunctionRadial.h.
Constructor & Destructor Documentation
SymmetryFunctionRadial()
SymmetryFunctionRadial::SymmetryFunctionRadial (ElementMap const & elementMap)
Constructor, sets type = 2.
Definition at line 29 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::minNeighbors, and nnp::SymmetryFunction::parameters.
                                                                            :
     SymmetryFunction(2, elementMap),
     e1              (0  ),
     eta             (0.0),
     rs              (0.0)
 {
     minNeighbors = 1;
     parameters.insert("e1");
     parameters.insert("eta");
     parameters.insert("rs");
 }
Member Function Documentation
operator==()
bool SymmetryFunctionRadial::operator== (SymmetryFunction const & rhs) const virtual
Overload == operator.
Implements nnp::SymmetryFunction.
Definition at line 41 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::cutoffAlpha, nnp::SymmetryFunction::cutoffType, e1, nnp::SymmetryFunction::ec, eta, nnp::SymmetryFunction::getEc(), nnp::SymmetryFunction::getType(), nnp::SymmetryFunction::rc, rs, and nnp::SymmetryFunction::type.
 {
     if (ec   != rhs.getEc()  ) return false;
     if (type != rhs.getType()) return false;
     SymmetryFunctionRadial const& c =
         dynamic_cast<SymmetryFunctionRadial const&>(rhs);
     if (cutoffType  != c.cutoffType ) return false;
     if (cutoffAlpha != c.cutoffAlpha) return false;
     if (rc          != c.rc         ) return false;
     if (eta         != c.eta        ) return false;
     if (rs          != c.rs         ) return false;
     if (e1          != c.e1         ) return false;
     return true;
 }
operator!=()
bool nnp::SymmetryFunctionRadial::operator!= (SymmetryFunction const & rhs) const inline virtual
Overload != operator.
Implements nnp::SymmetryFunction.
Definition at line 150 of file SymmetryFunctionRadial.h.
 {
     return !((*this) == rhs);
 }
operator<()
bool SymmetryFunctionRadial::operator< (SymmetryFunction const & rhs) const virtual
Overload < operator.
Implements nnp::SymmetryFunction.
Definition at line 56 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::cutoffAlpha, nnp::SymmetryFunction::cutoffType, e1, nnp::SymmetryFunction::ec, eta, nnp::SymmetryFunction::getEc(), nnp::SymmetryFunction::getType(), nnp::SymmetryFunction::rc, rs, and nnp::SymmetryFunction::type.
 {
     if      (ec   < rhs.getEc()  ) return true;
     else if (ec   > rhs.getEc()  ) return false;
     if      (type < rhs.getType()) return true;
     else if (type > rhs.getType()) return false;
     SymmetryFunctionRadial const& c =
         dynamic_cast<SymmetryFunctionRadial const&>(rhs);
     if      (cutoffType  < c.cutoffType ) return true;
     else if (cutoffType  > c.cutoffType ) return false;
     if      (cutoffAlpha < c.cutoffAlpha) return true;
     else if (cutoffAlpha > c.cutoffAlpha) return false;
     if      (rc          < c.rc         ) return true;
     else if (rc          > c.rc         ) return false;
     if      (eta         < c.eta        ) return true;
     else if (eta         > c.eta        ) return false;
     if      (rs          < c.rs         ) return true;
     else if (rs          > c.rs         ) return false;
     if      (e1          < c.e1         ) return true;
     else if (e1          > c.e1         ) return false;
     return false;
 }
operator>()
bool nnp::SymmetryFunctionRadial::operator> (SymmetryFunction const & rhs) const inline virtual
Overload > operator.
Implements nnp::SymmetryFunction.
Definition at line 156 of file SymmetryFunctionRadial.h.
 {
     return rhs < (*this);
 }
operator<=()
bool nnp::SymmetryFunctionRadial::operator<= (SymmetryFunction const & rhs) const inline virtual
Overload <= operator.
Implements nnp::SymmetryFunction.
Definition at line 162 of file SymmetryFunctionRadial.h.
 {
     return !((*this) > rhs);
 }
operator>=()
bool nnp::SymmetryFunctionRadial::operator>= (SymmetryFunction const & rhs) const inline virtual
Overload >= operator.
Implements nnp::SymmetryFunction.
Definition at line 168 of file SymmetryFunctionRadial.h.
 {
     return !((*this) < rhs);
 }
setParameters()
void SymmetryFunctionRadial::setParameters (std::string const & parameterString) virtual
Set symmetry function parameters.
Parameters
[in] parameterString String containing radial symmetry function parameters.
Implements nnp::SymmetryFunction.
Definition at line 79 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::cutoffAlpha, e1, nnp::SymmetryFunction::ec, nnp::SymmetryFunction::elementMap, eta, nnp::SymmetryFunction::fc, nnp::SymmetryFunction::rc, nnp::reduce(), rs, nnp::CutoffFunction::setCutoffParameter(), nnp::CutoffFunction::setCutoffRadius(), nnp::split(), and nnp::SymmetryFunction::type.
 {
     vector<string> splitLine = split(reduce(parameterString));
     if (type != (size_t)atoi(splitLine.at(1).c_str()))
     {
         throw runtime_error("ERROR: Incorrect symmetry function type.\n");
     }
     ec   = elementMap[splitLine.at(0)];
     e1   = elementMap[splitLine.at(2)];
     eta  = atof(splitLine.at(3).c_str());
     rs   = atof(splitLine.at(4).c_str());
     rc   = atof(splitLine.at(5).c_str());
     fc.setCutoffRadius(rc);
     fc.setCutoffParameter(cutoffAlpha);
     return;
 }
changeLengthUnit()
void SymmetryFunctionRadial::changeLengthUnit (double convLength) virtual
Change length unit.
Parameters
[in] convLength Multiplicative length unit conversion factor.
Implements nnp::SymmetryFunction.
Definition at line 100 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::convLength, nnp::SymmetryFunction::cutoffAlpha, eta, nnp::SymmetryFunction::fc, nnp::SymmetryFunction::rc, rs, nnp::CutoffFunction::setCutoffParameter(), and nnp::CutoffFunction::setCutoffRadius().
 {
     this->convLength = convLength;
     eta /= convLength * convLength;
     rs *= convLength;
     rc *= convLength;
     fc.setCutoffRadius(rc);
     fc.setCutoffParameter(cutoffAlpha);
     return;
 }
getSettingsLine()
string SymmetryFunctionRadial::getSettingsLine () const virtual
Get settings file line from currently set parameters.
Returns
Settings file string ("symfunction_short ...").
Implements nnp::SymmetryFunction.
Definition at line 113 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::convLength, e1, nnp::SymmetryFunction::ec, nnp::SymmetryFunction::elementMap, eta, nnp::SymmetryFunction::rc, rs, nnp::strpr(), and nnp::SymmetryFunction::type.
 {
     string s = strpr("symfunction_short %2s %2zu %2s %16.8E %16.8E %16.8E\n",
                      elementMap[ec].c_str(),
                      type,
                      elementMap[e1].c_str(),
                      eta * convLength * convLength,
                      rs / convLength,
                      rc / convLength);
     return s;
 }
calculate()
void SymmetryFunctionRadial::calculate (Atom & atom, bool const derivatives) const virtual
Calculate symmetry function for one atom.
Parameters
[in,out] atom Atom for which the symmetry function is caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymmetryFunction.
Definition at line 126 of file SymmetryFunctionRadial.cpp.
References nnp::Atom::Neighbor::cutoffAlpha, nnp::SymmetryFunction::cutoffAlpha, nnp::Atom::Neighbor::cutoffType, nnp::SymmetryFunction::cutoffType, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dfc, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, e1, nnp::Atom::Neighbor::element, eta, nnp::Atom::Neighbor::fc, nnp::SymmetryFunction::fc, nnp::CutoffFunction::fdf(), nnp::Atom::G, nnp::SymmetryFunction::index, nnp::SymmetryFunction::indexPerElement, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::Atom::Neighbor::rc, nnp::SymmetryFunction::rc, rs, nnp::SymmetryFunction::scale(), and nnp::SymmetryFunction::scalingFactor.
 {
     double result = 0.0;
     for (size_t j = 0; j < atom.numNeighbors; ++j)
     {
         Atom::Neighbor& n = atom.neighbors[j];
         if (e1 == n.element && n.d < rc)
         {
             // Energy calculation.
             double const rij = n.d;
             double const pexp = exp(-eta * (rij - rs) * (rij - rs));
             // Calculate cutoff function and derivative.
 #ifdef NOCFCACHE
             double pfc;
             double pdfc;
             fc.fdf(rij, pfc, pdfc);
 #else
             // If cutoff radius matches with the one in the neighbor storage
             // we can use the previously calculated value.
             double& pfc = n.fc;
             double& pdfc = n.dfc;
             if (n.cutoffType != cutoffType ||
                 n.rc != rc ||
                 n.cutoffAlpha != cutoffAlpha)
             {
                 fc.fdf(rij, pfc, pdfc);
                 n.rc = rc;
                 n.cutoffType = cutoffType;
                 n.cutoffAlpha = cutoffAlpha;
             }
 #endif
             result += pexp * pfc;
             // Force calculation.
             if (!derivatives) continue;
             double const p1 = scalingFactor
                 * (pdfc - 2.0 * eta * (rij - rs)
                 * pfc) * pexp / rij;
             Vec3D dij = p1 * n.dr;
             // Save force contributions in Atom storage.
             atom.dGdr[index] += dij;
 #ifdef IMPROVED_SFD_MEMORY
             n.dGdr[indexPerElement[e1]] -= dij;
 #else
             n.dGdr[index] -= dij;
 #endif
         }
     }
     atom.G[index] = scale(result);
     return;
 }
parameterLine()
string SymmetryFunctionRadial::parameterLine () const virtual
Give symmetry function parameters in one line.
Returns
String containing symmetry function parameter values.
Implements nnp::SymmetryFunction.
Definition at line 183 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::convLength, nnp::SymmetryFunction::cutoffAlpha, nnp::SymmetryFunction::cutoffType, e1, nnp::SymmetryFunction::ec, nnp::SymmetryFunction::elementMap, eta, nnp::SymmetryFunction::getPrintFormat(), nnp::SymmetryFunction::index, nnp::SymmetryFunction::lineNumber, nnp::SymmetryFunction::rc, rs, nnp::strpr(), and nnp::SymmetryFunction::type.
 {
     return strpr(getPrintFormat().c_str(),
                  index + 1,
                  elementMap[ec].c_str(),
                  type,
                  elementMap[e1].c_str(),
                  eta * convLength * convLength,
                  rs / convLength,
                  rc / convLength,
                  (int)cutoffType,
                  cutoffAlpha,
                  lineNumber + 1);
 }
parameterInfo()
vector< string > SymmetryFunctionRadial::parameterInfo () const virtual
Get description with parameter names and values.
Returns
Vector of parameter description strings.
Reimplemented from nnp::SymmetryFunction.
Definition at line 198 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::convLength, e1, nnp::SymmetryFunction::elementMap, eta, nnp::pad(), nnp::SymmetryFunction::parameterInfo(), rs, nnp::SymmetryFunction::sfinfoWidth, and nnp::strpr().
 {
     vector<string> v = SymmetryFunction::parameterInfo();
     string s;
     size_t w = sfinfoWidth;
     s = "e1";
     v.push_back(strpr((pad(s, w) + "%s"    ).c_str(), elementMap[e1].c_str()));
     s = "eta";
     v.push_back(strpr((pad(s, w) + "%14.8E").c_str(),
                       eta * convLength * convLength));
     s = "rs";
     v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), rs / convLength));
     return v;
 }
getE1()
std::size_t nnp::SymmetryFunctionRadial::getE1 () const inline
Get private e1 member variable.
Definition at line 173 of file SymmetryFunctionRadial.h.
References e1.
Referenced by nnp::SymmetryFunctionGroupRadial::addMember().
 {
     return e1;
 }
getEta()
double nnp::SymmetryFunctionRadial::getEta () const inline
Get private eta member variable.
Definition at line 178 of file SymmetryFunctionRadial.h.
References eta.
 {
     return eta;
 }
getRs()
double nnp::SymmetryFunctionRadial::getRs () const inline
Get private rs member variable.
Definition at line 183 of file SymmetryFunctionRadial.h.
References rs.
 {
     return rs;
 }
calculateRadialPart()
double SymmetryFunctionRadial::calculateRadialPart (double distance) const virtual
Calculate (partial) symmetry function value for one given distance.
Parameters
[in] distance Distance between two atoms.
Returns
Implements nnp::SymmetryFunction.
Definition at line 215 of file SymmetryFunctionRadial.cpp.
References nnp::SymmetryFunction::convLength, eta, nnp::CutoffFunction::f(), nnp::SymmetryFunction::fc, and rs.
 {
     double const& r = distance * convLength;
     return exp(-eta * (r - rs) * (r - rs)) * fc.f(r);
 }
calculateAngularPart()
double SymmetryFunctionRadial::calculateAngularPart (double angle) const virtual
Calculate (partial) symmetry function value for one given angle.
Parameters
[in] angle Angle between triplet of atoms (in radians).
Returns
Implements nnp::SymmetryFunction.
Definition at line 222 of file SymmetryFunctionRadial.cpp.
 {
     return 1.0;
 }
checkRelevantElement()
bool SymmetryFunctionRadial::checkRelevantElement (std::size_t index) const virtual
Check whether symmetry function is relevant for given element.
Parameters
[in] index Index of given element.
Returns
True if symmetry function is sensitive to given element, false otherwise.
Implements nnp::SymmetryFunction.
Definition at line 227 of file SymmetryFunctionRadial.cpp.
References e1.
 {
     if (index == e1) return true;
     else return false;
 }
Member Data Documentation
e1
std::size_t nnp::SymmetryFunctionRadial::e1 private
Element index of neighbor atom.
Definition at line 138 of file SymmetryFunctionRadial.h.
Referenced by calculate(), checkRelevantElement(), getE1(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
eta
double nnp::SymmetryFunctionRadial::eta private
Width of gaussian.
Definition at line 140 of file SymmetryFunctionRadial.h.
Referenced by calculate(), calculateRadialPart(), changeLengthUnit(), getEta(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
rs
double nnp::SymmetryFunctionRadial::rs private
Shift of gaussian.
Definition at line 142 of file SymmetryFunctionRadial.h.
Referenced by calculate(), calculateRadialPart(), changeLengthUnit(), getRs(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunctionRadial.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SymmetryFunctionRadial.cpp